import {render,screen,fireEvent,cleanup,within} from '@testing-library/react';
import {afterEach,beforeEach,describe,it,expect,vi} from 'vitest';
import NFTPage from './NFTPage';
import {priceRange,selectMarketItems,marketStats,readFavorites} from './market';
import {matchesNFT,type NFT,type Listing} from './model';
const sample=(id:number):NFT=>({id,name:`原创 #${id}`,nameEn:`Original #${id}`,family:'蓝闪蝶',familyEn:'Morpho',palette:'Morpho',color:'#168aff',rarity:'典藏',wing:'round',pattern:'veins',halo:'nature',dna:'a'.repeat(64),image:`/nft/art/${id}.jpg`,theme:{kind:'original',name:'蝴蝶股票原创特别款',nameEn:'Butterfly Originals',ticker:'FLAP STOCK',edition:id,total:277,snapshot:'test'}});
const seller='0x1111111111111111111111111111111111111111';
const listing=(id:number,price:bigint,active=true):Listing=>({id,price,seller,active,version:1n});
describe('market calculations',()=>{
 it('sorts exact wei prices and excludes inactive orders from range filtering and stats',()=>{const orders=[listing(1,100000000000000001n),listing(2,100000000000000000n),listing(3,1n,false)];const map=new Map(orders.map(l=>[l.id,l]));const items=[sample(1),sample(2),sample(3)];expect(selectMarketItems(items,map,'price-asc').map(n=>n.id)).toEqual([2,1,3]);expect(selectMarketItems(items,map,'price-desc').map(n=>n.id)).toEqual([1,2,3]);expect(selectMarketItems(items,map,'price-asc','0.1','0.1').map(n=>n.id)).toEqual([2]);expect(marketStats(orders)).toEqual({count:2,sellers:1,floor:100000000000000000n});expect(marketStats([]).floor).toBeNull()});
 it('validates price boundaries without rounding or silently ignoring errors',()=>{expect(priceRange('0','')).toMatchObject({low:0n,error:''});expect(priceRange('2','1').error).toBeTruthy();expect(priceRange('no','').error).toBeTruthy();expect(priceRange('0.0000000000000000001','').error).toBeTruthy();expect(priceRange('0.000000000000000001','').low).toBe(1n)});
 it('keeps wishlist IDs valid and handles corrupt storage; numeric search is exact',()=>{expect(readFavorites('[1,1,7777,7778,0,"2",1.1]')).toEqual([1,7777]);expect(readFavorites('{')).toEqual([]);expect(matchesNFT(sample(1111),'#1','all')).toBe(false);expect(matchesNFT(sample(1),'#0001','original')).toBe(true)});
});
beforeEach(()=>{localStorage.clear();history.replaceState({},'','/');vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:true,json:async()=>[sample(1),sample(520)]}));HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','')};HTMLDialogElement.prototype.close=function(){this.removeAttribute('open')};Element.prototype.scrollIntoView=vi.fn();window.scrollTo=vi.fn()});
afterEach(()=>{cleanup();vi.unstubAllGlobals()});
it('persists wishlist, filters it and preserves it through language switching and reload',async()=>{render(<NFTPage/>);fireEvent.click(await screen.findByRole('button',{name:'加入心愿单 #520'}));fireEvent.click(screen.getByRole('button',{name:'♡ 心愿单 1'}));expect(screen.queryByRole('button',{name:'查看 原创 #1'})).not.toBeInTheDocument();expect(screen.getByRole('button',{name:'查看 原创 #520'})).toBeInTheDocument();fireEvent.click(screen.getByLabelText('Language / 语言'));expect(screen.getByRole('button',{name:'View Original #520'})).toBeInTheDocument();expect(screen.getByText('Your wishlist is saved in this browser. It does not represent on-chain ownership.')).toBeInTheDocument();cleanup();render(<NFTPage/>);expect(await screen.findByRole('button',{name:'Remove from wishlist #520'})).toHaveAttribute('aria-pressed','true')});
it('opens the market by URL, distinguishes unavailable stats and lets a seller connect',async()=>{history.replaceState({},'','/?nftView=market&lang=en');render(<NFTPage/>);const overview=await screen.findByRole('region',{name:'Marketplace overview'});expect(within(overview).getAllByText('—')).toHaveLength(3);expect(screen.queryByRole('button',{name:'Buy ↗'})).not.toBeInTheDocument();fireEvent.change(screen.getByRole('textbox',{name:'Min price BNB'}),{target:{value:'2'}});fireEvent.change(screen.getByRole('textbox',{name:'Max price BNB'}),{target:{value:'1'}});expect(screen.getByRole('alert')).toHaveTextContent('Minimum price cannot exceed maximum price');fireEvent.click(screen.getByRole('button',{name:'Sell an NFT ↗'}));expect(screen.getByRole('dialog')).toBeInTheDocument();expect(new URL(location.href).searchParams.get('nftView')).toBe('collection')});
