import {render,screen,fireEvent,waitFor,cleanup} from '@testing-library/react';
import {afterEach,beforeEach,it,expect,vi} from 'vitest';
import type {ChainState} from './chain';
const mocks=vi.hoisted(()=>({read:vi.fn(),send:vi.fn(),connect:vi.fn(),listeners:{} as Record<string,()=>void>}));
vi.mock('./chain',()=>({config:{enabled:true,collection:'0x3333333333333333333333333333333333333333'},emptyState:{total:0,reserved:0,owned:[],pending:[],listings:[],referral:null},readState:mocks.read,transact:mocks.send,connect:mocks.connect,walletProvider:()=>({on:(name:string,fn:()=>void)=>mocks.listeners[name]=fn,removeListener:vi.fn()})}));
import NFTPage from './NFTPage';
const account='0x1111111111111111111111111111111111111111',bound='0x2222222222222222222222222222222222222222';
const base:ChainState={total:0,reserved:0,owned:[],pending:[],listings:[],referral:{bound:null,invited:2n,minted:5n,earned:10000000000000000n,rewards:10000000000000000n}};
function deferred<T>(){let resolve!:(v:T)=>void,reject!:(e:Error)=>void;const promise=new Promise<T>((a,b)=>{resolve=a;reject=b});return {promise,resolve,reject}}
beforeEach(()=>{vi.clearAllMocks();localStorage.clear();history.replaceState({},'','/?ref='+bound);mocks.read.mockResolvedValue(base);mocks.connect.mockResolvedValue(account);mocks.send.mockResolvedValue({status:'success'});vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:true,json:async()=>[]}));HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','')};HTMLDialogElement.prototype.close=function(){this.removeAttribute('open')};Element.prototype.scrollIntoView=vi.fn()});
afterEach(()=>{cleanup();vi.unstubAllGlobals()});
async function mintConnect(){render(<NFTPage/>);fireEvent.click(screen.getByRole('button',{name:'随机批量铸造 ↗'}));fireEvent.click(screen.getByRole('button',{name:'5 张'}));fireEvent.click(screen.getByRole('button',{name:'连接钱包并保留草稿 ↗'}));await waitFor(()=>expect(mocks.read).toHaveBeenCalledWith(account))}
it('preserves draft across connect, requires acknowledgment, sends exact batch boundary',async()=>{await mintConnect();expect(screen.getByLabelText('铸造数量')).toHaveValue('5');expect(screen.getByLabelText('邀请地址')).toHaveValue(bound);const pay=await screen.findByRole('button',{name:'支付 0.05 BNB · 批量铸造 ↗'});expect(pay).toBeDisabled();fireEvent.click(screen.getByRole('checkbox'));expect(pay).toBeEnabled();fireEvent.click(pay);await waitFor(()=>expect(mocks.send).toHaveBeenCalledWith('mint',account,{quantity:5,referrer:bound},expect.any(Function)))});
it('on-chain binding defeats wrong URL and withdraws to current wallet through adapter',async()=>{history.replaceState({},'','/?ref=wrong');mocks.read.mockResolvedValue({...base,referral:{...base.referral!,bound}});await mintConnect();expect(screen.getByTestId('bound-referrer')).toHaveTextContent(bound);expect(screen.queryByRole('checkbox')).not.toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'支付 0.05 BNB · 批量铸造 ↗'}));await waitFor(()=>expect(mocks.send).toHaveBeenCalledWith('mint',account,{quantity:5,referrer:bound},expect.any(Function)));fireEvent.click(screen.getByRole('button',{name:'提现奖励到当前钱包 ↗'}));await waitFor(()=>expect(mocks.send).toHaveBeenCalledWith('withdraw',account,{},expect.any(Function)))});
it('revalidates a self-referral once wallet connects',async()=>{history.replaceState({},'','/?ref='+account);await mintConnect();fireEvent.click(screen.getByRole('checkbox'));expect(screen.getByRole('button',{name:'支付 0.05 BNB · 批量铸造 ↗'})).toBeDisabled();expect(screen.getByText(/邀请地址不能为自己/)).toBeInTheDocument()});
it('shows every pending ID and reveals only after successful receipt',async()=>{const tx=deferred<unknown>();mocks.send.mockReturnValue(tx.promise);mocks.read.mockImplementation(async(a?:string)=>a?{...base,pending:[{requestId:9n,quantity:3,tokenIds:[12,34,56]}]}:base);await mintConnect();fireEvent.click(screen.getByLabelText('关闭弹窗'));fireEvent.click(await screen.findByRole('button',{name:'整批领取到钱包 ↗'}));expect(screen.getByText('#0012 · #0034 · #0056')).toBeInTheDocument();expect(screen.queryByText('你的蝴蝶，已抵达。')).not.toBeInTheDocument();tx.resolve({status:'success'});await screen.findByText('你的蝴蝶，已抵达。');expect(screen.getAllByRole('img',{name:/已领取蝴蝶/})).toHaveLength(3)});
it('does not reveal on reverted claim',async()=>{mocks.send.mockRejectedValue(Error('链上交易失败'));mocks.read.mockResolvedValue({...base,pending:[{requestId:9n,quantity:1,tokenIds:[12]}]});await mintConnect();fireEvent.click(screen.getByLabelText('关闭弹窗'));fireEvent.click(screen.getByRole('button',{name:'整批领取到钱包 ↗'}));await screen.findByText('链上交易失败');expect(screen.queryByText('你的蝴蝶，已抵达。')).not.toBeInTheDocument()});
it.each(['resolve','reject'] as const)('ignores stale wallet read %s after an account change',async(mode)=>{const stale=deferred<ChainState>();mocks.read.mockImplementation((a?:string)=>a?stale.promise:Promise.resolve({...base,referral:null}));await mintConnect();mocks.listeners.accountsChanged();await waitFor(()=>expect(screen.getAllByText('暂不可用')).toHaveLength(4));if(mode==='resolve')stale.resolve({...base,referral:{...base.referral!,bound}});else stale.reject(Error('stale failure'));await new Promise(r=>setTimeout(r,0));expect(screen.queryByTestId('bound-referrer')).not.toBeInTheDocument();expect(screen.queryByText('stale failure')).not.toBeInTheDocument();expect(screen.getAllByText('暂不可用')).toHaveLength(4)});
it('keeps an unfulfilled batch waiting and disables claim',async()=>{mocks.read.mockResolvedValue({...base,pending:[{requestId:9n,quantity:5,tokenIds:[]}]});await mintConnect();fireEvent.click(screen.getByLabelText('关闭弹窗'));expect(screen.getByText('5 张正在等待随机编号')).toBeInTheDocument();expect(screen.getByRole('button',{name:'等待随机数'})).toBeDisabled()});
it('does not reveal a completed claim from a previous wallet session',async()=>{const tx=deferred<unknown>();mocks.send.mockReturnValue(tx.promise);mocks.read.mockImplementation(async(a?:string)=>a?{...base,pending:[{requestId:9n,quantity:1,tokenIds:[12]}]}:{...base,referral:null});await mintConnect();fireEvent.click(screen.getByLabelText('关闭弹窗'));fireEvent.click(screen.getByRole('button',{name:'整批领取到钱包 ↗'}));mocks.listeners.accountsChanged();tx.resolve({status:'success'});await waitFor(()=>expect(screen.getAllByText('暂不可用')).toHaveLength(4));expect(screen.queryByText('你的蝴蝶，已抵达。')).not.toBeInTheDocument()});
it('opens a real listing from artwork details and confirms the exact seller, price and version',async()=>{const seller='0x4444444444444444444444444444444444444444';const price=157770000000000001n;const item={id:520,name:'蝴蝶 #0520',family:'蓝闪蝶',palette:'Morpho',color:'#178bff',rarity:'典藏',wing:'round',pattern:'veins',halo:'自然光',dna:'a'.repeat(64),image:'/nft/art/520.jpg'};vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:true,json:async()=>[item]}));mocks.read.mockResolvedValue({...base,listings:[{id:520,seller,price,version:7n,active:true}]});await mintConnect();fireEvent.click(screen.getByLabelText('关闭弹窗'));fireEvent.click(await screen.findByRole('button',{name:'查看 蝴蝶 #0520'}));fireEvent.click(screen.getByRole('button',{name:'购买这张 NFT ↗'}));expect(screen.getByText('钱包确认时显示')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'确认支付 0.157770000000000001 BNB ↗'}));await waitFor(()=>expect(mocks.send).toHaveBeenCalledWith('buy',account,{id:520,price,seller,version:7n},expect.any(Function)))});
