import {useState,useEffect,useRef,useMemo,useCallback} from 'react';
import type {Address,Hash} from 'viem';
import {NFT,Listing,TREASURY,NFT_SUPPLY,parseBNB,formatBNB} from './model';
import {config,connect,readState,emptyState,transact,walletProvider,type ChainState,type PendingMint} from './chain';
import './nft.css';
import {MintForm,loadReferralDraft} from './components/MintForm';
import {ReferralPanel} from './components/ReferralPanel';
type View='discover'|'market'|'collection';
type Modal={kind:'mint'}|{kind:'detail';id:number}|{kind:'list';id:number}|{kind:'buy';listing:Listing}|{kind:'rules'}|{kind:'history'}|{kind:'wallet'}|{kind:'reveal';ids:number[]};
const pad=(id:number)=>String(id).padStart(4,'0');
const short=(a:string)=>`${a.slice(0,6)}…${a.slice(-4)}`;
function Mark(){return <svg viewBox="0 0 40 40" fill="currentColor" aria-hidden="true"><path d="M19 20C5 20 0 3 7 4c8 0 10 9 13 13C23 11 27 2 34 4c7 4-1 15-13 16 9 1 15 8 11 12-5 5-11-4-12-10-1 6-8 15-12 10-5-5 2-11 11-12Z"/></svg>}
const reason=(e:unknown)=>e instanceof Error?e.message.slice(0,250):'请求失败，请重试';
export default function NFTPage(){
 const [catalog,setCatalog]=useState<NFT[]>([]),[error,setError]=useState(''),[view,setView]=useState<View>('discover'),[state,setState]=useState<ChainState>(emptyState);
 const [modal,setModal]=useState<Modal|null>(null),[query,setQuery]=useState(''),[family,setFamily]=useState('全部蝶类'),[page,setPage]=useState(1),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[price,setPrice]=useState('0.15777'),[wallet,setWallet]=useState<Address>(),[live,setLive]=useState(false),[chainError,setChainError]=useState(config.reason),[loading,setLoading]=useState(false),[hash,setHash]=useState<Hash>();
 const [quantity,setQuantity]=useState('1'),[draft,setDraft]=useState(loadReferralDraft);
 const epoch=useRef(0),refreshSequence=useRef(0);
 const dialog=useRef<HTMLDialogElement>(null),lock=useRef(false),walletRef=useRef(wallet);
 walletRef.current=wallet;
 useEffect(()=>{document.title='蝴蝶股票 NFT · BUTTERFLY 7777';const c=new AbortController();fetch('/nft/catalog.json',{signal:c.signal}).then(r=>{if(!r.ok)throw Error('作品加载失败，请刷新重试');return r.json()}).then(setCatalog).catch(e=>{if(e.name!=='AbortError')setError(reason(e))});return()=>c.abort()},[]);
 const refresh=useCallback(async()=>{if(!config.enabled)return;const sequence=++refreshSequence.current,session=epoch.current,account=walletRef.current;setLoading(true);const current=()=>session===epoch.current&&sequence===refreshSequence.current&&account===walletRef.current;try{const next=await readState(account);if(current()){setState(next);setLive(true);setChainError('')}}catch(e){if(current()){setLive(false);setState(emptyState);setChainError(reason(e))}}finally{if(current())setLoading(false)}},[]);
 useEffect(()=>{setState(emptyState);setLive(false);void refresh();const timer=setInterval(()=>void refresh(),15000);return()=>clearInterval(timer)},[wallet,refresh]);
 useEffect(()=>{const p=walletProvider() as ReturnType<typeof walletProvider>&{on?:(event:string,fn:()=>void)=>void;removeListener?:(event:string,fn:()=>void)=>void};const reset=()=>{epoch.current++;walletRef.current=undefined;setWallet(undefined);setState(emptyState);setLive(false);setHash(undefined);setModal(m=>m?.kind==='reveal'?null:m);setNotice('钱包或网络已变化，请重新连接')};p?.on?.('accountsChanged',reset);p?.on?.('chainChanged',reset);return()=>{p?.removeListener?.('accountsChanged',reset);p?.removeListener?.('chainChanged',reset)}},[]);
 useEffect(()=>{if(modal)dialog.current?.showModal();else dialog.current?.close()},[modal]);
 useEffect(()=>{setPage(1)},[query,family,view]);
 useEffect(()=>{if(!catalog.length)return;const id=Number(new URLSearchParams(location.search).get('token'));if(Number.isInteger(id)&&id>0&&id<=NFT_SUPPLY)setModal({kind:'detail',id})},[catalog.length]);
 const byId=useMemo(()=>new Map(catalog.map(x=>[x.id,x])),[catalog]);
 const mine=(seller:string)=>!!wallet&&seller.toLowerCase()===wallet.toLowerCase();
 const filtered=useMemo(()=>catalog.filter(x=>(view==='collection'?state.owned.includes(x.id):view==='market'?state.listings.some(l=>l.id===x.id&&l.active):true)&&(family==='全部蝶类'||x.family===family)&&(!query||String(x.id)===query.replace(/^#/,'')||x.name.includes(query)||x.palette.toLowerCase().includes(query.toLowerCase()))),[catalog,view,state,query,family]);
 useEffect(()=>setPage(p=>Math.min(p,Math.max(1,Math.ceil(filtered.length/24)))),[filtered.length]);
 function changeView(next:View){setView(next);setQuery('');document.getElementById('nft-gallery')?.scrollIntoView({behavior:'smooth'})}
 async function connectWallet(){try{const a=await connect();epoch.current++;walletRef.current=a;setWallet(a);setModal(m=>m?.kind==='wallet'?null:m);setNotice('钱包已连接，持仓以 BNB Chain 链上记录为准');await refresh()}catch(e){setNotice(reason(e))}}
 async function run(action:Parameters<typeof transact>[0],args:Parameters<typeof transact>[2]){
  if(lock.current)return;if(!wallet){setModal({kind:'wallet'});return}if(!live){setNotice(chainError||'主网服务尚未就绪');return}
  const session=epoch.current,account=wallet,claimIds=action==='claim'?state.pending.find(r=>r.requestId===args.requestId)?.tokenIds:undefined;
  lock.current=true;setBusy(true);setHash(undefined);setNotice('请在钱包核对操作并确认。');
  try{await transact(action,account,args,h=>{if(session!==epoch.current)return;setHash(h);setNotice('交易已发送，等待链上确认。')});if(session!==epoch.current)return;setNotice(action==='mint'?'申请已确认，等待随机编号。分配后请点击领取。':action==='approve'?'单张 NFT 授权已确认，请再次点击发布挂单。':'交易已确认，正在更新持仓。');if(action==='claim'&&claimIds?.length)setModal({kind:'reveal',ids:claimIds});else if(action!=='approve')setModal(null);await refresh()}catch(e){if(session===epoch.current)setNotice(reason(e))}finally{lock.current=false;setBusy(false)}
 }
 const selected=modal&&'id'in modal?byId.get(modal.id):modal?.kind==='buy'?byId.get(modal.listing.id):undefined;
 let listingPrice=0n;try{listingPrice=parseBNB(price)}catch{/* form disabled */}
 const families=[...new Set(catalog.map(x=>x.family))];
 const pending=(r:PendingMint)=><div className="nft-pending-item" key={r.requestId.toString()}><div><strong>{r.tokenIds.length?`${r.quantity} 张已分配`:`${r.quantity} 张正在等待随机编号`}</strong><p className="nft-assigned-ids">{r.tokenIds.map(id=>`#${pad(id)}`).join(' · ')}</p><small>申请 #{r.requestId.toString().slice(0,14)}…</small></div><button className="nft-btn secondary" disabled={busy||r.tokenIds.length!==r.quantity||!live} onClick={()=>run('claim',{requestId:r.requestId})}>{r.tokenIds.length===r.quantity?'整批领取到钱包 ↗':'等待随机数'}</button></div>;
 return <div className="nft-app">
  <div className="nft-preview-bar"><span><i/>{live?'BNB CHAIN · 链上连接已核验':'NATURE EDITION · 自然典藏'}</span><span>{live?'铸造 0.01 BNB · 市场零手续费':'尚未开放付款 · 主网部署准备中'} <button onClick={()=>setModal({kind:'rules'})}>收藏规则 ↗</button></span></div>
  <header className="nft-header"><a className="nft-brand" href="/?view=nft"><Mark/><span>BUTTERFLY <b>7777</b><small>蝴蝶股票 · 自然典藏</small></span></a><nav aria-label="NFT 导航">{([['discover','探索典藏'],['market','交易市场'],['collection','我的蝴蝶']] as const).map(([key,label])=><button key={key} className={view===key?'active':''} onClick={()=>changeView(key)}>{label}</button>)}</nav><button className="nft-wallet" onClick={()=>setModal({kind:'wallet'})}><span className="nft-network-dot"/>{wallet?short(wallet):'连接钱包'} ↗</button></header>
  <main><section className="nft-hero"><div className="nft-hero-copy"><div className="nft-eyebrow"><span/> INSPIRED BY NATURE · MADE TO BE YOURS</div><h1>把自然的色彩，<br/>收藏在<span>你的钱包。</span></h1><p>蓝闪蝶的光，凤蝶的翅，帝王蝶的纹。<br/>12 个自然灵感系列，7,777 次独一无二的相遇。</p><div className="nft-hero-actions"><button className="nft-btn primary" onClick={()=>setModal({kind:'mint'})}>随机批量铸造 ↗</button><button className="nft-text-button" onClick={()=>changeView('market')}>探索交易市场 →</button></div><div className="nft-hero-facts"><div><strong>7,777</strong><span>固定总量 · 独立图案</span></div><div><strong>0.01 <small>BNB</small></strong><span>每张铸造价格</span></div><div><strong>0%</strong><span>市场手续费</span></div></div></div><div className="nft-hero-art"><div className="nft-orbit orbit-one"/><div className="nft-orbit orbit-two"/><span className="nft-art-coordinate">NATURE / ARCHIVE 001</span><div className="nft-hero-card side left"><img src="/nft/art/77.jpg" alt="蝴蝶典藏 77"/><span>EDITION #0077</span></div><button className="nft-hero-card center" onClick={()=>setModal({kind:'detail',id:7777})}><div className="nft-card-top"><span>NATURE COLLECTION</span><Mark/></div><img src="/nft/art/7777.jpg" alt="蝴蝶典藏 7777"/><div className="nft-hero-card-bottom"><span>{byId.get(7777)?.family||'自然典藏'}<small>ORIGINAL GENERATIVE ART</small></span><b>#7777</b></div></button><div className="nft-hero-card side right"><img src="/nft/art/1314.jpg" alt="蝴蝶典藏 1314"/><span>EDITION #1314</span></div><div className="nft-floating-tag">✦ 自然有万千色彩，你有独特的一只。</div></div></section>
  <div className="nft-ticker"><span>✦ NATURE INSPIRED</span><span>7777 UNIQUE BUTTERFLIES</span><span>✦ 市场零手续费</span><span>100% TO THE SELLER</span><span>✦ 钱包直接持有</span></div>
  {chainError&&<div className="nft-chain-banner" role="status"><strong>链上状态</strong><span>{chainError}</span></div>}
  {state.pending.length>0&&<section className="nft-pending"><h2>等待领取的蝴蝶</h2><p>申请和编号保存在链上，关闭页面后仍可回来领取。</p>{state.pending.map(pending)}</section>}
  <ReferralPanel wallet={wallet} referral={state.referral} live={live} busy={busy} onWithdraw={()=>void run('withdraw',{})}/>
  <section id="nft-gallery" className="nft-gallery"><div className="nft-section-heading"><div className="nft-eyebrow">THE NATURE COLLECTION / 001</div><div className="nft-heading-row"><h2>{view==='discover'?'在自然的万千色彩中，找到你的蝴蝶。':view==='market'?'让收藏，遇见新的主人。':'属于你的，独一无二。'}</h2><button className="nft-text-button" onClick={()=>void refresh()} disabled={loading||!config.enabled}>{loading?'读取链上数据…':'刷新链上数据 ↻'}</button></div></div>
  <div className="nft-tabs">{([['discover','全部典藏',7777],['market','交易市场',state.listings.filter(x=>x.active).length],['collection','我的收藏',state.owned.length]] as const).map(([key,label,count])=><button key={key} className={view===key?'active':''} onClick={()=>changeView(key)}>{label}<span>{count}</span></button>)}</div>
  <div className="nft-toolbar"><label className="nft-search"><span>⌕</span><input aria-label="搜索名称或编号" placeholder="搜索蝶类、名称或编号，如 #7777" value={query} onChange={e=>setQuery(e.target.value.trim())}/></label><select aria-label="筛选蝶类" value={family} onChange={e=>setFamily(e.target.value)}>{['全部蝶类',...families].map(f=><option key={f}>{f}</option>)}</select><button className="nft-text-button" onClick={()=>setModal({kind:'history'})}>交易记录 ↗</button></div>
  <div className="nft-results-note"><span>{error||(!catalog.length?'作品载入中…':`共 ${filtered.length.toLocaleString()} 张作品`)}</span><span>{view==='market'?'真实有效挂单 · 卖家收到全部售价':view==='collection'?'仅显示当前钱包的链上持仓':'自然灵感艺术创作 · 非生物标本'}</span></div>
  <div className="nft-grid">{filtered.slice((page-1)*24,page*24).map(nft=>{const l=state.listings.find(x=>x.id===nft.id);const owned=state.owned.includes(nft.id);return <article className="nft-item" key={nft.id}><button className="nft-item-image" onClick={()=>setModal({kind:'detail',id:nft.id})} aria-label={`查看 ${nft.name}`}><img src={nft.image} alt={nft.name} loading="lazy"/><span className="nft-edition">#{pad(nft.id)}</span><span className="nft-view-art">查看作品 ↗</span></button><div className="nft-item-info"><div><h3>{nft.family}</h3><span>{nft.palette}</span></div><span className="nft-color" style={{background:nft.color}}/></div><div className="nft-item-bottom"><div><small>{l?.active?'挂单价格':owned?'链上持有':'典藏编号'}</small><strong>{l?.active?`${formatBNB(l.price)} BNB`:`#${pad(nft.id)}`}</strong></div>{l&&mine(l.seller)?<button disabled={busy} onClick={()=>run('cancel',{id:nft.id})}>{l.active?'撤单':'清除失效挂单'} ↗</button>:l?.active?<button onClick={()=>setModal({kind:'buy',listing:l})}>购买 ↗</button>:owned?<button onClick={()=>setModal({kind:'list',id:nft.id})}>挂单 ↗</button>:<button onClick={()=>setModal({kind:'detail',id:nft.id})}>详情 ↗</button>}</div></article>})}</div>
  {!error&&catalog.length>0&&!filtered.length&&<div className="nft-empty"><Mark/><h3>{!live?'主网市场尚未开放':view==='collection'?'你的第一只蝴蝶，正在等待相遇。':'暂时没有匹配的作品'}</h3><p>{!wallet&&view==='collection'?'连接钱包后查看实际持仓。':view==='market'?'这里仅展示链上挂单，没有演示订单。':'试试其他蝶类或编号。'}</p><button className="nft-btn secondary" onClick={()=>{setQuery('');setFamily('全部蝶类');if(view==='collection'&&!wallet)setModal({kind:'wallet'})}}> {view==='collection'&&!wallet?'连接钱包':'清空筛选'} ↗</button></div>}
  {filtered.length>24&&<div className="nft-pagination"><span>第 {page} / {Math.ceil(filtered.length/24)} 页</span><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>← 上一页</button><button disabled={page*24>=filtered.length} onClick={()=>setPage(p=>p+1)}>下一页 →</button></div>}</section>
  <section className="nft-how"><div><div className="nft-eyebrow">YOURS. FROM WING TO WALLET.</div><h2>自然的浪漫，<br/>自由地收藏。</h2><button className="nft-text-button" onClick={()=>setModal({kind:'rules'})}>查看全部规则 ↗</button></div><ol><li><span>01</span><h3>随机相遇</h3><p>每张 0.01 BNB，一次申请 1–20 张，等待随机编号后整批领取；申请和领取的 Gas 分别另计。</p></li><li><span>02</span><h3>自己保管</h3><p>NFT 是标准 ERC-721 资产。挂单时仍在你的钱包，成交后才转给买家。</p></li><li><span>03</span><h3>全部归卖家</h3><p>挂价 0.15777 BNB，成交时卖家就收到 0.15777 BNB。平台手续费为零，网络 Gas 另计。</p></li></ol></section>
  <section className="nft-atelier"><img src="/nft/art/7777.jpg" loading="lazy" alt="蝴蝶典藏实际作品 #7777"/><div><div className="nft-eyebrow">INSPIRED BY THE NATURAL WORLD</div><h2>从真实的蝴蝶，<br/>到独特的艺术。</h2><p>蓝、橙、翡翠绿、玫瑰红。从 12 种自然蝴蝶的翅形和纹理中寻找灵感，以原创算法生成 7,777 幅独立作品。</p><span className="nft-muted">左图为实际 NFT 作品 #7777，与画廊和元数据一致。</span><a href="/nft/manifest.json" target="_blank" rel="noreferrer">查看作品校验清单 ↗</a></div></section></main>
  <footer className="nft-footer"><a className="nft-brand" href="/?view=nft"><Mark/><span>BUTTERFLY <b>7777</b></span></a><p>每一只蝴蝶，都值得被看见。<small>{live?'BNB Chain · ERC-721 · 零市场手续费':'主网尚未开放付款'}</small></p><div><button onClick={()=>setModal({kind:'rules'})}>收藏规则</button><a href="https://app.gupiao.sh/" target="_blank" rel="noreferrer">蝴蝶 Swap ↗</a></div></footer>
  <dialog ref={dialog} className="nft-dialog" aria-label="NFT 操作" onCancel={e=>{if(busy)e.preventDefault();else setModal(null)}} onClick={e=>{if(e.target===dialog.current&&!busy)setModal(null)}}><div className="nft-dialog-inner"><button className="nft-close" aria-label="关闭弹窗" disabled={busy} onClick={()=>setModal(null)}>×</button>
  {modal?.kind==='mint'&&<MintForm quantity={quantity} setQuantity={setQuantity} draft={draft} setDraft={setDraft} wallet={wallet} referral={state.referral} collection={config.collection} live={live} busy={busy} reserved={state.reserved} onConnect={()=>void connectWallet()} onMint={(quantity,referrer)=>void run('mint',{quantity,referrer})}/>}
  {modal?.kind==='reveal'&&<><div className="nft-eyebrow">CONFIRMED ON CHAIN</div><h2>你的蝴蝶，已抵达。</h2><p>整批领取交易已确认 · {modal.ids.length} 张</p><div className="nft-reveal">{modal.ids.map(id=><figure key={id}><img src={`/nft/art/${id}.jpg`} alt={`已领取蝴蝶 #${pad(id)}`}/><figcaption>#{pad(id)}</figcaption></figure>)}</div></>}
  {modal?.kind==='detail'&&selected&&<><div className="nft-eyebrow">NATURE / #{pad(selected.id)}</div><h2>{selected.family}</h2><img className="nft-detail-art" src={selected.image} alt={selected.name}/><div className="nft-traits">{[['自然灵感',selected.palette],['翅形',selected.wing],['纹理',selected.pattern],['编号',`#${pad(selected.id)}`]].map(([k,v])=><div key={k}><small>{k}</small><strong>{v}</strong></div>)}</div><div className="nft-downloads"><a href={selected.image} download={`butterfly-${selected.id}.jpg`}>下载作品 ↓</a><a href={`/nft/metadata/${selected.id}.json`} target="_blank" rel="noreferrer">查看元数据 ↗</a></div><p className="nft-dialog-copy">市场手续费 0% · 每张铸造 0.01 BNB · 可批量申请 1–20 张，整批领取，领取交易 Gas 另计。</p><p className="nft-dna">ART SHA-256<br/>{selected.dna}</p>{state.owned.includes(selected.id)?<button className="nft-btn primary full" onClick={()=>setModal({kind:'list',id:selected.id})}>挂单出售 ↗</button>:<button className="nft-btn primary full" onClick={()=>setModal({kind:'mint'})}>随机铸造 · 不指定编号 ↗</button>}</>}
  {modal?.kind==='list'&&selected&&<><div className="nft-eyebrow">LIST YOUR BUTTERFLY</div><h2>给收藏，一个新旅程。</h2><div className="nft-order-art"><img src={selected.image} alt={selected.name}/><div><h3>{selected.name}</h3><span>NFT 挂单期间仍在你的钱包</span></div></div><label className="nft-price-label">挂单价格（BNB）<input aria-label="挂单价格" inputMode="decimal" value={price} onChange={e=>setPrice(e.target.value)}/></label><div className="nft-receipt"><div><span>买家支付</span><strong>{formatBNB(listingPrice)} BNB</strong></div><div><span>平台手续费</span><strong>0 BNB · 0%</strong></div><div><span>你将收到</span><strong className="nft-lime">{formatBNB(listingPrice)} BNB · 100%</strong></div></div><button className="nft-btn secondary full" disabled={!live||busy} onClick={()=>run('approve',{id:selected.id})}>第一步：仅授权这张 NFT</button><button className="nft-btn primary full" disabled={!live||busy||listingPrice<=0n} onClick={()=>run('list',{id:selected.id,price:listingPrice})}>第二步：发布链上挂单 ↗</button></>}
  {modal?.kind==='buy'&&selected&&<><div className="nft-eyebrow">COLLECT SOMETHING UNIQUE</div><h2>确认收藏这只蝴蝶。</h2><div className="nft-order-art"><img src={selected.image} alt={selected.name}/><div><h3>{selected.name}</h3><span>卖家 {short(modal.listing.seller)}</span></div></div><div className="nft-receipt"><div><span>支付 / 卖家收到</span><strong>{formatBNB(modal.listing.price)} BNB</strong></div><div><span>平台手续费</span><strong>0 BNB</strong></div></div><p className="nft-dialog-copy">成交时 NFT 进入你的钱包，全额 BNB 进入卖家钱包。网络 Gas 由钱包另行显示。</p><button className="nft-btn primary full" disabled={!live||busy||mine(modal.listing.seller)} onClick={()=>run('buy',{id:selected.id,price:modal.listing.price,seller:modal.listing.seller,version:modal.listing.version})}>确认支付 {formatBNB(modal.listing.price)} BNB ↗</button></>}
  {modal?.kind==='rules'&&<><div className="nft-eyebrow">COLLECTION DETAILS</div><h2>规则透明，收藏自在。</h2><div className="nft-rule-list"><h3>01 / 固定总量与随机</h3><p>7,777 张，编号 1–7777。付费申请通过 Chainlink VRF 分配未使用编号；分配后领取 NFT。不会由浏览器随机决定付费结果。等待期间请保留申请，不要重复支付。</p><h3>02 / 铸造款</h3><p>每张 0.01 BNB，每批 1–20 张。整批领取成功时，20% 记入唯一邀请人的可提现奖励，80% 转至下方收款地址。首次成功绑定后邀请人不可更改；无默认邀请人，只有一代奖励，二级市场不分成。申请和领取的网络 Gas 另计。随机数服务异常会延迟分配；当前合约没有退款功能。</p><h3>03 / 零手续费交易</h3><p>卖家自行定价，买家支付全部售价，卖家收到全部售价。平台抽成为 0%，不设置 NFT 版税。交易失败会整体回滚，网络 Gas 不退。</p><h3>04 / TokenPocket</h3><p>使用 BNB Chain 的 ERC-721 标准。可在 TP 钱包 NFT 页面通过合约地址添加。图片采用 JPEG，tokenURI 提供 JSON 元数据；钱包索引和图片展示以 TP 实际支持为准。</p><h3>05 / 当前状态</h3><p>{live?'已连接并核验主网合约。所有资产和挂单均来自链上。':chainError}</p></div><div className="nft-treasury"><small>仅铸造收款地址</small><code>{TREASURY}</code>{live&&<><small>NFT 合约</small><code>{config.collection}</code><a href={`https://bscscan.com/address/${config.collection}`} target="_blank" rel="noreferrer">查看链上合约 ↗</a></>}</div></>}
  {modal?.kind==='history'&&<><h2>链上记录，随时可查。</h2><p className="nft-dialog-copy">持仓、申请和挂单从链上读取。本站不生成模拟成交记录。</p>{hash&&<a href={`https://bscscan.com/tx/${hash}`} target="_blank" rel="noreferrer">查看本次交易 ↗</a>}{wallet?<a className="nft-btn secondary full" href={`https://bscscan.com/address/${wallet}`} target="_blank" rel="noreferrer">在 BscScan 查看钱包交易 ↗</a>:<button className="nft-btn primary full" onClick={()=>setModal({kind:'wallet'})}>连接钱包</button>}</>}
  {modal?.kind==='wallet'&&<><div className="nft-eyebrow">WELCOME TO BUTTERFLY</div><h2>让蝴蝶，住进你的钱包。</h2><p className="nft-dialog-copy">支持 TokenPocket 内置浏览器和兼容的浏览器钱包。连接只读取公开地址；付款和 NFT 授权需要你在钱包逐笔确认。</p>{wallet&&<div className="nft-treasury"><code>{wallet}</code></div>}<button className="nft-btn primary full" onClick={connectWallet}>{wallet?'重新连接':'连接钱包'} ↗</button>{wallet&&<button className="nft-text-button full" onClick={()=>{epoch.current++;walletRef.current=undefined;setWallet(undefined);setModal(null)}}>断开本站连接</button>}</>}
  {modal&&(busy||notice)&&<p role="status" className="nft-disclaimer">{notice||'操作进行中，请在钱包完成确认。'}{hash&&<a href={`https://bscscan.com/tx/${hash}`} target="_blank" rel="noreferrer">查看交易 ↗</a>}</p>}
  </div></dialog>{notice&&!modal&&<div role="status" className="nft-toast"><span>✦</span>{notice}{hash&&<a href={`https://bscscan.com/tx/${hash}`} target="_blank" rel="noreferrer">交易 ↗</a>}<button aria-label="关闭提示" onClick={()=>setNotice('')}>×</button></div>}
 </div>;
}

