import {useState,useEffect,useRef,useMemo} from 'react';
import {NFT,Ledger,Listing,TREASURY,MINT_WEI,NFT_SUPPLY,STORAGE_KEY,initialLedger,loadLedger,drawRandom,mint,list,cancel,buy,parseBNB,formatBNB,splitFee} from './model';
import './nft.css';
type View='discover'|'market'|'collection';
type Modal={kind:'mint'}|{kind:'reveal';id:number}|{kind:'detail';id:number}|{kind:'list';id:number}|{kind:'buy';listing:Listing}|{kind:'rules'}|{kind:'history'}|{kind:'wallet'}|{kind:'reset'};
const pad=(id:number)=>String(id).padStart(4,'0');
const shorten=(a:string)=>`${a.slice(0,6)}…${a.slice(-4)}`;
function ButterflyMark(){return <svg viewBox="0 0 40 40" fill="currentColor" aria-hidden="true"><path d="M19 20C5 20 0 3 7 4c8 0 10 9 13 13C23 11 27 2 34 4c7 4-1 15-13 16 9 1 15 8 11 12-5 5-11-4-12-10-1 6-8 15-12 10-5-5 2-11 11-12Z"/></svg>}
export default function NFTPage(){
 const [catalog,setCatalog]=useState<NFT[]>([]),[error,setError]=useState(''),[view,setView]=useState<View>('discover'),[ledger,setLedger]=useState<Ledger>(loadLedger);
 const [modal,setModal]=useState<Modal|null>(null),[query,setQuery]=useState(''),[rarity,setRarity]=useState('全部稀有度'),[sort,setSort]=useState('edition'),[page,setPage]=useState(1),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[price,setPrice]=useState('0.02'),[wallet,setWallet]=useState('');
 const dialog=useRef<HTMLDialogElement>(null),mintLock=useRef(false),timer=useRef<ReturnType<typeof setTimeout>|null>(null),ledgerRef=useRef(ledger);
 useEffect(()=>{document.title='BUTTERFLY 7777 · 蝴蝶 NFT 典藏';const c=new AbortController();fetch('/nft/catalog.json',{signal:c.signal}).then(r=>{if(!r.ok)throw Error('作品加载失败，请刷新重试');return r.json();}).then(setCatalog).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return ()=>{c.abort();if(timer.current)clearTimeout(timer.current)};},[]);
 useEffect(()=>{ledgerRef.current=ledger;try{localStorage.setItem(STORAGE_KEY,JSON.stringify(ledger))}catch{setNotice('浏览器未允许保存，体验记录将在关闭页面后丢失')}} ,[ledger]);
 useEffect(()=>{if(modal){dialog.current?.showModal();}else{dialog.current?.close();}},[modal]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),6000);return()=>clearTimeout(t)},[notice]);
 useEffect(()=>{setPage(1)},[query,rarity,view,sort]);
 useEffect(()=>{if(!catalog.length)return;const id=Number(new URLSearchParams(location.search).get('token'));if(Number.isInteger(id)&&id>0&&id<=NFT_SUPPLY)setModal({kind:'detail',id});},[catalog.length]);
 const byId=useMemo(()=>new Map(catalog.map(x=>[x.id,x])),[catalog]);
 const filtered=useMemo(()=>{let items=catalog.filter(x=>view==='collection'?ledger.owned.includes(x.id):view==='market'?ledger.listings.some(l=>l.id===x.id):true);const q=query.trim().toLowerCase().replace(/^#/,'');if(q)items=items.filter(x=>String(x.id)===q||x.name.toLowerCase().includes(q)||x.family.includes(q));if(rarity!=='全部稀有度')items=items.filter(x=>x.rarity===rarity);if(sort==='rarity'){const order=['传说','史诗','稀有','典藏'];items.sort((a,b)=>order.indexOf(a.rarity)-order.indexOf(b.rarity)||a.id-b.id);}else if(sort==='price'){items.sort((a,b)=>{const ap=BigInt(ledger.listings.find(l=>l.id===a.id)?.price||'0'),bp=BigInt(ledger.listings.find(l=>l.id===b.id)?.price||'0');return ap<bp?-1:ap>bp?1:a.id-b.id});}return items;},[catalog,view,ledger,query,rarity,sort]);
 const notify=(text:string)=>setNotice(text);
 function commit(next:Ledger){ledgerRef.current=next;setLedger(next);}
 function transact(fn:(s:Ledger)=>Ledger,message:string){try{commit(fn(ledgerRef.current));setModal(null);notify(message)}catch(e){notify((e as Error).message)}}
 function reveal(){if(mintLock.current)return;mintLock.current=true;setBusy(true);try{const id=drawRandom(ledgerRef.current);timer.current=setTimeout(()=>{try{commit(mint(ledgerRef.current,id));setModal({kind:'reveal',id});}catch(e){notify((e as Error).message)}finally{setBusy(false);mintLock.current=false}},1500);}catch(e){notify((e as Error).message);setBusy(false);mintLock.current=false}}
 async function connectWallet(){try{const provider=(window as unknown as {ethereum?:{request:(args:{method:string})=>Promise<string[]>}}).ethereum;if(!provider){notify('请在钱包内置浏览器中打开，或使用本页的免钱包体验');return;}const accounts=await provider.request({method:'eth_requestAccounts'});if(!accounts[0])throw Error('没有可用的钱包地址');setWallet(accounts[0]);setModal(null);notify('地址已连接。本预览仍为模拟体验，不会请求签名或转账。');}catch{notify('未连接钱包，仍可继续免钱包体验')}}
 function changeView(next:View){setView(next);setQuery('');setRarity('全部稀有度');setPage(1);document.getElementById('nft-gallery')?.scrollIntoView({behavior:'smooth',block:'start'});}
 const selected=modal&&'id'in modal?byId.get(modal.id):modal?.kind==='buy'?byId.get(modal.listing.id):undefined;
 let listingPrice=0n;try{listingPrice=parseBNB(price)}catch{/* invalid form remains disabled */}
 const fee=splitFee(listingPrice);
 const rarityCounts=useMemo(()=>catalog.reduce((a,x)=>({...a,[x.rarity]:(a[x.rarity]||0)+1}),{} as Record<string,number>),[catalog]);
 const remaining=NFT_SUPPLY-ledger.minted.length-8;
 return <div className="nft-app">
  <div className="nft-preview-bar"><span><i/> VERCEL PREVIEW · 独立体验版</span><span>模拟铸造与交易，不收取真实 BNB <button onClick={()=>setModal({kind:'rules'})}>了解规则 ↗</button></span></div>
  <header className="nft-header"><a className="nft-brand" href="/?view=nft"><ButterflyMark/><span>BUTTERFLY <b>7777</b><small>蝴蝶股票 · NFT 典藏</small></span></a><nav aria-label="NFT 导航">{([['discover','探索典藏'],['market','交易市场'],['collection','我的蝴蝶']] as const).map(([key,label])=><button key={key} className={view===key?'active':''} onClick={()=>changeView(key)}>{label}{key==='collection'&&ledger.owned.length>0&&<sup>{ledger.owned.length}</sup>}</button>)}</nav><button className="nft-wallet" onClick={()=>setModal({kind:'wallet'})}><span className="nft-network-dot"/>{wallet?shorten(wallet):'连接钱包'}<span>↗</span></button></header>
  <main>
   <section className="nft-hero"><div className="nft-hero-copy"><div className="nft-eyebrow"><span/> GENERATIVE ART · BNB CHAIN</div><h1>每一次振翅，<br/>都是<span>独一无二。</span></h1><p>7,777 只蝴蝶，7,777 个平行宇宙。<br/>开启一份未知的色彩，让属于你的那一只落入收藏。</p><div className="nft-hero-actions"><button className="nft-btn primary" onClick={()=>setModal({kind:'mint'})} disabled={!catalog.length}>随机开启一只 <span>↗</span></button><button className="nft-text-button" onClick={()=>changeView('market')}>探索交易市场 <span>→</span></button></div><div className="nft-hero-facts"><div><strong>7,777</strong><span>独立作品 · 固定总量</span></div><div><strong>0.01 <small>BNB</small></strong><span>正式铸造单价</span></div><div><strong>1 / 1</strong><span>每个编号，仅此一张</span></div></div></div>
    <div className="nft-hero-art"><div className="nft-orbit orbit-one"/><div className="nft-orbit orbit-two"/><span className="nft-art-coordinate">BTF / ARCHIVE 001</span><div className="nft-hero-card side left"><img src="/nft/art/77.svg" alt="蝴蝶典藏第 77 号"/><span>EDITION #0077</span></div><button className="nft-hero-card center" onClick={()=>setModal({kind:'detail',id:7777})}><div className="nft-card-top"><span>GENESIS COLLECTION</span><ButterflyMark/></div><img src="/nft/art/7777.svg" alt="蝴蝶典藏第 7777 号"/><div className="nft-hero-card-bottom"><span>{byId.get(7777)?.family||'蝴蝶典藏'}<small>ORIGINAL GENERATIVE ART</small></span><b>#7777</b></div></button><div className="nft-hero-card side right"><img src="/nft/art/1314.svg" alt="蝴蝶典藏第 1314 号"/><span>EDITION #1314</span></div><div className="nft-floating-tag"><span>✦</span> 未知的编号，唯一的你。</div></div>
   </section>
   <div className="nft-ticker" aria-label="收藏特色"><span>✦ 随机邂逅</span><span>7777 UNIQUE BUTTERFLIES</span><span>✦ 独立图案</span><span>ORIGINAL GENERATIVE ART</span><span>✦ 自由收藏</span><span>EVERY WING TELLS A STORY</span></div>
   <section id="nft-gallery" className="nft-gallery"><div className="nft-section-heading"><div className="nft-eyebrow">THE COLLECTION / 001</div><div className="nft-heading-row"><h2>{view==='discover'?'在万千色彩中，找到你的蝴蝶。':view==='market'?'让收藏，遇见新的主人。':'属于你的，独一无二。'}</h2><button className="nft-text-button" onClick={()=>setModal({kind:'history'})}>体验记录 ↗</button></div></div>
    <div className="nft-tabs">{([['discover','全部典藏',7777],['market','交易市场',ledger.listings.length],['collection','我的收藏',ledger.owned.length]] as const).map(([key,label,count])=><button className={view===key?'active':''} key={key} onClick={()=>changeView(key)}>{label}<span>{count.toLocaleString()}</span></button>)}</div>
    <div className="nft-toolbar"><label className="nft-search"><span>⌕</span><input aria-label="搜索名称或编号" placeholder="搜索蝴蝶名称或编号，如 #7777" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="清空搜索" onClick={()=>setQuery('')}>×</button>}</label><select aria-label="筛选稀有度" value={rarity} onChange={e=>setRarity(e.target.value)}>{['全部稀有度','典藏','稀有','史诗','传说'].map(v=><option key={v}>{v}</option>)}</select><select aria-label="排序" value={sort} onChange={e=>setSort(e.target.value)}><option value="edition">编号顺序</option><option value="rarity">稀有度优先</option>{view==='market'&&<option value="price">价格从低到高</option>}</select></div>
    <div className="nft-results-note"><span>{error||(!catalog.length?'作品载入中…':`共 ${filtered.length.toLocaleString()} 张作品`)}</span><span>{view==='market'?'体验挂单 · 所有价格与成交均为模拟':view==='collection'?'仅保存在当前浏览器，不代表链上持仓':'全部原创图案 · 编号不代表稀有度'}</span></div>
    <div className="nft-grid">{filtered.slice((page-1)*24,page*24).map(nft=>{const listing=ledger.listings.find(x=>x.id===nft.id);return <article className="nft-item" key={nft.id}><button className="nft-item-image" onClick={()=>setModal({kind:'detail',id:nft.id})} aria-label={`查看 ${nft.name}`}><img loading="lazy" src={nft.image} alt={nft.name}/><span className={`nft-rarity rarity-${nft.rarity}`}>✦ {nft.rarity}</span><span className="nft-edition">#{pad(nft.id)}</span><span className="nft-view-art">查看作品 ↗</span></button><div className="nft-item-info"><div><h3>{nft.family}</h3><span>{nft.wing} · {nft.pattern}</span></div><span className="nft-color" style={{background:nft.color}}/></div><div className="nft-item-bottom"><div><small>{listing?'体验挂单价':ledger.owned.includes(nft.id)?'收藏状态':'典藏编号'}</small><strong>{listing?`${formatBNB(listing.price)} BNB`:ledger.owned.includes(nft.id)?'已收藏':`#${pad(nft.id)}`}</strong></div>{listing?<button onClick={()=>listing.seller==='you'?transact(s=>cancel(s,nft.id),'已撤销体验挂单'):setModal({kind:'buy',listing})}>{listing.seller==='you'?'撤单':'购买'} ↗</button>:ledger.owned.includes(nft.id)?<button onClick={()=>{setPrice('0.02');setModal({kind:'list',id:nft.id})}}>挂单 ↗</button>:<button onClick={()=>setModal({kind:'detail',id:nft.id})}>详情 ↗</button>}</div></article>})}</div>
    {!error&&catalog.length>0&&!filtered.length&&<div className="nft-empty"><ButterflyMark/><h3>{view==='collection'?'你的第一只蝴蝶，正在等待相遇。':'暂时没有匹配的作品'}</h3><p>{view==='collection'?'随机开启一只，或者从体验市场收藏喜欢的作品。':'试试其他名称、编号或稀有度。'}</p><button className="nft-btn primary" onClick={()=>view==='collection'?setModal({kind:'mint'}):(setQuery(''),setRarity('全部稀有度'))}>{view==='collection'?'开启我的第一只':'清空筛选'} ↗</button></div>}
    {filtered.length>24&&<div className="nft-pagination"><span>第 {page} / {Math.ceil(filtered.length/24)} 页</span><button disabled={page===1} onClick={()=>{setPage(p=>p-1);document.getElementById('nft-gallery')?.scrollIntoView({behavior:'smooth'})}}>← 上一页</button><button disabled={page*24>=filtered.length} onClick={()=>{setPage(p=>p+1);document.getElementById('nft-gallery')?.scrollIntoView({behavior:'smooth'})}}>下一页 →</button></div>}
   </section>
   <section className="nft-how"><div><div className="nft-eyebrow">A LITTLE MAGIC. ALL YOURS.</div><h2>收藏很简单，<br/>惊喜留给下一秒。</h2><button className="nft-text-button" onClick={()=>setModal({kind:'rules'})}>查看全部规则 ↗</button></div><ol><li><span>01</span><h3>开启未知</h3><p>正式铸造价 0.01 BNB，随机分配一个未被领取的编号。</p></li><li><span>02</span><h3>遇见唯一</h3><p>不同翅形、色彩、纹理与光环，构成 7,777 张独立蝴蝶作品。</p></li><li><span>03</span><h3>自由流转</h3><p>自由定价挂单。市场成交款 93% 给卖家，7% 作为平台服务费。</p></li></ol></section>
   <section className="nft-atelier"><img src="/nft-assets/atelier-concept.webp" loading="lazy" alt="蝴蝶艺术工作室原创翡翠概念图"/><div><div className="nft-eyebrow">FROM THE BUTTERFLY ATELIER</div><h2>把蝴蝶的浪漫，<br/>写进数字世界。</h2><p>从一束光、一条翅脉开始，我们以生成艺术探索蝴蝶的无数种可能。这里的每一张作品，都有自己的色彩和纹理。</p><span className="nft-muted">左图为原创视觉概念；实际典藏作品以画廊中的 SVG 为准。</span><a href="/nft/manifest.json" target="_blank" rel="noreferrer">查看 7777 张作品的校验清单 ↗</a></div></section>
  </main>
  <footer className="nft-footer"><a className="nft-brand" href="/?view=nft"><ButterflyMark/><span>BUTTERFLY <b>7777</b></span></a><p>每一只蝴蝶，都值得被看见。<small>独立预览 · 真实链上铸造与交易尚未开放</small></p><div><button onClick={()=>setModal({kind:'rules'})}>收藏规则</button><a href="https://app.gupiao.sh/" target="_blank" rel="noreferrer">蝴蝶 Swap ↗</a><button onClick={()=>setModal({kind:'reset'})}>重置体验</button></div></footer>
  <dialog ref={dialog} className="nft-dialog" onCancel={e=>{if(busy)e.preventDefault();else setModal(null)}} onClick={e=>{if(e.target===dialog.current&&!busy)setModal(null)}}><div className="nft-dialog-inner"><button className="nft-close" aria-label="关闭弹窗" disabled={busy} onClick={()=>setModal(null)}>×</button>
   {modal?.kind==='mint'&&<><div className="nft-eyebrow">A MOMENT OF DISCOVERY</div><h2>{busy?'你的蝴蝶，即将现身。':'下一只，会是哪一只？'}</h2><div className={`nft-mystery ${busy?'revealing':''}`}><ButterflyMark/><span>{busy?'REVEALING…':'? / 7777'}</span></div><p className="nft-dialog-copy">随机编号 · 独立图案 · 领取后不再重复<br/>体验池剩余 {remaining.toLocaleString()} 只（另有 8 只用于市场演示）</p><div className="nft-receipt"><div><span>正式铸造单价</span><strong>0.01 BNB / 张</strong></div><div><span>本次体验支付</span><strong>0 BNB · 免费模拟</strong></div><div><span>正式收款地址</span><a href={`https://bscscan.com/address/${TREASURY}`} target="_blank" rel="noreferrer">{shorten(TREASURY)} ↗</a></div></div><button className="nft-btn primary full" disabled={busy||remaining<=0} onClick={reveal}>{busy?'正在揭晓…':'免费体验随机开启 ↗'}</button><p className="nft-disclaimer">仅在当前浏览器生成体验记录，不签名、不转账、不铸造链上 NFT。</p></>}
   {modal?.kind==='reveal'&&selected&&<><div className="nft-eyebrow">IT WAS MEANT TO BE.</div><h2>这一只，属于你了。</h2><img className="nft-revealed-art" src={selected.image} alt={selected.name}/><div className="nft-reveal-caption"><h3>{selected.name}</h3><span className="nft-rarity">✦ {selected.rarity}</span></div><p className="nft-dialog-copy">已加入「我的收藏」体验记录。</p><button className="nft-btn primary full" onClick={()=>{setModal(null);changeView('collection')}}>查看我的蝴蝶 ↗</button><button className="nft-text-button full" onClick={()=>setModal({kind:'mint'})}>再遇见一只 →</button></>}
   {modal?.kind==='detail'&&selected&&<><div className="nft-eyebrow">BUTTERFLY / #{pad(selected.id)}</div><h2>{selected.family}</h2><img className="nft-detail-art" src={selected.image} alt={selected.name}/><div className="nft-traits">{[['翅形',selected.wing],['纹理',selected.pattern],['光环',selected.halo],['稀有度',selected.rarity]].map(([k,v])=><div key={k}><small>{k}</small><strong>{v}</strong></div>)}</div><p className="nft-dialog-copy">{selected.rarity}作品共 {rarityCounts[selected.rarity]} 张，占总量 {((rarityCounts[selected.rarity]||0)/7777*100).toFixed(2)}%。稀有度不代表收益或价值承诺。</p><div className="nft-downloads"><a href={selected.image} download={`butterfly-${selected.id}.svg`}>下载原始作品 ↓</a><a href={`/nft/metadata/${selected.id}.json`} target="_blank" rel="noreferrer">查看元数据 ↗</a></div><p className="nft-dna">ART SHA-256<br/>{selected.dna}</p><button className="nft-btn primary full" onClick={()=>{const l=ledger.listings.find(x=>x.id===selected.id);if(l?.seller==='demo')setModal({kind:'buy',listing:l});else if(l?.seller==='you')transact(s=>cancel(s,selected.id),'已撤销体验挂单');else if(ledger.owned.includes(selected.id)){setPrice('0.02');setModal({kind:'list',id:selected.id})}else setModal({kind:'mint'});}}>{ledger.listings.some(x=>x.id===selected.id&&x.seller==='demo')?'购买此体验挂单':ledger.listings.some(x=>x.id===selected.id&&x.seller==='you')?'撤销我的体验挂单':ledger.owned.includes(selected.id)?'挂单出售':'随机开启 · 不指定编号'} ↗</button></>}
   {modal?.kind==='list'&&selected&&<><div className="nft-eyebrow">LIST YOUR BUTTERFLY</div><h2>给收藏，一个新旅程。</h2><div className="nft-order-art"><img src={selected.image} alt={selected.name}/><div><h3>{selected.name}</h3><span>体验收藏 · 你持有</span></div></div><label className="nft-price-label">挂单价格（BNB）<input inputMode="decimal" value={price} onChange={e=>setPrice(e.target.value)} aria-label="挂单价格" placeholder="0.02"/></label><div className="nft-receipt"><div><span>买家支付</span><strong>{formatBNB(listingPrice)} BNB</strong></div><div><span>平台服务费 · 7%</span><strong>{formatBNB(fee.fee)} BNB</strong></div><div><span>你预计收到 · 93%</span><strong className="nft-lime">{formatBNB(fee.seller)} BNB</strong></div></div><button className="nft-btn primary full" disabled={listingPrice<=0n} onClick={()=>transact(s=>list(s,selected.id,listingPrice),'体验挂单已发布，可在交易市场查看或撤销')}>确认体验挂单 ↗</button><p className="nft-disclaimer">本次挂单仅在当前浏览器展示，不会上传至真实市场。</p></>}
   {modal?.kind==='buy'&&selected&&<><div className="nft-eyebrow">COLLECT SOMETHING UNIQUE</div><h2>确认收藏这只蝴蝶。</h2><div className="nft-order-art"><img src={selected.image} alt={selected.name}/><div><h3>{selected.name}</h3><span>示例卖家 · 演示挂单</span></div></div><div className="nft-receipt"><div><span>体验成交价格</span><strong>{formatBNB(modal.listing.price)} BNB</strong></div><div><span>卖家所得 · 93%</span><strong>{formatBNB(splitFee(BigInt(modal.listing.price)).seller)} BNB</strong></div><div><span>平台所得 · 7%</span><strong>{formatBNB(splitFee(BigInt(modal.listing.price)).fee)} BNB</strong></div><div><span>平台收款地址</span><a href={`https://bscscan.com/address/${TREASURY}`} target="_blank" rel="noreferrer">{shorten(TREASURY)} ↗</a></div><div><span>本次实际支付</span><strong className="nft-lime">0 BNB · 模拟交易</strong></div></div><button className="nft-btn primary full" onClick={()=>transact(s=>buy(s,modal.listing.id,modal.listing.price),'体验购买完成，作品已加入我的收藏')}>免费体验购买 ↗</button><p className="nft-disclaimer">正式交易时 NFT 进入买家钱包，成交款按上述比例分配。当前没有任何链上转账。</p></>}
   {modal?.kind==='rules'&&<><div className="nft-eyebrow">COLLECTION DETAILS</div><h2>规则透明，收藏自在。</h2><div className="nft-rule-list"><h3>01 / 限量与随机</h3><p>作品总量 7,777 张，编号 1–7777。正式合约设计使用可验证随机数，每次分配一个未被领取的编号，无法指定或重复领取。</p><h3>02 / 铸造款</h3><p>每张 0.01 BNB，全部进入指定平台地址。网络 Gas 另计。</p><h3>03 / 市场分账</h3><p>本市场每笔成交款 93% 付给卖家，7% 付给平台。NFT 交给买家。铸造不另外收取 7%；未成交可撤销挂单。外部市场不保证执行本平台费率。</p><h3>04 / 预览状态</h3><p>当前为独立体验版，拥有记录和挂单保存在本浏览器。随机开启、买卖和分账均为模拟，不代表链上资产。钱包连接只读取地址。</p><h3>05 / 正式上线前</h3><p>需要完成合约部署、随机数服务配置、作品与元数据永久存储和独立安全审核，再开放真实支付。</p></div><div className="nft-treasury"><small>铸造款与市场服务费统一收款地址</small><code>{TREASURY}</code><a href={`https://bscscan.com/address/${TREASURY}`} target="_blank" rel="noreferrer">在 BscScan 查看 ↗</a></div></>}
   {modal?.kind==='history'&&<><div className="nft-eyebrow">YOUR JOURNEY</div><h2>每一次相遇，都有记录。</h2><p className="nft-dialog-copy">当前浏览器中的模拟操作，无链上交易哈希。</p><div className="nft-history">{ledger.activity.length===0?<p>还没有体验记录，去开启第一只蝴蝶吧。</p>:ledger.activity.map(a=><div key={a.id}><img src={`/nft/art/${a.token}.svg`} alt={`蝴蝶 #${a.token}`}/><div><strong>{{mint:'随机开启',list:'发布挂单',cancel:'撤销挂单',buy:'市场收藏'}[a.kind]} · #{pad(a.token)}</strong><small>{new Date(a.time).toLocaleString('zh-CN')}</small></div><span>{formatBNB(a.price)}<small>BNB · 模拟</small></span></div>)}</div></>}
   {modal?.kind==='wallet'&&<><div className="nft-eyebrow">WELCOME TO BUTTERFLY</div><h2>用你的方式，开始收藏。</h2><p className="nft-dialog-copy">现在可以直接体验，无需充值。连接钱包只读取公开地址，本预览不会要求签名或授权资产。</p>{wallet&&<div className="nft-treasury"><code>{wallet}</code></div>}<button className="nft-btn primary full" onClick={connectWallet}>{wallet?'重新连接钱包':'连接浏览器钱包'} ↗</button><button className="nft-btn secondary full" onClick={()=>{setModal(null);notify('已进入免钱包体验，可以随机开启或购买示例挂单')}}>免钱包体验 →</button>{wallet&&<button className="nft-text-button full" onClick={()=>{setWallet('');setModal(null)}}>断开本站连接</button>}</>}
   {modal?.kind==='reset'&&<><div className="nft-eyebrow">START A NEW JOURNEY</div><h2>重新开始体验？</h2><p className="nft-dialog-copy">将清空本浏览器的体验收藏、挂单和操作记录，恢复示例市场。不会影响任何真实钱包资产。</p><button className="nft-btn primary full" onClick={()=>{commit(initialLedger());setModal(null);notify('体验记录已重置')}}>确认重置体验</button><button className="nft-text-button full" onClick={()=>setModal(null)}>保留我的体验记录</button></>}
  </div></dialog>
  {notice&&<div role="status" className="nft-toast"><span>✦</span>{notice}<button aria-label="关闭提示" onClick={()=>setNotice('')}>×</button></div>}
 </div>;
}
