import {beforeEach,describe,expect,it,vi} from 'vitest'
import type {PublicClient,WalletClient} from 'viem'
import {BUDGET,OWNER,VAULT_PORTAL} from './protocol'
import {prepare,submit,records,checkReceipt,type Prepared} from './service'
const hash=('0x'+'a'.repeat(64)) as `0x${string}`
function rpc(){return {getChainId:vi.fn().mockResolvedValue(56),getCode:vi.fn().mockResolvedValue('0x1234'),call:vi.fn().mockResolvedValue({data:'0x'}),estimateGas:vi.fn().mockResolvedValue(100000n),getGasPrice:vi.fn().mockResolvedValue(1_000_000_000n),getBalance:vi.fn().mockResolvedValue(BUDGET),waitForTransactionReceipt:vi.fn().mockResolvedValue({status:'success',gasUsed:100000n,effectiveGasPrice:1_000_000_000n,logs:[]}),getTransaction:vi.fn().mockResolvedValue({from:OWNER,to:VAULT_PORTAL,value:0n})}}
function wallet(){return {getChainId:vi.fn().mockResolvedValue(56),getAddresses:vi.fn().mockResolvedValue([OWNER]),sendTransaction:vi.fn().mockResolvedValue(hash)}}
const p=():Prepared=>({account:OWNER,to:VAULT_PORTAL,data:'0x1234',value:0n,gas:125000n,gasPrice:1_200_000_001n,maximumCost:150000000125000n,createdAt:Date.now(),label:'test'})
beforeEach(()=>localStorage.clear())
describe('signing and budget invariants',()=>{
  it('rejects missing code, reverts, wrong chains and over-budget amounts before signing',async()=>{const c=rpc();c.getCode.mockResolvedValue('0x');await expect(prepare(c as unknown as PublicClient,OWNER,VAULT_PORTAL,'0x',0n,'x')).rejects.toThrow('目标地址不是已部署合约');c.getCode.mockResolvedValue('0x12');c.call.mockRejectedValue(Error('contract revert'));await expect(prepare(c as unknown as PublicClient,OWNER,VAULT_PORTAL,'0x',0n,'x')).rejects.toThrow('contract revert');await expect(prepare(c as unknown as PublicClient,OWNER,VAULT_PORTAL,'0x',BUDGET+1n,'x')).rejects.toThrow('预算')})
  it('rechecks account and rejects stale reviews without sending',async()=>{const c=rpc(),w=wallet();w.getAddresses.mockResolvedValue([VAULT_PORTAL]);await expect(submit(c as unknown as PublicClient,w as unknown as WalletClient,p(),()=>{})).rejects.toThrow('账号');expect(w.sendTransaction).not.toHaveBeenCalled();w.getAddresses.mockResolvedValue([OWNER]);await expect(submit(c as unknown as PublicClient,w as unknown as WalletClient,{...p(),createdAt:0},()=>{})).rejects.toThrow('过期')})
  it('persists the hash before polling and never rebroadcasts a timed-out transaction',async()=>{const c=rpc(),w=wallet();c.waitForTransactionReceipt.mockImplementation(async()=>{expect(records()[0].hash).toBe(hash);throw Error('timeout')});await expect(submit(c as unknown as PublicClient,w as unknown as WalletClient,p(),()=>{})).rejects.toThrow('timeout');expect(records()[0].status).toBe('pending');await expect(submit(c as unknown as PublicClient,w as unknown as WalletClient,p(),()=>{})).rejects.toThrow('待确认');expect(w.sendTransaction).toHaveBeenCalledTimes(1)})
  it('records a reverted receipt as reverted and accounts for gas',async()=>{const c=rpc(),w=wallet();c.waitForTransactionReceipt.mockResolvedValue({status:'reverted',gasUsed:50000n,effectiveGasPrice:1_000_000_000n,logs:[]});const r=await submit(c as unknown as PublicClient,w as unknown as WalletClient,p(),()=>{});expect(r.status).toBe('reverted');expect(r.cost).toBe('50000000000000')})
  it('wallet rejection does not fabricate a hash or success',async()=>{const c=rpc(),w=wallet();w.sendTransaction.mockRejectedValue(Error('User rejected'));await expect(submit(c as unknown as PublicClient,w as unknown as WalletClient,p(),()=>{})).rejects.toThrow('User rejected');expect(records()).toHaveLength(0);expect(c.waitForTransactionReceipt).not.toHaveBeenCalled()})
  it('receipt checking cannot send transactions',async()=>{await expect(checkReceipt(rpc() as unknown as PublicClient,hash)).rejects.toThrow('找不到交易记录')})
})
