import { useEffect, useRef, useState } from 'react'
import { createWalletClient, custom, encodeFunctionData, erc20Abi, formatEther, getAddress, isAddress, type Address, type Hex } from 'viem'
import { bsc } from 'viem/chains'
import catalog from '../../public/vault/templates.json'
import stocks from '../swap/stock-tokens.json'
import { discoverWalletProviders, type WalletProviderDetail } from '../web3/walletProviders'
import { OWNER, REVENUE, ZERO, VAULT_PORTAL, components, defaults, encodeSchema, fieldValue, launchAbi, launchData, launchParams, mineSalt, uiAbi, type Field, type LaunchInput, type Method, type Row, type Schema } from './protocol'
import { checkReceipt, client, message, prepare, readFactory, records, submit, type Prepared, type RecordEntry } from './service'
import { acceptanceInput, acceptanceAccount, acceptanceMaxCost } from './acceptance'
import { MintPanel } from './MintPanel'
import { ConfirmedVault } from './ConfirmedVault'
import './vault-live.css'

const short=(s:string)=>s.slice(0,8)+'…'+s.slice(-6)
const explorer=(a:string)=>`https://bscscan.com/${a.length===66?'tx':'address'}/${a}`
const json=(v:unknown)=>JSON.stringify(v,(_,x)=>typeof x==='bigint'?x.toString():x,2)
const initial:LaunchInput={name:'',symbol:'',meta:'',quoteToken:ZERO,buyPct:'3',sellPct:'3',taxDays:'36500',protectionDays:'30',mktPct:'100',burnPct:'0',dividendPct:'0',lpPct:'0',minimumHold:'0',dividendToken:ZERO}

function Fields({fields,rows,onChange,array,disabled=false}:{fields:readonly Field[];rows:Row[];onChange:(r:Row[])=>void;array:boolean;disabled?:boolean}){
  return <>{rows.map((row,index)=><div className="vl-fields" key={index}>{fields.map(f=><label key={f.name}><span>{f.name}{f.decimals>0?`（数量，${f.decimals} 位精度）`:''}</span>{f.fieldType==='bool'?<select disabled={disabled} value={row[f.name]||'false'} onChange={e=>onChange(rows.map((r,i)=>i===index?{...r,[f.name]:e.target.value}:r))}><option value="false">false</option><option value="true">true</option></select>:<input disabled={disabled} value={row[f.name]??''} autoComplete="off" onChange={e=>onChange(rows.map((r,i)=>i===index?{...r,[f.name]:e.target.value}:r))}/>}<small>{f.description}</small></label>)}{array&&rows.length>1&&<button disabled={disabled} onClick={()=>onChange(rows.filter((_,i)=>i!==index))}>删除本组</button>}</div>)}{array&&<button disabled={disabled||rows.length>=10} onClick={()=>onChange([...rows,defaults(fields)])}>添加一组参数</button>}</>
}
export function VaultPage(){
  const query=new URLSearchParams(location.search),requested=(query.get('template')||'percent-buyback').replace(/^vault-/,'')
  const acceptance=query.get('setup')==='acceptance'
  const [mode,setMode]=useState(acceptance?'receipt':['launch','manage','history','mint','receipt'].includes(query.get('panel')||'')?query.get('panel')!:'launch')
  const [template,setTemplate]=useState(catalog.find(t=>t.id==='vault-'+(acceptance?'percent-buyback':requested))||catalog.find(t=>t.id==='vault-percent-buyback')!)
  const [factory,setFactory]=useState<Awaited<ReturnType<typeof readFactory>>|null>(null)
  const [rows,setRows]=useState<Row[]>([{}]),[input,setInput]=useState(acceptance?acceptanceInput:initial),[file,setFile]=useState<File|null>(null)
  const [providers,setProviders]=useState<WalletProviderDetail[]>([]),[wallet,setWallet]=useState<WalletProviderDetail|null>(null),[account,setAccount]=useState<Address|null>(null),[walletOpen,setWalletOpen]=useState(false),[balance,setBalance]=useState('')
  const [busy,setBusy]=useState(false),[status,setStatus]=useState(''),[error,setError]=useState(''),[review,setReview]=useState<Prepared|null>(null),[predicted,setPredicted]=useState<Address|null>(null),[history,setHistory]=useState<RecordEntry[]>(records)
  const [vaultInput,setVaultInput]=useState(query.get('address')||''),[vault,setVault]=useState<Address|null>(null),[methods,setMethods]=useState<readonly Method[]>([]),[vaultDescription,setVaultDescription]=useState(''),[methodRows,setMethodRows]=useState<Record<string,Row[]>>({}),[result,setResult]=useState<Record<string,string>>({})
  const [ack,setAck]=useState(false),epoch=useRef(0),operation=useRef(false),reviewRef=useRef<HTMLElement|null>(null)
  useEffect(()=>{if(review)reviewRef.current?.scrollIntoView({block:'start',behavior:'smooth'})},[review])
  const invalidate=()=>{epoch.current++;setReview(null);setAck(false)}
  function edit<K extends keyof LaunchInput>(key:K,value:LaunchInput[K]){invalidate();setInput(s=>({...s,[key]:value}))}
  useEffect(()=>discoverWalletProviders(setProviders),[])
  useEffect(()=>{let active=true;setFactory(null);setError('');setReview(null);epoch.current++
    if(mode!=='launch'){setStatus('');return}
    if(!template.factory){setStatus('Mint 工厂尚未完成独立部署，当前不能创建募资项目。');return}
    setStatus('正在从 BSC 读取真实合约参数…')
    readFactory(getAddress(template.factory)).then(f=>{if(active){setFactory(f);setRows([acceptance?{...defaults(f.schema.fields),intervalSeconds:'60',spendBps:'1000'}:defaults(f.schema.fields)]);setStatus('合约参数已读取')}}).catch(e=>{if(active){setError(message(e));setStatus('读取失败，可重新选择模板重试')}})
    return()=>{active=false}
  },[template,mode])
  useEffect(()=>{if(!wallet)return;const provider=wallet.provider as typeof wallet.provider&{on?:(e:string,fn:()=>void)=>void;removeListener?:(e:string,fn:()=>void)=>void};const change=()=>{invalidate();setAccount(null);setBalance('');setStatus('钱包状态已变化，请重新连接')};provider.on?.('accountsChanged',change);provider.on?.('chainChanged',change);provider.on?.('disconnect',change);return()=>{provider.removeListener?.('accountsChanged',change);provider.removeListener?.('chainChanged',change);provider.removeListener?.('disconnect',change)}},[wallet])
  async function run(action:()=>Promise<void>){if(operation.current)return;operation.current=true;setBusy(true);setError('');try{await action()}catch(e){setError(message(e))}finally{operation.current=false;setBusy(false);setHistory(records())}}
  async function connect(p:WalletProviderDetail){await run(async()=>{invalidate();const w=createWalletClient({chain:bsc,transport:custom(p.provider)});await w.requestAddresses();if(await w.getChainId()!==56){try{await w.switchChain({id:56})}catch(e){if((e as {code?:number}).code!==4902)throw e;await w.addChain({chain:bsc});await w.switchChain({id:56})}}const [a]=await w.getAddresses();if(!a||await w.getChainId()!==56)throw Error('钱包未连接到 BNB Chain');setWallet(p);setAccount(a);setWalletOpen(false);setBalance(formatEther(await client.getBalance({address:a})));setStatus('真实钱包已连接')})}
  async function upload(){await run(async()=>{if(!account)throw Error('请先连接钱包');if(!file)throw Error('请选择 PNG、JPEG 或 WebP 封面');if(file.size>2_000_000)throw Error('图片最大 2 MB');invalidate();setStatus('正在上传资料到 Flap / IPFS…');const base64=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onerror=reject;r.onload=()=>resolve(String(r.result).split(',')[1]);r.readAsDataURL(file)});const response=await fetch('/api/vault-metadata',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image:base64,mime:file.type,description:input.name+' · '+input.symbol,creator:account})});const data=await response.json();if(!response.ok)throw Error(data.error||'上传失败');edit('meta',data.cid);setStatus('资料上传成功，CID 已填入')})}
  async function checkLaunch(){await run(async()=>{
    setReview(null);setAck(false);if(acceptance)throw Error('验收金库已经创建，请打开已创建金库页面');if(!account||!wallet)throw Error('请先连接真实钱包');if(!factory||!template.factory)throw Error('合约参数尚未读取');const current=epoch.current
    if(acceptance&&account.toLowerCase()!==acceptanceAccount.toLowerCase())throw Error('请切换到验收管理员钱包 '+acceptanceAccount)
    if(acceptance&&records().some(r=>r.status==='success'&&r.label==='创建 Butterfly Vault Check · 百分比回购 · 3D'))throw Error('本浏览器已有成功验收交易，请打开交易记录，不要重复创建')
    const data=encodeSchema(factory.schema,rows);launchParams(input,getAddress(template.factory),data,('0x'+'1'.repeat(64)) as Hex)
    setStatus('正在计算代币地址…');const salt=await mineSalt(n=>setStatus(`正在计算 7777 地址，已尝试 ${n.toLocaleString()} 次`),()=>epoch.current!==current)
    const existingCode=await client.getCode({address:salt.address});if(existingCode&&existingCode!=='0x')throw Error('预测地址已被使用，请重试')
    const params=launchParams(input,getAddress(template.factory),data,salt.salt)
    setStatus('正在模拟真实部署和估算网络费…');const checked=await prepare(client,account,VAULT_PORTAL,launchData(params),0n,`创建 ${input.name} · ${template.name}`)
    if(acceptance&&checked.maximumCost>acceptanceMaxCost)throw Error('本次验收最大网络费超过 0.002 BNB，暂不发送')
    if(current!==epoch.current)throw Error('参数或钱包已变化，请重新检查')
    setPredicted(salt.address);setReview(checked);setStatus('模拟通过，请核对交易后在钱包签名')
  })}
  async function sign(){await run(async()=>{if(!review||!wallet||!ack)throw Error('请先核对交易详情');const p=review;setReview(null);setAck(false);setStatus('请在钱包确认交易…');const r=await submit(client,createWalletClient({chain:bsc,transport:custom(wallet.provider)}),p,hash=>{setHistory(records());setStatus(`已提交交易 ${hash}，正在等待确认。请勿重复发送。`)});setStatus(r.status==='success'?'链上交易成功，已确认回执':'交易已回滚，请查看链上原因');if(r.contractAddress)setStatus(`Mint 工厂部署成功：${r.contractAddress}。请在 Mint 页面填入交易哈希 ${r.hash} 并核验工厂。`);if(r.vault){setVaultInput(r.vault);setMode('manage')}if(account)setBalance(formatEther(await client.getBalance({address:account})))})}
  async function loadVault(){await run(async()=>{invalidate();setVault(null);setMethods([]);if(!isAddress(vaultInput))throw Error('请输入完整金库合约地址');const a=getAddress(vaultInput);const code=await client.getCode({address:a});if(!code||code==='0x')throw Error('此地址没有合约');const [rawSchema,description]=await Promise.all([client.readContract({address:a,abi:uiAbi,functionName:'vaultUISchema'}),client.readContract({address:a,abi:uiAbi,functionName:'description'})]);const schema=rawSchema as {methods:readonly Method[]};if(!Array.isArray(schema.methods)||schema.methods.length>100)throw Error('合约接口数量异常');setVault(a);setMethods(schema.methods);setVaultDescription(description);setMethodRows(Object.fromEntries(schema.methods.map(m=>[m.name,[defaults(m.inputs)]])));setResult({});setStatus('已读取金库的实时接口和状态')})}
  async function callMethod(m:Method){await run(async()=>{invalidate();if(!vault)throw Error('请先读取金库');const rs=methodRows[m.name]||[{}];const fields=components(m.inputs),outputs=components(m.outputs)
    const args=rs.map(r=>m.inputs.map(f=>fieldValue(f,r[f.name]??'')))
    const abi=[{type:'function',name:m.name,stateMutability:m.isWriteMethod?'nonpayable':'view',inputs:m.isInputArray?[{type:'tuple[]',components:fields}]:fields,outputs:m.isOutputArray?[{type:'tuple[]',components:outputs}]:outputs}] as const
    const data=encodeFunctionData({abi,functionName:m.name,args:m.isInputArray?[args]:args[0]})
    if(!m.isWriteMethod){const value=await client.readContract({address:vault,abi,functionName:m.name,args:m.isInputArray?[args]:args[0],account:account||undefined});setResult(r=>({...r,[m.name]:json(value)}));setStatus('链上查询已更新');return}
    if(!account)throw Error('请先连接钱包');const current=epoch.current
    for(const approval of m.approvals){if(!['taxToken','lpToken'].includes(approval.tokenType))throw Error('该操作需要尚未支持的授权类型，请使用金库官方界面');if(m.isInputArray)throw Error('此数组操作需要专用授权适配，当前暂不支持');const field=m.inputs.find(f=>f.name===approval.amountFieldName);if(!field)throw Error('合约授权参数缺失');const amount=fieldValue(field,rs[0][field.name]||'');if(typeof amount!=='bigint'||amount<=0n)throw Error('授权金额必须大于 0');const token=await client.readContract({address:vault,abi:uiAbi,functionName:approval.tokenType as 'taxToken'|'lpToken'});if(token===ZERO||!await client.getCode({address:token}))throw Error('授权代币地址无效');const allowance=await client.readContract({address:token,abi:erc20Abi,functionName:'allowance',args:[account,vault]});if(allowance<amount){const targetAmount=allowance===0n?amount:0n;const p=await prepare(client,account,token,encodeFunctionData({abi:erc20Abi,functionName:'approve',args:[vault,targetAmount]}),0n,`授权 ${token} 给金库 ${vault}，原始数量 ${targetAmount}`);if(epoch.current!==current)throw Error('钱包已变化，请重试');setReview(p);setStatus('请先核对并完成代币授权，再点击原操作');return}}
    const p=await prepare(client,account,vault,data,0n,m.description||m.name);if(epoch.current!==current)throw Error('钱包已变化，请重试');setReview(p);setStatus('操作模拟通过，请核对交易')
  })}
  function modeChange(next:string){invalidate();setMode(next);setError('');setStatus('')}
  const inputField=(key:keyof LaunchInput,label:string)=><label><span>{label}</span><input disabled={busy} value={input[key]} onChange={e=>edit(key,e.target.value)}/></label>
  return <div className="vl-root"><header className="vl-header"><a href="/?view=vault"><img src="/flap-stock-avatar.png" alt="蝴蝶股票"/>金库</a><nav><button onClick={()=>{if(acceptance)location.href='/?view=vault-live';else modeChange('launch')}}>一键部署</button><button onClick={()=>modeChange('receipt')}>已创建金库</button><button onClick={()=>modeChange('manage')}>管理金库</button><button onClick={()=>modeChange('history')}>交易记录</button><button onClick={()=>modeChange('mint')}>Mint</button></nav><button disabled={busy} onClick={()=>setWalletOpen(true)}>{account?short(account):'连接钱包'}</button></header>
    <main className="vl-main"><p className="vl-eyebrow">蝴蝶股票 · BNB CHAIN · 独立测试入口</p><h1>{mode==='launch'?'创建链上金库':mode==='manage'?'管理链上金库':mode==='mint'?'Mint 募资部署':mode==='receipt'?'已创建金库':'链上交易记录'}</h1>
    <p className="vl-sub">{account?`已连接 ${account} · ${Number(balance||0).toFixed(6)} BNB`:'使用钱包签名，每次交易都会实际写入 BSC 主网。'}</p>
    {status&&<p className="vl-status" role="status">{status}</p>}{error&&<p className="vl-error" role="alert">{error}</p>}
    {(mode==='receipt'||acceptance&&mode==='launch')&&<ConfirmedVault/>}
    {mode==='launch'&&!acceptance&&<><section className="vl-card"><h2>1 选择模板</h2><select disabled={busy||acceptance} value={template.id} onChange={e=>{invalidate();setTemplate(catalog.find(t=>t.id===e.target.value)!);setInput(s=>({...s,meta:s.meta}));}}>{catalog.filter(t=>t.factory).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><p>{template.summary.replace(/已验证，低风险。|已审计，/g,'')}</p>{template.factory&&<a href={explorer(template.factory)} target="_blank" rel="noreferrer">查看工厂合约：{template.factory}</a>}
      {factory&&<><p className="vl-note">此工厂由原作者部署。项目管理员配置不会改变该工厂的控制权或固定作者费用。{factory.owner&&`链上 owner：${factory.owner}`}</p><details><summary>查看链上参数说明与约束</summary><p>{factory.schema.description}</p>{factory.policies.map((p,i)=><p key={i}>{p.target} {p.operator} {p.value} — {p.description}</p>)}</details><Fields fields={factory.schema.fields} rows={rows} array={factory.schema.isArray} disabled={busy} onChange={r=>{invalidate();setRows(r)}}/>{!factory.schema.fields.length&&<p>此模板无需额外参数。</p>}</>}
    </section><section className="vl-card"><h2>2 代币资料</h2><div className="vl-fields">{inputField('name','代币名称')}{inputField('symbol','代币符号')}</div><label><span>封面（PNG / JPEG / WebP，最大 2 MB）</span><input disabled={busy} type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{invalidate();setFile(e.target.files?.[0]||null);setInput(s=>({...s,meta:''}))}}/></label><button disabled={busy||!file} onClick={()=>void upload()}>上传封面与资料到 IPFS</button>{inputField('meta','资料 CID（上传后自动填入，也可使用已有 Flap 资料 CID）')}</section>
    <section className="vl-card"><h2>3 底池与税收</h2><label><span>支付底池</span><select disabled={busy} value={input.quoteToken} onChange={e=>edit('quoteToken',getAddress(e.target.value))}><option value={ZERO}>BNB</option>{(Array.isArray(stocks)?stocks:[]).map((s:{address:string;symbol:string})=><option key={s.address} value={getAddress(s.address)}>{s.symbol}</option>)}</select><small>实际兼容性由工厂校验和交易模拟确认。</small></label><p className="vl-note">当前发射不做创建者首购（0），只支付网络费。发射后可通过蝴蝶swap购买。</p><div className="vl-fields">{inputField('buyPct','买入税 %')}{inputField('sellPct','卖出税 %')}{inputField('taxDays','税收有效天数')}{inputField('protectionDays','保护期天数')}{inputField('mktPct','税收分配：金库 %')}{inputField('burnPct','税收分配：销毁 %')}{inputField('dividendPct','税收分配：持币分红 %')}{inputField('lpPct','税收分配：流动性 %')}{inputField('minimumHold','分红最低持有量（代币数量）')}{inputField('dividendToken','分红代币地址（0x000…000 表示协议默认）')}</div></section>
    <section className="vl-card"><h2>4 权限与收益</h2><p>项目管理员：<code>{OWNER}</code></p><p>平台佣金接收人：<code>{REVENUE}</code></p><p>本次创建者：<code>{account||'连接钱包后显示'}</code></p><p>平台佣金由 Flap V3 按税率计算；模板作者固定收费、用户分红和回购资金由对应合约决定。创建者不等于第三方工厂所有者。</p><button className="vl-primary" disabled={busy||!factory} onClick={()=>void checkLaunch()}>{busy?'正在处理…':'检查参数并模拟部署'}</button></section></>}
    {mode==='manage'&&<><section className="vl-card"><h2>读取已有金库</h2><label><span>金库合约地址</span><input value={vaultInput} disabled={busy} onChange={e=>{invalidate();setVault(null);setMethods([]);setVaultInput(e.target.value)}}/></label><button disabled={busy} onClick={()=>void loadVault()}>读取链上状态</button>{vault&&<><a href={explorer(vault)} target="_blank" rel="noreferrer">{vault}</a><p>{vaultDescription}</p></>}</section>{methods.map(m=><section className="vl-card" key={m.name}><h2>{m.name} · {m.isWriteMethod?'链上操作':'实时查询'}</h2><p>{m.description}</p><Fields fields={m.inputs} rows={methodRows[m.name]||[{}]} array={m.isInputArray} disabled={busy} onChange={r=>{invalidate();setMethodRows(s=>({...s,[m.name]:r}))}}/><button disabled={busy} onClick={()=>void callMethod(m)}>{m.isWriteMethod?'检查并模拟操作':'查询'}</button>{result[m.name]&&<pre>{result[m.name]}</pre>}</section>)}</>}
    {mode==='mint'&&<MintPanel account={account} busy={busy} run={run} status={setStatus} review={p=>{setReview(p);setAck(false)}} connect={()=>setWalletOpen(true)}/>}
    {mode==='history'&&<section className="vl-card"><p>本浏览器记录；刷新待确认交易只查询回执，不重复发送。</p>{!history.length&&<p>尚无交易。</p>}{history.slice().reverse().map(r=><article className="vl-record" key={r.hash}><h3>{r.label}</h3><p>{r.status==='pending'?'待确认':r.status==='success'?'链上成功':'已回滚'} · {new Date(r.time).toLocaleString()}</p><a href={explorer(r.hash)} target="_blank" rel="noreferrer">{r.hash}</a>{r.cost&&<p>实际支出：{formatEther(BigInt(r.cost))} BNB</p>}{r.vault&&<button onClick={()=>{setVaultInput(r.vault!);modeChange('manage')}}>管理此金库</button>}{r.status==='pending'&&<button disabled={busy} onClick={()=>void run(async()=>{const updated=await checkReceipt(client,r.hash);setStatus(updated.status==='success'?'回执确认成功':'交易已回滚')})}>检查回执</button>}</article>)}</section>}
    {review&&<section ref={reviewRef} className="vl-card vl-review"><h2>核对真实交易</h2><p>{review.label}</p><dl><dt>网络</dt><dd>BNB Chain / 56</dd><dt>签名钱包</dt><dd>{review.account}</dd><dt>调用目标</dt><dd>{review.to||'创建新合约（由钱包发送部署交易）'}</dd><dt>BNB 转入金额</dt><dd>{formatEther(review.value)} BNB</dd><dt>最大网络费</dt><dd>{formatEther(review.gas*review.gasPrice)} BNB</dd>{!review.to&&<><dt>工厂管理员</dt><dd>{OWNER}</dd><dt>平台佣金接收人</dt><dd>{REVENUE}</dd></>}{review.to===VAULT_PORTAL&&<><dt>预测代币地址</dt><dd>{predicted}</dd><dt>平台佣金接收人</dt><dd>{REVENUE}</dd></>}</dl><details><summary>查看完整交易数据</summary><pre>{review.data}</pre></details><label className="vl-check"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/>我已核对目标、金额和权限，确认这是主网交易。</label><button className="vl-primary" disabled={busy||!ack} onClick={()=>void sign()}>在钱包签名并发送</button><button disabled={busy} onClick={()=>{setReview(null);setAck(false)}}>返回修改</button></section>}
    <footer><a href="/?view=vault">返回金库目录</a><a href="/?view=swap">蝴蝶swap</a><a href="/">返回首页</a><p>独立测试入口 · 真实链上操作由你的钱包签名。交易记录以 BscScan 为准。</p></footer></main>
    {walletOpen&&<div className="vl-modal" role="dialog" aria-modal="true" aria-label="连接钱包"><div className="vl-card"><h2>连接钱包</h2>{providers.map(p=><button disabled={busy} key={p.info.uuid} onClick={()=>void connect(p)}>{p.info.name}</button>)}{!providers.length&&<p>电脑请启用 MetaMask、OKX 等钱包扩展；手机请在钱包的 DApp 浏览器中打开此页面。</p>}<button onClick={()=>setWalletOpen(false)}>关闭</button></div></div>}
  </div>
}
