import { useEffect, useRef, useState } from 'react'
import { BOARD_CATEGORIES, BOARD_SORTS, type BoardCategory, type BoardSort, type BoardSnapshot, type BoardRow } from './flapBoard'
import quotes from './flap-quotes.json'
import { percent, usd } from './marketData'
import { ProductDialog } from './TokenPicker'
import './flap-board.css'
const short=(s:string)=>`${s.slice(0,6)}…${s.slice(-4)}`
const tax=(n:number|null)=>n===null?'—':`${n/100}%`
const num=(n:number|null)=>n===null?'—':n.toLocaleString('en-US')
const original=(address:string)=>`https://flap.sh/bnb/${address}?lang=zh`
function CoinImage({row}:{row:BoardRow}){const [failed,setFailed]=useState(false);return <span className="board-coin-image">{row.image&&!failed?<img src={row.image} alt="" loading="lazy" referrerPolicy="no-referrer" onError={()=>setFailed(true)}/>:row.symbol.slice(0,1)}</span>}
function Change({value}:{value:number|null}){return <span className={value===null?'':value>=0?'swap-positive':'swap-negative'}>{percent(value)}</span>}
export function FlapBoard({favorites,onFavorite,onTrade}:{favorites:string[];onFavorite:(a:string)=>void;onTrade?:(a:string)=>void}){
  const [category,setCategory]=useState<BoardCategory>('trending'),[sort,setSort]=useState<BoardSort>('default'),[order,setOrder]=useState<'asc'|'desc'>('desc')
  const [layout,setLayout]=useState<'list'|'grid'>('list'),[filters,setFilters]=useState(false),[query,setQuery]=useState(''),[quote,setQuote]=useState(''),[stage,setStage]=useState('all'),[minimum,setMinimum]=useState(''),[favoriteOnly,setFavoriteOnly]=useState(false)
  const [data,setData]=useState<(BoardSnapshot&{key:string})|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[refresh,setRefresh]=useState(0),[cursor,setCursor]=useState(''),[detail,setDetail]=useState<BoardRow|null>(null)
  const requestId=useRef(0)
  const key=JSON.stringify([category,sort,order,quote,refresh])
  const current=data?.key===key?data:null
  const active=BOARD_CATEGORIES.find(c=>c.id===category)!
  useEffect(()=>{const id=setInterval(()=>{if(!document.hidden){setCursor('');setRefresh(n=>n+1)}},60000);return()=>clearInterval(id)},[])
  useEffect(()=>{
    const id=++requestId.current,controller=new AbortController();setLoading(true);setError('')
    const p=new URLSearchParams({category,sort,order});if(quote)p.set('quote',quote);if(cursor)p.set('cursor',cursor)
    void fetch(`/api/flap-board?${p}`,{signal:controller.signal}).then(async r=>{
      if(!r.ok)throw Error('Flap 此分类暂时无法读取。你可以重试，或打开 Flap 原站查看。')
      const next=await r.json() as BoardSnapshot
      if(next.category!==category||!Array.isArray(next.items)||!Number.isFinite(next.fetchedAt)||!['page','api'].includes(next.source))throw Error('看板数据格式异常，请刷新。')
      if(id!==requestId.current||controller.signal.aborted)return
      setData(old=>{const items=cursor&&old?.key===key?[...old.items,...next.items]:next.items;return {...next,key,items:[...new Map(items.map(r=>[r.address,r])).values()].slice(0,400)}})
    }).catch(e=>{if(!controller.signal.aborted&&id===requestId.current)setError(e.message)}).finally(()=>{if(!controller.signal.aborted&&id===requestId.current)setLoading(false)})
    return()=>controller.abort()
  },[key,cursor,category,sort,order,quote])
  function changeSort(next:BoardSort){setCursor('');if(next===sort)setOrder(order==='desc'?'asc':'desc');else{setSort(next);setOrder('desc')}}
  const loaded=current?.items??[]
  const rows=loaded.filter(r=>(`${r.symbol} ${r.name} ${r.address}`.toLowerCase().includes(query.trim().toLowerCase()))&&(!favoriteOnly||favorites.includes(r.address))&&(stage==='all'||stage==='listed'&&r.listed===true||stage==='bonding'&&r.listed===false)&&(!minimum||r.liquidity!==null&&r.liquidity>=Number(minimum)))
  const quoteLabel=(r:BoardRow)=>quotes.find(q=>q.address===r.quoteAddress)?.symbol||(r.quoteAddress?short(r.quoteAddress):'未知')
  const favorite=(r:BoardRow)=>favorites.includes(r.address)
  function actions(r:BoardRow){return <div className="board-actions"><button aria-label={`${favorite(r)?'取消收藏':'收藏'} ${r.symbol}`} aria-pressed={favorite(r)} onClick={()=>onFavorite(r.address)}>{favorite(r)?'★':'☆'}</button><button onClick={()=>setDetail(r)} aria-label={`查看 ${r.symbol} 详情`}>详情</button>{r.listed===true&&onTrade?<button className="board-trade" onClick={()=>onTrade(r.address)} aria-label={`选择 ${r.symbol} 交易`}>交易 ↗</button>:<a href={original(r.address)} target="_blank" rel="noreferrer">Flap ↗</a>}</div>}
  const sortable=(id:BoardSort,label:string)=><th aria-sort={sort===id?(order==='desc'?'descending':'ascending'):'none'}><button onClick={()=>changeSort(id)}>{label} <span>{sort===id?(order==='desc'?'↓':'↑'):'↕'}</span></button></th>
  return <div className="flap-board">
    <div className="board-intro"><div><span className="board-kicker">FLAP ECOSYSTEM</span><h2>下一只蝴蝶，从这里发现。</h2><p>分类发现 · 实时行情 · 链上核对</p></div><a href="https://flap.sh/board?lang=zh" target="_blank" rel="noreferrer">Flap 原站 ↗</a></div>
    <div className="board-category-scroll"><div className="board-categories" role="group" aria-label="Flap 代币分类">{BOARD_CATEGORIES.map(c=><button key={c.id} aria-pressed={category===c.id} onClick={()=>{setCategory(c.id);setCursor('');setQuery('');setStage('all')}}><span aria-hidden="true">{c.icon}</span>{c.label}</button>)}</div></div>
    <div className="board-control-row"><label className="board-search"><span aria-hidden="true">⌕</span><input aria-label="搜索看板已加载代币" placeholder="搜索已加载代币 / 合约地址" value={query} maxLength={120} onChange={e=>setQuery(e.target.value)}/></label><div className="board-tools"><button aria-pressed={favoriteOnly} onClick={()=>setFavoriteOnly(!favoriteOnly)}>☆ 收藏</button><button aria-expanded={filters} onClick={()=>setFilters(!filters)}>筛选 {filters?'−':'+'}</button><div className="board-view" role="group" aria-label="看板视图"><button aria-label="列表视图" aria-pressed={layout==='list'} onClick={()=>setLayout('list')}>☷</button><button aria-label="卡片视图" aria-pressed={layout==='grid'} onClick={()=>setLayout('grid')}>▦</button></div><button aria-label="刷新 Flap 看板" disabled={loading} onClick={()=>{setCursor('');setRefresh(n=>n+1)}}>↻</button></div></div>
    {filters&&<div className="board-filters"><label>计价代币<select aria-label="计价代币" value={quote} onChange={e=>{setQuote(e.target.value);setCursor('')}}><option value="">全部计价币</option>{quotes.map(q=><option key={q.address} value={q.address}>{q.symbol}</option>)}</select></label><label>发行阶段<select aria-label="发行阶段" value={stage} onChange={e=>setStage(e.target.value)}><option value="all">全部阶段</option><option value="listed">已毕业</option><option value="bonding">内盘中</option></select></label><label>最低流动性（USD）<input aria-label="最低流动性" inputMode="decimal" placeholder="不限" value={minimum} onChange={e=>{if(/^\d{0,12}(\.\d{0,2})?$/.test(e.target.value))setMinimum(e.target.value)}}/></label><button onClick={()=>{setQuote('');setStage('all');setMinimum('');setFavoriteOnly(false);setQuery('');setCursor('')}}>重置筛选</button></div>}
    <div className="board-context"><p>{active.description}</p><select aria-label="Flap 排行排序" value={sort} onChange={e=>{setSort(e.target.value as BoardSort);setOrder('desc');setCursor('')}}>{Object.entries(BOARD_SORTS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><button aria-label="切换排序方向" disabled={sort==='default'} onClick={()=>{setOrder(order==='desc'?'asc':'desc');setCursor('')}}>{order==='desc'?'↓ 降序':'↑ 升序'}</button></div>
    {error&&<div className="board-error" role="alert"><strong>分类数据暂不可用</strong><p>{error}</p><button onClick={()=>{setCursor('');setRefresh(n=>n+1)}}>重新读取</button><a href="https://flap.sh/board?lang=zh" target="_blank" rel="noreferrer">打开原站 ↗</a></div>}
    {loading&&!current?<div className="board-skeleton" role="status">正在读取 {active.label} 的真实数据…{[0,1,2,3].map(n=><div key={n}/>)}</div>:current&&<>
      {layout==='list'?<div className="product-table-scroll board-table-scroll" tabIndex={0} aria-label="代币行情表，可横向滚动"><table className="product-table board-table"><thead><tr><th>代币 / 阶段</th><th>价格</th><th>计价币</th>{sortable('marketcap','市值')}<th>买税 / 卖税</th>{sortable('volume24h','24H 成交额')}{sortable('holders','持有人')}{sortable('liquidity','流动性')}{sortable('5m','5M')}{sortable('1h','1H')}{sortable('4h','4H')}{sortable('24h','24H')}<th>操作</th></tr></thead><tbody>{rows.map(r=><tr key={r.address}><td><button className="board-identity" onClick={()=>setDetail(r)} aria-label={`查看 ${r.symbol} 合约`}><CoinImage row={r}/><span><strong>{r.symbol}{r.fac&&<em title="Flap FAC 标记">FAC</em>}</strong><small>{r.name||short(r.address)}</small><small>{r.listed===true?'已毕业':r.listed===false?`内盘 · ${r.progress===null?'进度未知':r.progress.toFixed(1)+'%'}`:'阶段未知'}</small></span></button></td><td>{usd(r.price)}</td><td><span className="board-quote">{quoteLabel(r)}</span></td><td>{usd(r.marketCap,true)}</td><td><button className="board-tax" onClick={()=>setDetail(r)}>{tax(r.buyTaxBps)} / {tax(r.sellTaxBps)}</button></td><td>{usd(r.volume24h,true)}</td><td>{num(r.holders)}</td><td>{usd(r.liquidity,true)}</td>{[r.change5m,r.change1h,r.change4h,r.change24h].map((v,i)=><td key={i}><Change value={v}/></td>)}<td>{actions(r)}</td></tr>)}</tbody></table></div>:<div className="board-grid">{rows.map(r=><article key={r.address} className="board-card"><div className="board-card-title"><CoinImage row={r}/><div><strong>{r.symbol}</strong><small>{r.name}</small></div><span className="board-stage">{r.fac?'FAC':r.listed===true?'已毕业':r.listed===false?'内盘':'未知'}</span></div><div className="board-price"><strong>{usd(r.price)}</strong><Change value={r.change24h}/></div><dl><div><dt>市值</dt><dd>{usd(r.marketCap,true)}</dd></div><div><dt>24H 成交额</dt><dd>{usd(r.volume24h,true)}</dd></div><div><dt>持有人</dt><dd>{num(r.holders)}</dd></div><div><dt>流动性</dt><dd>{usd(r.liquidity,true)}</dd></div><div><dt>计价币</dt><dd>{quoteLabel(r)}</dd></div><div><dt>买税 / 卖税</dt><dd>{tax(r.buyTaxBps)} / {tax(r.sellTaxBps)}</dd></div></dl>{r.listed===false&&r.progress!==null&&<div className="board-progress"><span style={{width:`${r.progress}%`}}/><small>内盘进度 {r.progress.toFixed(1)}%</small></div>}<div className="board-card-changes">{[['5M',r.change5m],['1H',r.change1h],['4H',r.change4h]].map(([label,v])=><span key={String(label)}>{label}<Change value={v as number|null}/></span>)}</div>{actions(r)}</article>)}</div>}
      {!rows.length&&<div className="product-empty"><strong>当前范围没有匹配代币</strong><p>试试其他分类或重置筛选。{current.nextCursor?'也可以加载更多。':''}</p></div>}
      {current.nextCursor&&loaded.length<400&&<button className="board-load-more" disabled={loading} onClick={()=>setCursor(current.nextCursor!)}>{loading?'加载中…':'加载更多代币 ↓'}</button>}
      <div className="board-source"><span className="board-live-dot"/><p>来源：<a href="https://flap.sh/board?lang=zh" target="_blank" rel="noreferrer">Flap</a> · 读取于 {new Date(current.fetchedAt).toLocaleTimeString('zh-CN')} · 显示 {rows.length} / 已加载 {loaded.length} 个{current.source==='page'?' · 公开页面备用数据':''}<br/>{current.sourceUpdatedAt&&`原站数据时间 ${new Date(current.sourceUpdatedAt).toLocaleString('zh-CN')}。`}{current.scope} 搜索、收藏、阶段及最低流动性筛选仅作用于已加载数据。</p></div>
    </>}
    {detail&&<ProductDialog title={`${detail.symbol} · 代币详情`} onClose={()=>setDetail(null)}><div className="board-detail-head"><CoinImage row={detail}/><div><h3>{detail.name}</h3><p>{detail.symbol} · BNB Chain</p></div></div><a className="board-address" href={`https://bscscan.com/token/${detail.address}`} target="_blank" rel="noreferrer">{detail.address} ↗</a><dl className="product-details"><div><dt>发行阶段</dt><dd>{detail.listed===true?'Flap 已毕业':detail.listed===false?'Flap 内盘':'未知'}</dd></div><div><dt>计价资产</dt><dd>{quoteLabel(detail)}</dd></div><div><dt>买入 / 卖出代币税</dt><dd>{tax(detail.buyTaxBps)} / {tax(detail.sellTaxBps)}</dd></div><div><dt>Flap FAC 标记</dt><dd>{detail.fac?'有 · 以 Flap 原站为准':'未返回认证标记'}</dd></div><div><dt>蝴蝶兑换服务费</dt><dd>另计 0.8% · 收费合约待上线</dd></div></dl><p className="swap-small-note">行情与税率由 Flap 返回，可能变化。收录和认证标记不代表资产安全。选择交易后仍须读取链上信息、核对合约并取得可用路由。</p><div className="board-detail-actions"><a href={original(detail.address)} target="_blank" rel="noreferrer">在 Flap 查看详情 ↗</a>{detail.listed===true&&onTrade&&<button className="swap-primary" onClick={()=>{onTrade(detail.address);setDetail(null)}}>选择此代币交易</button>}</div>{detail.listed!==true&&<p className="swap-small-note">此资产尚未确认毕业，请到 Flap 核对内盘状态。</p>}</ProductDialog>}
  </div>
}
