import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {decodeFunctionData} from 'viem';
import * as core from './snapshot0921-core.mjs';
import {isDue} from './snapshot0921-schedule.mjs';
import {runSlot} from './snapshot0921-chain.mjs';
const source=fs.readFileSync(new URL('./data/snapshot0921-recipients.txt',import.meta.url));
const manifest=JSON.parse(fs.readFileSync(new URL('./data/snapshot0921-manifest.json',import.meta.url)));
const prior=JSON.parse(fs.readFileSync(new URL('./data/snapshot0921-prior-image12.json',import.meta.url)));
core.configure(source,manifest.recipientSha256,prior);
test('5557 unique recipients, 28 batches, exact 0.7777 amounts and total',()=>{
 assert.equal(core.BATCHES,28);assert.equal(new Set(core.plan().flat()).size,5557);assert.ok(core.plan().slice(0,-1).every(b=>b.length===200));assert.equal(core.plan().at(-1).length,157);assert.equal(core.TOTAL,4321678900000000000000n);assert.equal(core.BASE_NONCE,250);assert.notEqual(core.ID,prior.id);
 for(let batch=0;batch<28;batch++){const d=decodeFunctionData({abi:core.artifact.abi,data:core.callFor({kind:'send',batch}).data});assert.deepEqual(d.args[2].map(x=>x.toLowerCase()),core.plan()[batch]);assert.ok(d.args[3].every(x=>x===777700000000000000n));}
 assert.throws(()=>core.configure(Buffer.concat([source,Buffer.from('bad')]),manifest.recipientSha256,prior));
});
test('cumulative budget boundary 0.3 BNB',()=>{assert.equal(core.BUDGET,300000000000000000n);assert.equal(core.reserve(core.BUDGET-21000n,21000n,1n),21000n);assert.throws(()=>core.reserve(core.BUDGET-20999n,21000n,1n));});
test('hourly wait crosses old 40 minute timeout without early sending',async()=>{let now=10000;let j={entries:[{kind:'send',settled:true,success:true,confirmedAt:10000}]};assert.equal(isDue(j,13599),false);assert.equal(isDue(j,13600),true);let executions=0;await runSlot({load:async()=>j,now:()=>now,sleep:async ms=>{now+=ms/1000;},log:()=>{},execute:async()=>{assert.ok(now>=13600);executions++;j.entries.push({kind:'send',settled:true,success:true,confirmedAt:now});}});assert.equal(executions,1);});
test('saving failure prevents broadcasting and uses deterministic recovery hash',async()=>{let sent=false;const entry={};await assert.rejects(core.persistThenBroadcast({journal:{},entry,raw:'0x1234',save:async()=>{throw Error('save failed');},broadcast:async()=>{sent=true;}}));assert.equal(sent,false);assert.match(entry.hash,/^0x[0-9a-f]{64}$/);});
test('live prior ledger must match all completed old campaigns',async()=>{const {assertPrior72}=await import('./snapshot0921-main.mjs');const read=n=>JSON.parse(fs.readFileSync(new URL('./data/'+n,import.meta.url)));const api=bad=>async(method,path)=>{assert.equal(method,'GET');let j=path.includes('72x200')?read('holders18-prior71.json'):path.includes('holders18-ledger')?read('image10-prior-holders18.json'):path.includes('image10-ledger')?read('image12-prior-image10.json'):bad?{...prior,active:true}:prior;let content=JSON.stringify(j);return {encoding:'base64',size:content.length,content:Buffer.from(content).toString('base64')};};await assertPrior72(api(false));await assert.rejects(assertPrior72(api(true)));});
test('new budget accounting accepts above 0.2, refuses above 0.3 and altered historical exclusion',async()=>{const {accountBudget,OWNED_RETURN}=await import('./snapshot0921-budget.mjs');const rows=[{...OWNED_RETURN,nonce:5},...Array.from({length:5},(_,nonce)=>({hash:'0x'+String(nonce+1).padStart(64,'0'),from:OWNED_RETURN.from,nonce,feeWei:'0',valueWei:'0',success:true})),{hash:'0x'+'a'.repeat(64),from:core.ACCOUNT,nonce:0,feeWei:'250000000000000000',valueWei:'0',success:true}];assert.equal(accountBudget(rows,true).spent,250001050000000000n);assert.throws(()=>accountBudget(rows.map(r=>r.from===core.ACCOUNT?{...r,feeWei:'300000000000000000'}:r),true));assert.throws(()=>accountBudget(rows,false));});
test('delivery validates gross 0.7777 and records taxed net without reissuing',async()=>{const {encodeEventTopics,encodeAbiParameters}=await import('viem');const {verifyDelivery}=await import('./snapshot0921-run.mjs');const args={sender:core.ACCOUNT,token:core.TOKEN,batchId:core.batchId(27)};const recipients=core.plan()[27];const logs=recipients.map((recipient,i)=>({address:core.DISTRIBUTOR,topics:encodeEventTopics({abi:core.artifact.abi,eventName:'Delivered',args}),data:encodeAbiParameters([{type:'address'},{type:'uint256'},{type:'uint256'}],[recipient,core.AMOUNT,i?core.AMOUNT:core.AMOUNT*97n/100n])}));logs.push({address:core.DISTRIBUTOR,topics:encodeEventTopics({abi:core.artifact.abi,eventName:'BatchCompleted',args}),data:encodeAbiParameters([{type:'uint256'},{type:'uint256'}],[157n,157n*core.AMOUNT])});assert.equal(verifyDelivery({kind:'send',batch:27},logs).length,157);assert.throws(()=>verifyDelivery({kind:'send',batch:26},logs));});
