export type Language = 'zh' | 'en'

type Step = { index: string; title: string; body: string }

export type SiteCopy = {
  nav: { participate: string; proof: string; story: string; languageLabel: string; languageSwitchLabel: string; menuOpenLabel: string; menuCloseLabel: string; menuLabel: string; closeLabel: string; homeLabel: string; logoLabel: string; navigationLabel: string }
  community: { regionLabel: string; xLabel: string; telegramLabel: string; comingSoon: string; xPendingLabel: string; telegramPendingLabel: string }
  ticker: { sectionLabel: string; symbolLabel: string; chainLabel: string; priceLabel: string; capacityLabel: string; statusLabel: string }
  hero: { eyebrow: string; statusLabel: string; tagline: string; description: string; quickFacts: Array<{ label: string; value: string }>; enterPresale: string; presalePendingLabel: string; mobilePresaleLabel: string; mobilePresaleMeta: string; mobileStatus: Record<'live' | 'paused' | 'ended' | 'soldOut' | 'participated' | 'unavailable', string>; visualLabel: string; visualTicker: string; posterLineOne: string; posterLineTwo: string; brandSignalLabel: string; brandSignalValue: string; safetyLabel: string }
  presale: { regionLabel: string; eyebrow: string; title: string; body: string; facts: string[]; actionLabel: string; unavailable: string; pendingLabel: string; warning: string; interaction: { loading: string; connectWallet: string; chooseWallet: string; confirm: string; disclosure: string; participants: string; raised: string; countdown: string; addressNote: string; soldOut: string; soldOutAction: string; paused: string; ended: string; alreadyParticipated: string; alreadyParticipatedAction: string; unavailable: string; rpcError: string; walletMissing: string; walletHeading: string; walletBody: string; walletMobileHint: string; walletConnectUnavailable: string; close: string; account: string; network: string; disconnect: string; copy: string; copied: string; wrongNetwork: string; waitingSignature: string; broadcast: string; confirming: string; confirmed: string; rejected: string; failed: string; uncertain: string; viewOnBscScan: string; retry: string; myParticipation: string; chainRecord: string; savedRecord: string; noRecord: string; distributionPending: string; submittedAt: string } }
  publicProof: { regionLabel: string; eyebrow: string; title: string; body: string; copy: string; copied: string; openExplorer: string; pending: string; presaleLabel: string; tokenLabel: string; recipientLabel: string; adminLabel: string; platformLabel: string; communityLabel: string; presaleNote: string; tokenNote: string; recipientNote: string; adminNote: string; platformValue: string; platformNote: string; communityNote: string }
  updates: { regionLabel: string; eyebrow: string; title: string; body: string; updatedLabel: string; updatedValue: string; items: Array<{ date: string; title: string; body: string }>; shareTitle: string; shareBody: string; shareButton: string; copyButton: string; copied: string; download: string; shareText: string }
  nameCore: { regionLabel: string; eyebrow: string; title: string; cards: Array<{ glyph: string; title: string; body: string }> }
  footer: { rights: string }
  effect: { regionLabel: string; eyebrow: string; title: string; body: string; steps: Step[] }
  signal: { regionLabel: string; eyebrow: string; title: string; disclaimer: string; metrics: Array<{ label: string; value: string; trend: string }> }
  roadmap: { regionLabel: string; eyebrow: string; title: string; phases: Array<{ code: string; title: string; body: string; status: string }>; caveat: string }
  manifesto: { regionLabel: string; eyebrow: string; title: string; body: string }
}

export const siteContent: Record<Language, SiteCopy> = {
  zh: {
    nav: { participate: '参与中心', proof: '公开信息', story: '四字内核', languageLabel: 'EN', languageSwitchLabel: '切换到英文', menuOpenLabel: '打开菜单', menuCloseLabel: '关闭菜单', menuLabel: '菜单', closeLabel: '收起', homeLabel: 'FLAP STOCK 首页', logoLabel: '蝴蝶股票 FLAP STOCK 标志', navigationLabel: '主导航' },
    community: { regionLabel: '社区入口', xLabel: 'X', telegramLabel: 'Telegram', comingSoon: '即将开放', xPendingLabel: 'X：即将开放', telegramPendingLabel: 'Telegram：即将开放' },
    ticker: { sectionLabel: 'FLAP STOCK 项目详情', symbolLabel: '代币', chainLabel: '网络', priceLabel: '单地址', capacityLabel: '上限', statusLabel: '代币合约' },
    hero: { eyebrow: '社区 MEME · BNB SMART CHAIN', statusLabel: '机制摘要', tagline: '振翅，让故事发生。', description: '蝴蝶股票是一个 BNB Chain 社区 Meme 项目。机制方案包含金库、QQQB 奖励分配与销毁，代币合约待公布。', quickFacts: [{ label: '金库', value: '资金分配' }, { label: 'QQQB', value: '奖励方案' }, { label: '销毁', value: '机制组成' }], enterPresale: '参与私募 · 0.05 BNB', presalePendingLabel: '私募尚未开放', mobilePresaleLabel: '进入蝴蝶股票参与中心', mobilePresaleMeta: 'BSC 主网 · 0.05 BNB', mobileStatus: { live: '私募进行中', paused: '私募已暂停', ended: '私募已结束', soldOut: '名额已满', participated: '当前地址已参与', unavailable: '链上状态暂不可用' }, visualLabel: '正在煽动翅膀的蝴蝶股票品牌头像', visualTicker: '蝴蝶股票 · 振翅 · 共鸣', posterLineOne: '一只蝴蝶', posterLineTwo: '一场共同叙事', brandSignalLabel: '了解代币机制', brandSignalValue: '开放私募', safetyLabel: 'Meme 项目 · 非金融产品' },
    presale: { regionLabel: '参与中心', eyebrow: '02 / PARTICIPATION CENTER', title: '连接、参与、查询，都在这里。', body: '先检查链上状态，再选择钱包。广播后会立即显示交易哈希；即使后续查询暂时失败，也不会误报为“没有发送”。', facts: ['BSC 主网（56）', '固定 0.05 BNB', '每地址仅一次', '北京时间 2026-09-09 23:59:59 截止'], actionLabel: '连接钱包参与', unavailable: '尚未开放', pendingLabel: '私募尚未开放', warning: '签名前请核对：BSC 主网、0.05 BNB，以及私募合约 0x409c9448172b0f244a6823e91ad669281294622b。', interaction: { loading: '正在读取链上状态', connectWallet: '选择并连接钱包', chooseWallet: '选择钱包', confirm: '确认支付 0.05 BNB', disclosure: '我已了解：获得的 蝴蝶股票 数量及发放时间尚未公布；由项目方后续人工发放；不退款；一地址一次不等于一人一次。', participants: '链上确认地址', raised: '链上确认金额', countdown: '距离截止', addressNote: '地址数不等于真实人数', soldOut: '10,000 个链上地址名额已满', soldOutAction: '名额已满', paused: '私募当前已暂停', ended: '本轮私募已经结束', alreadyParticipated: '当前地址已有链上参与记录', alreadyParticipatedAction: '当前地址已参与', unavailable: '链上状态暂不可用', rpcError: '暂时无法获取链上数据', walletMissing: '当前浏览器未检测到钱包', walletHeading: '选择 BSC 钱包', walletBody: '选择当前浏览器检测到的钱包，并确认网络为 BSC 主网。', walletMobileHint: '手机用户可在 MetaMask、Trust Wallet 等钱包 App 的内置浏览器中打开 hudiegupiao.com。', walletConnectUnavailable: '扫码连接尚未配置，当前只展示真实检测到的钱包。', close: '关闭', account: '当前地址', network: '网络', disconnect: '断开', copy: '复制', copied: '已复制', wrongNetwork: '需要切换到 BSC 主网（56）', waitingSignature: '等待钱包签名：当前尚未广播', broadcast: '交易已广播', confirming: '等待链上确认', confirmed: '链上已确认参与成功', rejected: '你已在钱包中取消，本次没有广播', failed: '交易失败，可核对原因后重试', uncertain: '交易已广播，但暂时无法获取最终结果；请用哈希查询链上记录', viewOnBscScan: '在 BscScan 查看', retry: '重新检查', myParticipation: '我的参与', chainRecord: '链上记录', savedRecord: '本机最近交易', noRecord: '当前地址还没有可查询的参与记录', distributionPending: '蝴蝶股票 发放状态：等待项目方后续人工发放', submittedAt: '提交时间' } },
    publicProof: { regionLabel: '项目公开信息', eyebrow: '04 / PUBLIC PROOF', title: '承诺要能被查看，地址要能被核对。', body: '私募合约、收款与管理员地址集中展示；未公布的信息与私募合约明确分开。', copy: '复制', copied: '已复制', openExplorer: 'BscScan 查看', pending: '尚未公布', presaleLabel: '私募合约', tokenLabel: '蝴蝶股票 代币合约', recipientLabel: 'BNB 收款地址', adminLabel: '私募管理员', platformLabel: '发行平台关系', communityLabel: '官方社区', presaleNote: '用于固定 0.05 BNB 参与和链上记录。', tokenNote: '不要把私募合约误认为代币合约。', recipientNote: '私募合约收到 BNB 后转入此地址。', adminNote: '可暂停、恢复及调整结束时间；固定金额与上限不变。', platformValue: 'flap.sh · 项目链接待公布', platformNote: '计划使用的发行平台；蝴蝶股票并非平台官方项目。', communityNote: 'X 与 Telegram 真实链接尚未提供。' },
    updates: { regionLabel: '项目进展与分享', eyebrow: '05 / KEEP THE SIGNAL', title: '先验证，再分享；有进展，就留下记录。', body: '这里仅记录已经完成或可验证的事项。官方社区尚未开放前，可保存官网与品牌头像。', updatedLabel: '最近更新', updatedValue: '2026-09-06', items: [{ date: '09.06', title: '参与中心 V2', body: '整合钱包状态、交易反馈、我的参与与链上信息。' }, { date: '09.03', title: 'BSC 私募开放', body: '固定 0.05 BNB、每地址一次、最多 10,000 个地址。' }, { date: '09.02', title: '蝴蝶股票品牌上线', body: '确定 FLAP STOCK、荧光绿与紫色视觉，以及社区 Meme 定位。' }], shareTitle: '把正确的信息扇出去', shareBody: '分享链接包含来源参数，方便后续判断有效传播渠道。', shareButton: '系统分享', copyButton: '复制官网与介绍', copied: '分享内容已复制', download: '下载官方头像', shareText: '蝴蝶股票 FLAP STOCK 正在 BSC 开放私募：固定 0.05 BNB，每地址一次。在官网连接钱包，查看参与状态。' },
    nameCore: { regionLabel: '蝴蝶股票四字内核', eyebrow: '06 / BRAND STORY', title: '为什么叫蝴蝶股票？', cards: [{ glyph: '蝴', title: '微小起点', body: '微小的起点，也能带来改变。' }, { glyph: '蝶', title: '共同蜕变', body: '因共同兴趣相聚，让故事生长。' }, { glyph: '股', title: '共同叙事', body: '社区共同参与的叙事。' }, { glyph: '票', title: '入场凭证', body: '加入这段 Meme 故事的入口。' }] },
    footer: { rights: '© 2026 蝴蝶股票 · FLAP STOCK' },
    effect: { regionLabel: '蝴蝶效应', eyebrow: 'BUTTERFLY EFFECT', title: '一点点动静，也能掀起大风暴。', body: '每一次参与与分享都可能成为新的信号。', steps: [] }, signal: { regionLabel: 'Meme 信号终端', eyebrow: 'MEME SIGNAL', title: '看看翅膀。', disclaimer: '仅供娱乐，非金融数据。', metrics: [] }, roadmap: { regionLabel: '路线图', eyebrow: 'FLIGHT PATH', title: '飞行轨迹', phases: [], caveat: '以官方公告为准。' }, manifesto: { regionLabel: '社区宣言', eyebrow: 'MANIFESTO', title: '不预测风口，我们把风扇起来。', body: '一万只蝴蝶，就是风暴。' },
  },
  en: {
    nav: { participate: 'JOIN', proof: 'PUBLIC PROOF', story: 'BRAND STORY', languageLabel: '中文', languageSwitchLabel: 'Switch to Chinese', menuOpenLabel: 'Open menu', menuCloseLabel: 'Close menu', menuLabel: 'MENU', closeLabel: 'CLOSE', homeLabel: 'FLAP STOCK home', logoLabel: 'FLAP STOCK logo', navigationLabel: 'Primary navigation' },
    community: { regionLabel: 'Community channels', xLabel: 'X', telegramLabel: 'Telegram', comingSoon: 'COMING SOON', xPendingLabel: 'X: COMING SOON', telegramPendingLabel: 'Telegram: COMING SOON' },
    ticker: { sectionLabel: 'FLAP STOCK project details', symbolLabel: 'TOKEN', chainLabel: 'CHAIN', priceLabel: 'PER ADDRESS', capacityLabel: 'CAP', statusLabel: 'TOKEN CONTRACT' },
    hero: { eyebrow: 'COMMUNITY MEME · BNB SMART CHAIN', statusLabel: 'MECHANISM SUMMARY', tagline: '蝴蝶股票. LET THE STORY BEGIN.', description: 'FLAP STOCK is a community Meme project on BNB Chain. Its proposed mechanism includes a treasury, QQQB rewards and burning. The token contract is not yet announced.', quickFacts: [{ label: 'TREASURY', value: 'Fund allocation' }, { label: 'QQQB', value: 'Reward plan' }, { label: 'BURN', value: 'Token mechanism' }], enterPresale: 'JOIN PRIVATE SALE · 0.05 BNB', presalePendingLabel: 'PRIVATE SALE COMING SOON', mobilePresaleLabel: 'Enter the FLAP STOCK participation center', mobilePresaleMeta: 'BSC MAINNET · 0.05 BNB', mobileStatus: { live: 'PRIVATE SALE LIVE', paused: 'PRIVATE SALE PAUSED', ended: 'PRIVATE SALE ENDED', soldOut: 'SOLD OUT', participated: 'ADDRESS PARTICIPATED', unavailable: 'CHAIN DATA UNAVAILABLE' }, visualLabel: 'Animated FLAP STOCK butterfly avatar', visualTicker: '蝴蝶股票 · COMMUNITY', posterLineOne: 'ONE BUTTERFLY', posterLineTwo: 'ONE SHARED STORY', brandSignalLabel: 'EXPLORE TOKENOMICS', brandSignalValue: 'PRIVATE SALE LIVE', safetyLabel: 'MEME PROJECT · NOT A FINANCIAL PRODUCT' },
    presale: { regionLabel: 'Participation Center', eyebrow: '02 / PARTICIPATION CENTER', title: 'Connect, participate, and check in one place.', body: 'The site checks chain state before sending. A transaction hash appears as soon as it is broadcast; a later RPC issue will never be mislabeled as “not sent.”', facts: ['BSC MAINNET (56)', 'FIXED 0.05 BNB', 'ONE PARTICIPATION PER ADDRESS', 'DEADLINE: 2026-09-09 23:59:59 BEIJING TIME'], actionLabel: 'CONNECT WALLET TO JOIN', unavailable: 'UNAVAILABLE', pendingLabel: 'PRIVATE SALE COMING SOON', warning: 'Before signing, verify BSC mainnet, 0.05 BNB, and presale contract 0x409c9448172b0f244a6823e91ad669281294622b.', interaction: { loading: 'READING CHAIN STATE', connectWallet: 'CHOOSE & CONNECT WALLET', chooseWallet: 'CHOOSE WALLET', confirm: 'CONFIRM 0.05 BNB PAYMENT', disclosure: 'I understand: the 蝴蝶股票 amount and distribution schedule are not announced; 蝴蝶股票 will be distributed manually; there are no refunds; one-address-once does not mean one-person-once.', participants: 'CONFIRMED ADDRESSES', raised: 'CONFIRMED BNB', countdown: 'TIME LEFT', addressNote: 'Addresses are not unique people', soldOut: 'THE 10,000-ADDRESS CAP IS FULL', soldOutAction: 'SOLD OUT', paused: 'PRIVATE SALE IS PAUSED', ended: 'PRIVATE SALE HAS ENDED', alreadyParticipated: 'THIS ADDRESS HAS AN ON-CHAIN PARTICIPATION RECORD', alreadyParticipatedAction: 'ADDRESS PARTICIPATED', unavailable: 'CHAIN STATE UNAVAILABLE', rpcError: 'CHAIN DATA TEMPORARILY UNAVAILABLE', walletMissing: 'NO WALLET DETECTED IN THIS BROWSER', walletHeading: 'CHOOSE A BSC WALLET', walletBody: 'Choose a detected browser wallet and confirm BSC mainnet.', walletMobileHint: 'On mobile, open hudiegupiao.com inside the browser in MetaMask, Trust Wallet, or another compatible wallet app.', walletConnectUnavailable: 'QR connection is not configured. Only genuinely detected wallets are shown.', close: 'CLOSE', account: 'ACCOUNT', network: 'NETWORK', disconnect: 'DISCONNECT', copy: 'COPY', copied: 'COPIED', wrongNetwork: 'SWITCH REQUIRED: BSC MAINNET (56)', waitingSignature: 'WAITING FOR WALLET SIGNATURE — NOT BROADCAST YET', broadcast: 'TRANSACTION BROADCAST', confirming: 'WAITING FOR ON-CHAIN CONFIRMATION', confirmed: 'PARTICIPATION CONFIRMED ON-CHAIN', rejected: 'CANCELLED IN WALLET — NOTHING WAS BROADCAST', failed: 'TRANSACTION FAILED — REVIEW THE REASON AND RETRY', uncertain: 'BROADCAST SUCCEEDED, BUT THE FINAL RESULT IS TEMPORARILY UNAVAILABLE. CHECK THE HASH ON-CHAIN.', viewOnBscScan: 'VIEW ON BSCSCAN', retry: 'CHECK AGAIN', myParticipation: 'MY PARTICIPATION', chainRecord: 'ON-CHAIN RECORD', savedRecord: 'LATEST SAVED TRANSACTION', noRecord: 'NO PARTICIPATION RECORD IS AVAILABLE FOR THIS ADDRESS', distributionPending: '蝴蝶股票 DISTRIBUTION: WAITING FOR MANUAL DISTRIBUTION', submittedAt: 'SUBMITTED' } },
    publicProof: { regionLabel: 'Public Project Information', eyebrow: '04 / PUBLIC PROOF', title: 'Claims should be inspectable. Addresses should be verifiable.', body: 'The presale contract, recipient and admin are grouped here. Unknown information is kept clearly separate from the presale contract.', copy: 'COPY', copied: 'COPIED', openExplorer: 'VIEW ON BSCSCAN', pending: 'NOT ANNOUNCED', presaleLabel: 'PRIVATE SALE CONTRACT', tokenLabel: '蝴蝶股票 TOKEN CONTRACT', recipientLabel: 'BNB RECIPIENT', adminLabel: 'PRIVATE SALE ADMIN', platformLabel: 'LAUNCH PLATFORM RELATION', communityLabel: 'OFFICIAL COMMUNITY', presaleNote: 'Fixed 0.05 BNB participation and on-chain records.', tokenNote: 'Do not mistake the presale contract for a token contract.', recipientNote: 'BNB received by the presale contract is forwarded here.', adminNote: 'Can pause, resume, and update the end time; fixed amount and cap stay unchanged.', platformValue: 'flap.sh · PROJECT LINK PENDING', platformNote: 'Planned launch platform. FLAP STOCK is not an official platform project.', communityNote: 'Real X and Telegram links have not been supplied.' },
    updates: { regionLabel: 'Project Updates and Sharing', eyebrow: '05 / KEEP THE SIGNAL', title: 'Verify first. Share second. Record real progress.', body: 'Only completed or verifiable milestones appear here. Until official community links open, save the site and the brand avatar.', updatedLabel: 'LAST UPDATED', updatedValue: '2026-09-06', items: [{ date: 'SEP 06', title: 'PARTICIPATION CENTER V2', body: 'Wallet state, transaction feedback, personal records, and on-chain information in one place.' }, { date: 'SEP 03', title: 'BSC PRIVATE SALE OPEN', body: 'Fixed 0.05 BNB, one entry per address, up to 10,000 addresses.' }, { date: 'SEP 02', title: 'FLAP STOCK BRAND LIVE', body: 'FLAP STOCK, acid-lime and purple identity, and community Meme positioning established.' }], shareTitle: '蝴蝶股票 THE RIGHT INFORMATION', shareBody: 'The share link includes source parameters so future campaigns can be measured.', shareButton: 'SYSTEM SHARE', copyButton: 'COPY SITE & INTRO', copied: 'SHARE TEXT COPIED', download: 'DOWNLOAD OFFICIAL AVATAR', shareText: 'FLAP STOCK presale is live on BSC: fixed 0.05 BNB, one participation per address. Connect your wallet on the site to check participation status.' },
    nameCore: { regionLabel: 'FLAP STOCK Character Core', eyebrow: '06 / BRAND STORY', title: 'WHY FLAP STOCK?', cards: [{ glyph: '蝴', title: 'A TINY START', body: 'Small beginnings can bring change.' }, { glyph: '蝶', title: 'SHARED CHANGE', body: 'Shared interests bring us together.' }, { glyph: '股', title: 'A SHARED STORY', body: 'A story shaped by its community.' }, { glyph: '票', title: 'A MEME ENTRY', body: 'An entry into a shared Meme story.' }] },
    footer: { rights: '© 2026 蝴蝶股票 · FLAP STOCK' },
    effect: { regionLabel: 'The Butterfly Effect', eyebrow: 'BUTTERFLY EFFECT', title: 'A tiny move can start a giant storm.', body: 'Every entry and share can become a new signal.', steps: [] }, signal: { regionLabel: 'Meme Signal Terminal', eyebrow: 'MEME SIGNAL', title: 'Watch the wings.', disclaimer: 'For entertainment only. Not financial data.', metrics: [] }, roadmap: { regionLabel: 'Roadmap', eyebrow: 'FLIGHT PATH', title: 'Flight path', phases: [], caveat: 'Subject to official announcements.' }, manifesto: { regionLabel: 'Community Manifesto', eyebrow: 'MANIFESTO', title: 'We do not predict the wind. We flap it into motion.', body: 'Ten thousand butterflies make a storm.' },
  },
}
