export type Language = 'zh' | 'en'

type Card = { label: string; value: string; detail: string; status?: 'known' | 'pending' }
type Step = { index: string; title: string; body: string }

export type SiteCopy = {
  nav: { rules: string; participate: string; proof: string; story: string; languageLabel: string; languageSwitchLabel: string; menuOpenLabel: string; menuCloseLabel: string; menuLabel: string; closeLabel: string; homeLabel: string; logoLabel: string; navigationLabel: string }
  community: { regionLabel: string; xLabel: string; telegramLabel: string; comingSoon: string; xPendingLabel: string; telegramPendingLabel: string }
  ticker: { sectionLabel: string; symbolLabel: string; chainLabel: string; priceLabel: string; capacityLabel: string; statusLabel: string }
  hero: { eyebrow: string; statusLabel: string; tagline: string; description: string; quickFacts: Array<{ label: string; value: string }>; explore: string; enterPresale: string; presalePendingLabel: string; mobilePresaleLabel: string; mobilePresaleMeta: string; mobileStatus: Record<'live' | 'paused' | 'ended' | 'soldOut' | 'participated' | 'unavailable', string>; visualLabel: string; visualTicker: string; posterLineOne: string; posterLineTwo: string; brandSignalLabel: string; brandSignalValue: string; safetyLabel: string }
  participationRules: { regionLabel: string; eyebrow: string; title: string; body: string; cards: Card[]; pendingLabel: string; leaderNote: string; meaningNote: string }
  presale: { regionLabel: string; eyebrow: string; title: string; body: string; facts: string[]; actionLabel: string; unavailable: string; pendingLabel: string; warning: string; interaction: { loading: string; connectWallet: string; chooseWallet: string; confirm: string; disclosure: string; participants: string; raised: string; countdown: string; addressNote: string; soldOut: string; soldOutAction: string; paused: string; ended: string; alreadyParticipated: string; alreadyParticipatedAction: string; unavailable: string; rpcError: string; walletMissing: string; walletHeading: string; walletBody: string; walletMobileHint: string; walletConnectUnavailable: string; close: string; account: string; network: string; disconnect: string; copy: string; copied: string; wrongNetwork: string; waitingSignature: string; broadcast: string; confirming: string; confirmed: string; rejected: string; failed: string; uncertain: string; viewOnBscScan: string; retry: string; myParticipation: string; chainRecord: string; savedRecord: string; noRecord: string; distributionPending: string; submittedAt: string } }
  howTo: { regionLabel: string; eyebrow: string; title: string; steps: Step[] }
  publicProof: { regionLabel: string; eyebrow: string; title: string; body: string; copy: string; copied: string; openExplorer: string; pending: string; presaleLabel: string; tokenLabel: string; recipientLabel: string; adminLabel: string; platformLabel: string; communityLabel: string; presaleNote: string; tokenNote: string; recipientNote: string; adminNote: string; platformValue: string; platformNote: string; communityNote: string }
  updates: { regionLabel: string; eyebrow: string; title: string; body: string; updatedLabel: string; updatedValue: string; items: Array<{ date: string; title: string; body: string }>; shareTitle: string; shareBody: string; shareButton: string; copyButton: string; copied: string; download: string; shareText: string }
  nameCore: { regionLabel: string; eyebrow: string; title: string; cards: Array<{ glyph: string; title: string; body: string }>; disclaimer: string }
  faq: { regionLabel: string; eyebrow: string; title: string; items: Array<{ question: string; answer: string }> }
  footer: { disclaimer: string; rights: string }
  effect: { regionLabel: string; eyebrow: string; title: string; body: string; steps: Step[] }
  signal: { regionLabel: string; eyebrow: string; title: string; disclaimer: string; metrics: Array<{ label: string; value: string; trend: string }> }
  roadmap: { regionLabel: string; eyebrow: string; title: string; phases: Array<{ code: string; title: string; body: string; status: string }>; caveat: string }
  manifesto: { regionLabel: string; eyebrow: string; title: string; body: string }
}

export const siteContent: Record<Language, SiteCopy> = {
  zh: {
    nav: { rules: '参与规则', participate: '参与中心', proof: '公开信息', story: '四字内核', languageLabel: 'EN', languageSwitchLabel: '切换到英文', menuOpenLabel: '打开菜单', menuCloseLabel: '关闭菜单', menuLabel: '菜单', closeLabel: '收起', homeLabel: 'FLAP STOCK 首页', logoLabel: '蝴蝶股票 FLAP STOCK 标志', navigationLabel: '主导航' },
    community: { regionLabel: '社区入口', xLabel: 'X', telegramLabel: 'Telegram', comingSoon: '即将开放', xPendingLabel: 'X：即将开放', telegramPendingLabel: 'Telegram：即将开放' },
    ticker: { sectionLabel: 'FLAP STOCK 项目详情', symbolLabel: '代币', chainLabel: '网络', priceLabel: '单地址', capacityLabel: '上限', statusLabel: '状态' },
    hero: { eyebrow: '社区 MEME · BNB SMART CHAIN', statusLabel: '预售正在进行', tagline: '看懂规则，再振翅。', description: '蝴蝶股票是一个社区 Meme 代币项目。“股票”是品牌隐喻，不代表股权、证券或收益权。当前预售固定每地址 0.05 BNB。', quickFacts: [{ label: '固定参与金额', value: '0.05 BNB' }, { label: '链上限制', value: '一地址一次' }, { label: '预售截止', value: '09.09 · 23:59' }], explore: '先看完整参与规则', enterPresale: '进入参与中心', presalePendingLabel: '预售尚未开放', mobilePresaleLabel: '进入蝴蝶股票参与中心', mobilePresaleMeta: 'BSC 主网 · 0.05 BNB', mobileStatus: { live: '预售进行中', paused: '预售已暂停', ended: '预售已结束', soldOut: '名额已满', participated: '当前地址已参与', unavailable: '链上状态暂不可用' }, visualLabel: '正在煽动翅膀的蝴蝶股票品牌头像', visualTicker: '$FLAP · 先看懂 · 再振翅', posterLineOne: '一只蝴蝶', posterLineTwo: '一场共同叙事', brandSignalLabel: '当前阶段', brandSignalValue: '开放预售', safetyLabel: 'Meme 项目 · 非金融产品' },
    participationRules: { regionLabel: '参与规则', eyebrow: '01 / KNOW BEFORE YOU FLAP', title: '付款之前，这些必须看懂。', body: '已确认的链上条件直接展示；尚未决定的代币与资金信息明确标为“官方未公布”，不会用模糊口号替代。', pendingLabel: '官方未公布', cards: [{ label: '每地址支付', value: '0.05 BNB', detail: 'BSC 主网；合约固定金额。' }, { label: '获得 FLAP 数量', value: '官方未公布', detail: '数量或计算公式公布前，请勿自行推算。', status: 'pending' }, { label: '发放方式', value: '预售后人工发放', detail: '具体开始与完成时间尚未公布。' }, { label: '总量与分配', value: '官方未公布', detail: '总供应量、预售、团队与流动性份额尚未发布。', status: 'pending' }, { label: '募集资金用途', value: '官方未公布', detail: '加池、运营、开发等比例尚未发布。', status: 'pending' }, { label: '退款规则', value: '不退款', detail: '签名前请确认金额、网络与合约。' }], leaderNote: '团队长 0.2 BNB 档位目前未开放；当前合约只接受固定 0.05 BNB，官网不会提供无链上支持的按钮。', meaningNote: '“蝴蝶股票”是 Meme 品牌名称，不代表公司股票、股权、证券、分红、收益权或价格承诺。' },
    presale: { regionLabel: '参与中心', eyebrow: '02 / PARTICIPATION CENTER', title: '连接、参与、查询，都在这里。', body: '先检查链上状态，再选择钱包。广播后会立即显示交易哈希；即使后续查询暂时失败，也不会误报为“没有发送”。', facts: ['BSC 主网（56）', '固定 0.05 BNB', '每地址仅一次', '最多 10,000 个地址', '北京时间 2026-09-09 23:59:59 截止', '预售后人工发放 FLAP', '不退款'], actionLabel: '连接钱包参与', unavailable: '尚未开放', pendingLabel: '预售尚未开放', warning: '签名前请核对：BSC 主网、0.05 BNB，以及预售合约 0x409c9448172b0f244a6823e91ad669281294622b。', interaction: { loading: '正在读取链上状态', connectWallet: '选择并连接钱包', chooseWallet: '选择钱包', confirm: '确认支付 0.05 BNB', disclosure: '我已了解：获得的 FLAP 数量及发放时间尚未公布；由项目方后续人工发放；不退款；一地址一次不等于一人一次。', participants: '链上确认地址', raised: '链上确认金额', countdown: '距离截止', addressNote: '地址数不等于真实人数', soldOut: '10,000 个链上地址名额已满', soldOutAction: '名额已满', paused: '预售当前已暂停', ended: '本轮预售已经结束', alreadyParticipated: '当前地址已有链上参与记录', alreadyParticipatedAction: '当前地址已参与', unavailable: '链上状态暂不可用', rpcError: '暂时无法获取链上数据', walletMissing: '当前浏览器未检测到钱包', walletHeading: '选择 BSC 钱包', walletBody: '选择当前浏览器检测到的钱包，并确认网络为 BSC 主网。', walletMobileHint: '手机用户可在 MetaMask、Trust Wallet 等钱包 App 的内置浏览器中打开 hudiegupiao.com。', walletConnectUnavailable: '扫码连接尚未配置，当前只展示真实检测到的钱包。', close: '关闭', account: '当前地址', network: '网络', disconnect: '断开', copy: '复制', copied: '已复制', wrongNetwork: '需要切换到 BSC 主网（56）', waitingSignature: '等待钱包签名：当前尚未广播', broadcast: '交易已广播', confirming: '等待链上确认', confirmed: '链上已确认参与成功', rejected: '你已在钱包中取消，本次没有广播', failed: '交易失败，可核对原因后重试', uncertain: '交易已广播，但暂时无法获取最终结果；请用哈希查询链上记录', viewOnBscScan: '在 BscScan 查看', retry: '重新检查', myParticipation: '我的参与', chainRecord: '链上记录', savedRecord: '本机最近交易', noRecord: '当前地址还没有可查询的参与记录', distributionPending: 'FLAP 发放状态：等待项目方后续人工发放', submittedAt: '提交时间' } },
    howTo: { regionLabel: '参与步骤', eyebrow: '03 / HOW TO JOIN', title: '三步参与，状态一路可查。', steps: [{ index: '01', title: '准备钱包与 BNB', body: '使用 BSC 主网钱包，准备 0.05 BNB 和少量网络费。' }, { index: '02', title: '核对规则并签名', body: '确认网络、金额、预售合约和不退款规则，再在钱包中签名。' }, { index: '03', title: '保存并查询记录', body: '广播后官网立即显示哈希；连接同一地址可查看链上参与与本机最近交易。' }] },
    publicProof: { regionLabel: '项目公开信息', eyebrow: '04 / PUBLIC PROOF', title: '承诺要能被查看，地址要能被核对。', body: '预售合约、收款与管理员地址集中展示；未公布的信息与预售合约明确分开。', copy: '复制', copied: '已复制', openExplorer: 'BscScan 查看', pending: '尚未公布', presaleLabel: '预售合约', tokenLabel: 'FLAP 代币合约', recipientLabel: 'BNB 收款地址', adminLabel: '预售管理员', platformLabel: '发行平台关系', communityLabel: '官方社区', presaleNote: '用于固定 0.05 BNB 参与和链上记录。', tokenNote: '不要把预售合约误认为代币合约。', recipientNote: '预售合约收到 BNB 后转入此地址。', adminNote: '可暂停、恢复及调整结束时间；固定金额与上限不变。', platformValue: 'flap.sh · 项目链接待公布', platformNote: '计划使用的发行平台；蝴蝶股票并非平台官方项目。', communityNote: 'X 与 Telegram 真实链接尚未提供。' },
    updates: { regionLabel: '项目进展与分享', eyebrow: '05 / KEEP THE SIGNAL', title: '先验证，再分享；有进展，就留下记录。', body: '这里仅记录已经完成或可验证的事项。官方社区尚未开放前，可保存官网与品牌头像。', updatedLabel: '最近更新', updatedValue: '2026-09-06', items: [{ date: '09.06', title: '参与中心 V2', body: '重排参与规则、钱包状态、交易反馈、我的参与与链上证明。' }, { date: '09.03', title: 'BSC 预售开放', body: '固定 0.05 BNB、每地址一次、最多 10,000 个地址。' }, { date: '09.02', title: '蝴蝶股票品牌上线', body: '确定 FLAP STOCK、荧光绿与紫色视觉，以及社区 Meme 定位。' }], shareTitle: '把正确的信息扇出去', shareBody: '分享链接包含来源参数，方便后续判断有效传播渠道。', shareButton: '系统分享', copyButton: '复制官网与介绍', copied: '分享内容已复制', download: '下载官方头像', shareText: '蝴蝶股票 FLAP STOCK 正在 BSC 开放预售：固定 0.05 BNB，每地址一次。参与前请先阅读完整规则。' },
    nameCore: { regionLabel: '蝴蝶股票四字内核', eyebrow: '06 / BRAND STORY', title: '四个字，一套完整的 Meme 记忆。', cards: [{ glyph: '蝴', title: '微小起点', body: '一只蝴蝶，也能改变风的路径。' }, { glyph: '蝶', title: '共同蜕变', body: '从围观者，变成真正的参与者。' }, { glyph: '股', title: '共同叙事', body: '不是公司股份，而是社区一起持有的注意力。' }, { glyph: '票', title: '入场凭证', body: '一张 Meme 世界的票，不是证券或收益凭证。' }], disclaimer: '“股”和“票”只属于 Meme 品牌叙事，不代表真实股权、股票、证券、分红或任何收益权利。' },
    faq: { regionLabel: '常见问题', eyebrow: '07 / FAQ', title: '参与前，再确认一遍。', items: [{ question: '0.05 BNB 能得到多少 FLAP？', answer: '官方尚未公布具体数量或计算公式。请在该信息正式公布后再自行判断是否参与。' }, { question: '什么时候收到 FLAP？', answer: '预售后由项目方人工发放，具体开始、完成时间和查询方式尚未公布。' }, { question: '为什么不能支付 0.2 BNB？', answer: '当前预售合约只支持每地址固定 0.05 BNB。团队长 0.2 BNB 档位未开放。' }, { question: '“股票”是不是公司股份？', answer: '不是。蝴蝶股票是 Meme 品牌名称，不代表任何股权、证券、分红或收益权。' }, { question: '交易广播后页面查询失败怎么办？', answer: '保留页面显示的交易哈希，并通过 BscScan 查询真实链上结果。链上记录优先于页面临时状态。' }, { question: '规则后续会变化吗？', answer: '管理员可按合约权限暂停、恢复或调整结束时间；任何项目计划变化应以官网和后续官方公告为准。' }] },
    footer: { disclaimer: 'FLAP 是纯社区 Meme 代币，不是真实股票、证券、投资产品或收益承诺。参与前请独立判断并核对链上信息。', rights: '© 2026 蝴蝶股票 · FLAP STOCK' },
    effect: { regionLabel: '蝴蝶效应', eyebrow: 'BUTTERFLY EFFECT', title: '一点点动静，也能掀起大风暴。', body: '每一次参与与分享都可能成为新的信号。', steps: [] }, signal: { regionLabel: 'Meme 信号终端', eyebrow: 'MEME SIGNAL', title: '看看翅膀。', disclaimer: '仅供娱乐，非金融数据。', metrics: [] }, roadmap: { regionLabel: '路线图', eyebrow: 'FLIGHT PATH', title: '飞行轨迹', phases: [], caveat: '以官方公告为准。' }, manifesto: { regionLabel: '社区宣言', eyebrow: 'MANIFESTO', title: '不预测风口，我们把风扇起来。', body: '一万只蝴蝶，就是风暴。' },
  },
  en: {
    nav: { rules: 'RULES', participate: 'JOIN', proof: 'PUBLIC PROOF', story: 'BRAND STORY', languageLabel: '中文', languageSwitchLabel: 'Switch to Chinese', menuOpenLabel: 'Open menu', menuCloseLabel: 'Close menu', menuLabel: 'MENU', closeLabel: 'CLOSE', homeLabel: 'FLAP STOCK home', logoLabel: 'FLAP STOCK logo', navigationLabel: 'Primary navigation' },
    community: { regionLabel: 'Community channels', xLabel: 'X', telegramLabel: 'Telegram', comingSoon: 'COMING SOON', xPendingLabel: 'X: COMING SOON', telegramPendingLabel: 'Telegram: COMING SOON' },
    ticker: { sectionLabel: 'FLAP STOCK project details', symbolLabel: 'TOKEN', chainLabel: 'CHAIN', priceLabel: 'PER ADDRESS', capacityLabel: 'CAP', statusLabel: 'STATUS' },
    hero: { eyebrow: 'COMMUNITY MEME · BNB SMART CHAIN', statusLabel: 'PRESALE IS LIVE', tagline: 'KNOW THE RULES. THEN FLAP.', description: 'FLAP STOCK is a community Meme token. “Stock” is a brand metaphor—not equity, a security, or a right to returns. Presale entry is fixed at 0.05 BNB per address.', quickFacts: [{ label: 'FIXED ENTRY', value: '0.05 BNB' }, { label: 'ON-CHAIN LIMIT', value: 'ONE ADDRESS ONCE' }, { label: 'DEADLINE', value: 'SEP 09 · 23:59' }], explore: 'READ ALL PARTICIPATION RULES', enterPresale: 'ENTER PARTICIPATION CENTER', presalePendingLabel: 'PRESALE COMING SOON', mobilePresaleLabel: 'Enter the FLAP STOCK participation center', mobilePresaleMeta: 'BSC MAINNET · 0.05 BNB', mobileStatus: { live: 'PRESALE LIVE', paused: 'PRESALE PAUSED', ended: 'PRESALE ENDED', soldOut: 'SOLD OUT', participated: 'ADDRESS PARTICIPATED', unavailable: 'CHAIN DATA UNAVAILABLE' }, visualLabel: 'Animated FLAP STOCK butterfly avatar', visualTicker: '$FLAP · KNOW IT · THEN FLAP', posterLineOne: 'ONE BUTTERFLY', posterLineTwo: 'ONE SHARED STORY', brandSignalLabel: 'CURRENT STAGE', brandSignalValue: 'PRESALE LIVE', safetyLabel: 'MEME PROJECT · NOT A FINANCIAL PRODUCT' },
    participationRules: { regionLabel: 'Participation Rules', eyebrow: '01 / KNOW BEFORE YOU FLAP', title: 'Understand this before you pay.', body: 'Confirmed on-chain terms are stated directly. Token and treasury information that has not been decided is marked “NOT ANNOUNCED”—never replaced with vague hype.', pendingLabel: 'NOT ANNOUNCED', cards: [{ label: 'PAYMENT PER ADDRESS', value: '0.05 BNB', detail: 'BSC mainnet; fixed by the contract.' }, { label: 'FLAP RECEIVED', value: 'NOT ANNOUNCED', detail: 'Do not infer an amount before an official formula is published.', status: 'pending' }, { label: 'DISTRIBUTION', value: 'MANUAL AFTER PRESALE', detail: 'Start and completion times are not announced.' }, { label: 'SUPPLY & ALLOCATION', value: 'NOT ANNOUNCED', detail: 'Presale, team and liquidity allocations are not published.', status: 'pending' }, { label: 'USE OF BNB', value: 'NOT ANNOUNCED', detail: 'Liquidity, operations and development ratios are not published.', status: 'pending' }, { label: 'REFUNDS', value: 'NO REFUNDS', detail: 'Verify the amount, network and contract before signing.' }], leaderNote: 'The 0.2 BNB team-leader tier is not open. The current contract only accepts a fixed 0.05 BNB, so this site will not show an unsupported payment button.', meaningNote: 'FLAP STOCK is a Meme brand name—not company stock, equity, a security, dividends, rights to returns, or a price promise.' },
    presale: { regionLabel: 'Participation Center', eyebrow: '02 / PARTICIPATION CENTER', title: 'Connect, participate, and check in one place.', body: 'The site checks chain state before sending. A transaction hash appears as soon as it is broadcast; a later RPC issue will never be mislabeled as “not sent.”', facts: ['BSC MAINNET (56)', 'FIXED 0.05 BNB', 'ONE PARTICIPATION PER ADDRESS', 'MAXIMUM 10,000 ADDRESSES', 'DEADLINE: 2026-09-09 23:59:59 BEIJING TIME', 'MANUAL FLAP DISTRIBUTION AFTER PRESALE', 'NO REFUNDS'], actionLabel: 'CONNECT WALLET TO JOIN', unavailable: 'UNAVAILABLE', pendingLabel: 'PRESALE COMING SOON', warning: 'Before signing, verify BSC mainnet, 0.05 BNB, and presale contract 0x409c9448172b0f244a6823e91ad669281294622b.', interaction: { loading: 'READING CHAIN STATE', connectWallet: 'CHOOSE & CONNECT WALLET', chooseWallet: 'CHOOSE WALLET', confirm: 'CONFIRM 0.05 BNB PAYMENT', disclosure: 'I understand: the FLAP amount and distribution schedule are not announced; FLAP will be distributed manually; there are no refunds; one-address-once does not mean one-person-once.', participants: 'CONFIRMED ADDRESSES', raised: 'CONFIRMED BNB', countdown: 'TIME LEFT', addressNote: 'Addresses are not unique people', soldOut: 'THE 10,000-ADDRESS CAP IS FULL', soldOutAction: 'SOLD OUT', paused: 'PRESALE IS PAUSED', ended: 'PRESALE HAS ENDED', alreadyParticipated: 'THIS ADDRESS HAS AN ON-CHAIN PARTICIPATION RECORD', alreadyParticipatedAction: 'ADDRESS PARTICIPATED', unavailable: 'CHAIN STATE UNAVAILABLE', rpcError: 'CHAIN DATA TEMPORARILY UNAVAILABLE', walletMissing: 'NO WALLET DETECTED IN THIS BROWSER', walletHeading: 'CHOOSE A BSC WALLET', walletBody: 'Choose a detected browser wallet and confirm BSC mainnet.', walletMobileHint: 'On mobile, open hudiegupiao.com inside the browser in MetaMask, Trust Wallet, or another compatible wallet app.', walletConnectUnavailable: 'QR connection is not configured. Only genuinely detected wallets are shown.', close: 'CLOSE', account: 'ACCOUNT', network: 'NETWORK', disconnect: 'DISCONNECT', copy: 'COPY', copied: 'COPIED', wrongNetwork: 'SWITCH REQUIRED: BSC MAINNET (56)', waitingSignature: 'WAITING FOR WALLET SIGNATURE — NOT BROADCAST YET', broadcast: 'TRANSACTION BROADCAST', confirming: 'WAITING FOR ON-CHAIN CONFIRMATION', confirmed: 'PARTICIPATION CONFIRMED ON-CHAIN', rejected: 'CANCELLED IN WALLET — NOTHING WAS BROADCAST', failed: 'TRANSACTION FAILED — REVIEW THE REASON AND RETRY', uncertain: 'BROADCAST SUCCEEDED, BUT THE FINAL RESULT IS TEMPORARILY UNAVAILABLE. CHECK THE HASH ON-CHAIN.', viewOnBscScan: 'VIEW ON BSCSCAN', retry: 'CHECK AGAIN', myParticipation: 'MY PARTICIPATION', chainRecord: 'ON-CHAIN RECORD', savedRecord: 'LATEST SAVED TRANSACTION', noRecord: 'NO PARTICIPATION RECORD IS AVAILABLE FOR THIS ADDRESS', distributionPending: 'FLAP DISTRIBUTION: WAITING FOR MANUAL DISTRIBUTION', submittedAt: 'SUBMITTED' } },
    howTo: { regionLabel: 'How to Join', eyebrow: '03 / HOW TO JOIN', title: 'Three steps, with status all the way.', steps: [{ index: '01', title: 'PREPARE A WALLET & BNB', body: 'Use a BSC mainnet wallet with 0.05 BNB plus a small network fee.' }, { index: '02', title: 'VERIFY & SIGN', body: 'Check the network, amount, presale contract and no-refund rule before signing.' }, { index: '03', title: 'SAVE & CHECK', body: 'The hash appears after broadcast. Reconnect the same address to check its on-chain and saved record.' }] },
    publicProof: { regionLabel: 'Public Project Information', eyebrow: '04 / PUBLIC PROOF', title: 'Claims should be inspectable. Addresses should be verifiable.', body: 'The presale contract, recipient and admin are grouped here. Unknown information is kept clearly separate from the presale contract.', copy: 'COPY', copied: 'COPIED', openExplorer: 'VIEW ON BSCSCAN', pending: 'NOT ANNOUNCED', presaleLabel: 'PRESALE CONTRACT', tokenLabel: 'FLAP TOKEN CONTRACT', recipientLabel: 'BNB RECIPIENT', adminLabel: 'PRESALE ADMIN', platformLabel: 'LAUNCH PLATFORM RELATION', communityLabel: 'OFFICIAL COMMUNITY', presaleNote: 'Fixed 0.05 BNB participation and on-chain records.', tokenNote: 'Do not mistake the presale contract for a token contract.', recipientNote: 'BNB received by the presale contract is forwarded here.', adminNote: 'Can pause, resume, and update the end time; fixed amount and cap stay unchanged.', platformValue: 'flap.sh · PROJECT LINK PENDING', platformNote: 'Planned launch platform. FLAP STOCK is not an official platform project.', communityNote: 'Real X and Telegram links have not been supplied.' },
    updates: { regionLabel: 'Project Updates and Sharing', eyebrow: '05 / KEEP THE SIGNAL', title: 'Verify first. Share second. Record real progress.', body: 'Only completed or verifiable milestones appear here. Until official community links open, save the site and the brand avatar.', updatedLabel: 'LAST UPDATED', updatedValue: '2026-09-06', items: [{ date: 'SEP 06', title: 'PARTICIPATION CENTER V2', body: 'Reordered rules, wallet state, transaction feedback, personal records, and public proof.' }, { date: 'SEP 03', title: 'BSC PRESALE OPEN', body: 'Fixed 0.05 BNB, one entry per address, up to 10,000 addresses.' }, { date: 'SEP 02', title: 'FLAP STOCK BRAND LIVE', body: 'FLAP STOCK, acid-lime and purple identity, and community Meme positioning established.' }], shareTitle: 'FLAP THE RIGHT INFORMATION', shareBody: 'The share link includes source parameters so future campaigns can be measured.', shareButton: 'SYSTEM SHARE', copyButton: 'COPY SITE & INTRO', copied: 'SHARE TEXT COPIED', download: 'DOWNLOAD OFFICIAL AVATAR', shareText: 'FLAP STOCK presale is live on BSC: fixed 0.05 BNB, one participation per address. Read the complete rules before joining.' },
    nameCore: { regionLabel: 'FLAP STOCK Character Core', eyebrow: '06 / BRAND STORY', title: 'Four characters. One memorable Meme system.', cards: [{ glyph: '蝴', title: 'A TINY START', body: 'One butterfly can still change the path of the wind.' }, { glyph: '蝶', title: 'SHARED CHANGE', body: 'From observer to someone who actually participates.' }, { glyph: '股', title: 'A SHARED STORY', body: 'Not company shares—community attention held together.' }, { glyph: '票', title: 'A MEME ENTRY', body: 'A ticket into the story, not a security or promise of returns.' }], disclaimer: '股 and 票 are Meme brand metaphors only. They do not represent equity, real stock, securities, dividends, or rights to returns.' },
    faq: { regionLabel: 'Frequently Asked Questions', eyebrow: '07 / FAQ', title: 'Check once more before joining.', items: [{ question: 'HOW MUCH FLAP DOES 0.05 BNB RECEIVE?', answer: 'The amount and formula have not been officially announced. Make your own decision only after that information is published.' }, { question: 'WHEN WILL I RECEIVE FLAP?', answer: 'FLAP will be distributed manually after presale. Start time, completion time, and the final lookup method are not announced.' }, { question: 'WHY CAN’T I PAY 0.2 BNB?', answer: 'The current presale contract only accepts a fixed 0.05 BNB per address. The team-leader tier is not open.' }, { question: 'DOES “STOCK” MEAN COMPANY EQUITY?', answer: 'No. FLAP STOCK is a Meme brand name—not equity, a security, dividends, or a right to returns.' }, { question: 'WHAT IF LOOKUP FAILS AFTER BROADCAST?', answer: 'Keep the displayed transaction hash and check the real result on BscScan. On-chain records take priority over temporary page state.' }, { question: 'CAN THE RULES CHANGE?', answer: 'The admin may pause, resume, or update the end time within contract permissions. Project plan changes should be announced on the site and future official channels.' }] },
    footer: { disclaimer: 'FLAP is a pure community Meme token—not real stock, a security, an investment product, or a promise of returns. Verify on-chain information and decide independently.', rights: '© 2026 蝴蝶股票 · FLAP STOCK' },
    effect: { regionLabel: 'The Butterfly Effect', eyebrow: 'BUTTERFLY EFFECT', title: 'A tiny move can start a giant storm.', body: 'Every entry and share can become a new signal.', steps: [] }, signal: { regionLabel: 'Meme Signal Terminal', eyebrow: 'MEME SIGNAL', title: 'Watch the wings.', disclaimer: 'For entertainment only. Not financial data.', metrics: [] }, roadmap: { regionLabel: 'Roadmap', eyebrow: 'FLIGHT PATH', title: 'Flight path', phases: [], caveat: 'Subject to official announcements.' }, manifesto: { regionLabel: 'Community Manifesto', eyebrow: 'MANIFESTO', title: 'We do not predict the wind. We flap it into motion.', body: 'Ten thousand butterflies make a storm.' },
  },
}
