import test from 'node:test';
import assert from 'node:assert/strict';
import ganache from 'ganache';
import {BrowserProvider,ContractFactory,parseEther,ZeroHash,id} from 'ethers';
import {compile} from '../scripts/compile.mjs';
const source=`pragma solidity 0.8.30; import 'ChangeFairies.sol';
contract Boundary is ChangeFairies {constructor() ChangeFairies('https://zhongqiu.sh/nft/metadata/',bytes32(uint256(1))) {} function setSupply(uint256 n) external {totalSupply=n;}}
contract Receiver {ChangeFairies public nft;bool public blocked;constructor(address a){nft=ChangeFairies(a);}function go() external payable{nft.mint{value:msg.value}(1);}function onERC721Received(address,address,uint256,bytes calldata) external returns(bytes4){try nft.mint(1){revert('reentered');}catch{blocked=true;}return this.onERC721Received.selector;}}
contract Rejector {ChangeFairies public nft;constructor(address a){nft=ChangeFairies(a);}function go() external payable{nft.mint{value:msg.value}(1);}}`;
const {artifact,output}=compile({'Fixtures.sol':{content:source}});
const raw=ganache.provider({logging:{quiet:true},chain:{hardfork:'shanghai',chainId:56},wallet:{totalAccounts:4,defaultBalance:100}});
const provider=new BrowserProvider(raw);provider.pollingInterval=10;
const signer=await provider.getSigner(),buyer=await provider.getSigner(1),recipient=await provider.getSigner(2);
const deploy=async a=>{const c=await new ContractFactory(a.abi,a.evm.bytecode.object,signer).deploy(...(a===artifact?['https://zhongqiu.sh/nft/metadata/',id('manifest')]:[]));await c.waitForDeployment();return c;};
const nft=await deploy(artifact);const price=parseEther('0.001');
const receipt=async t=>(await t).wait();
await test('fixed immutable business terms and ERC721 metadata interfaces',async()=>{assert.equal(await nft.MAX_SUPPLY(),7777n);assert.equal(await nft.MINT_PRICE(),price);assert.equal(await nft.REVENUE(),'0x23898F0866E4D5fa5C9B97645239eD635EA93cDC');assert(await nft.supportsInterface('0x80ac58cd'));assert(await nft.supportsInterface('0x5b5e139f'));assert(await nft.supportsInterface('0x01ffc9a7'));assert(!artifact.abi.some(x=>['setPrice','setBaseURI','ownerMint','withdraw','upgradeTo'].includes(x.name)));});
await test('single and custom quantity mint; payment forwarded exactly',async()=>{const rev=await nft.REVENUE();const before=BigInt(await raw.request({method:'eth_getBalance',params:[rev,'latest']}));await receipt(nft.connect(buyer).mint(1,{value:price}));await receipt(nft.connect(buyer).mint(7,{value:price*7n}));assert.equal(await nft.totalSupply(),8n);assert.equal(await nft.balanceOf(await buyer.getAddress()),8n);assert.equal(await nft.ownerOf(8),await buyer.getAddress());assert.equal(BigInt(await raw.request({method:'eth_getBalance',params:[rev,'latest']}))-before,price*8n);assert.equal(await provider.getBalance(await nft.getAddress()),0n);});
await test('rejects zero, oversized batch, underpayment and overpayment',async()=>{for(const [n,v]of [[0,0n],[51,price*51n],[2,price],[1,price*2n]])await assert.rejects(nft.mint.staticCall(n,{value:v}));assert.equal(await nft.totalSupply(),8n);});
await test('wallet metadata and normal ERC721 transfers',async()=>{assert.equal(await nft.tokenURI(1),'https://zhongqiu.sh/nft/metadata/1.json');await assert.rejects(nft.tokenURI(0));await assert.rejects(nft.tokenURI(9));await receipt(nft.connect(buyer).approve(await recipient.getAddress(),1));await receipt(nft.connect(recipient).transferFrom(await buyer.getAddress(),await recipient.getAddress(),1));assert.equal(await nft.ownerOf(1),await recipient.getAddress());});
await test('exact supply boundary rejects overflow and sold out',async()=>{const edge=await deploy(output.contracts['Fixtures.sol'].Boundary);await receipt(edge.setSupply(7775));await assert.rejects(edge.mint.staticCall(3,{value:price*3n}));await receipt(edge.mint(2,{value:price*2n}));assert.equal(await edge.totalSupply(),7777n);await assert.rejects(edge.mint.staticCall(1,{value:price}));});
await test('contract receiver cannot reenter and unsafe receivers revert atomically',async()=>{for(const name of ['Receiver','Rejector']){const a=output.contracts['Fixtures.sol'][name];const c=await new ContractFactory(a.abi,a.evm.bytecode.object,signer).deploy(await nft.getAddress());await c.waitForDeployment();const before=await nft.totalSupply();if(name==='Receiver'){await receipt(c.go({value:price}));assert(await c.blocked());assert.equal(await nft.totalSupply(),before+1n);}else{await assert.rejects(c.go.staticCall({value:price}));assert.equal(await nft.totalSupply(),before);}}});
await test('failed revenue transfer rolls back minted tokens and payment',async()=>{const rev=await nft.REVENUE(),before=await nft.totalSupply();await raw.request({method:'evm_setAccountCode',params:[rev,'0x60006000fd']});await assert.rejects(nft.connect(buyer).mint.staticCall(1,{value:price}));assert.equal(await nft.totalSupply(),before);await raw.request({method:'evm_setAccountCode',params:[rev,'0x']});});
await test('50 NFT batch fits conservative block budget',async()=>{const gas=await nft.mint.estimateGas(50,{value:price*50n});assert(gas<5000000n);console.log('50 NFT gas estimate:',gas.toString());await receipt(nft.mint(50,{value:price*50n}));});
await test('constructor rejects empty metadata or zero content commitment',async()=>{const f=new ContractFactory(artifact.abi,artifact.evm.bytecode.object,signer);await assert.rejects(f.deploy('',id('manifest')));await assert.rejects(f.deploy('https://zhongqiu.sh/',ZeroHash));});
await raw.disconnect();
