import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {JSDOM} from 'jsdom';import {fileURLToPath} from 'node:url';import path from 'node:path';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const htmlPath=path.join(root,'dist/nft/index.html');
// UI integration runs in the website checkout; deployment CI runs contract tests only.
if(fs.existsSync(htmlPath)){
const html=fs.readFileSync(htmlPath,'utf8'),script=fs.readFileSync(path.join(root,'dist/nft/app.js'),'utf8');
for(const lang of ['zh-CN','zh-TW','en','ja','ko'])await test('safe not-deployed UX, quantity and gallery: '+lang,async()=>{let walletCalls=0;const dom=new JSDOM(html,{url:'https://zhongqiu.sh/nft/?lang='+lang,runScripts:'outside-only'});const w=dom.window;w.TextEncoder=TextEncoder;w.TextDecoder=TextDecoder;w.fetch=async url=>url==='/nft/config.json'?{json:async()=>({deploymentUrl:'https://example.test/deployment.json'})}:{status:404,ok:false};w.ethereum={request:async()=>{walletCalls++;throw Error('wallet called');}};w.eval(script);await new Promise(r=>setTimeout(r,20));const doc=w.document;assert(doc.getElementById('mint').disabled);assert.equal(walletCalls,0);assert(!doc.body.textContent.includes('undefined'));for(const e of doc.querySelectorAll('[data-n]'))assert(e.textContent.trim());const q=doc.getElementById('quantity');q.value=7;q.dispatchEvent(new w.Event('input'));assert.equal(doc.getElementById('total').textContent,'0.007 BNB');q.value=51;q.dispatchEvent(new w.Event('input'));assert.equal(doc.getElementById('total').textContent,'—');doc.getElementById('token-id').value=7777;doc.getElementById('token-id').dispatchEvent(new w.Event('change'));assert(doc.getElementById('preview-image').src.endsWith('/7777.png'));dom.window.close();});
}
const galleryPath=path.join(root,'dist/nft/gallery/index.html');if(fs.existsSync(galleryPath))for(const lang of ['zh-CN','zh-TW','en','ja','ko'])await test('full gallery pagination and exact final ID: '+lang,()=>{const dom=new JSDOM(fs.readFileSync(galleryPath,'utf8'),{url:'https://zhongqiu.sh/nft/gallery/?token=7777&lang='+lang,runScripts:'outside-only'});dom.window.eval(fs.readFileSync(path.join(root,'dist/nft/gallery/gallery.js'),'utf8'));const d=dom.window.document;assert.equal(d.querySelectorAll('.art-card').length,1);assert(d.querySelector('.art-card').href.includes('token=7777'));assert(d.getElementById('next-page').disabled);d.getElementById('prev').click();assert.equal(d.querySelectorAll('.art-card').length,24);assert.equal(d.getElementById('page').textContent,'324 / 325');d.getElementById('jump').value=888;d.getElementById('jump-form').dispatchEvent(new dom.window.Event('submit',{cancelable:true}));assert(d.querySelector('.selected').textContent.includes('888'));assert(!d.body.textContent.includes('undefined'));dom.window.close();});
