import {BrowserProvider,JsonRpcProvider,Contract,parseEther,formatEther,keccak256} from 'ethers';
const $=id=>document.getElementById(id);
const zh=Object.fromEntries([...document.querySelectorAll('[data-n]')].map(e=>[e.dataset.n,e.textContent]));
const extra={pending:'合约尚未部署，暂未开放铸造',checking:'正在读取链上状态…',ready:'BNB Chain · 铸造开放',sold:'已售罄',mint:'连接钱包并铸造',working:'请在钱包中确认…',waiting:'交易已提交，等待确认…',success:'铸造成功，NFT 已进入你的钱包。',failed:'交易未完成，请检查钱包提示后重试。',rejected:'你已取消钱包请求，未提交新的交易。',unavailable:'链上信息暂不可用，铸造已暂停',walletMissing:'请用 TokenPocket 的 DApp 浏览器打开此页，或使用已安装的钱包扩展。',invalid:'请输入 1–50 的整数，且不超过剩余数量。',insufficient:'BNB 余额不足以支付 NFT 金额和 Gas。'};
Object.assign(zh,extra);
const en={brand:'Butterfly Mid-Autumn',title:'A moon fairy, yours to collect.',intro:'One moon above. Together onchain. Meet 7,777 generative fairy portraits with distinct faces, hair, hanfu and moonlit scenes.',actual:'Actual collectible',browse:'View token',collection:'Chang’e Fairies · 7777',unit:'Per NFT',minted:'Minted / total',quantity:'Mint quantity',batch:'1–50 per transaction; mint more in separate batches. IDs are sequential, not random blind boxes.',total:'NFT total',gas:'Your wallet shows network gas separately before payment.',viewTx:'View transaction ↗',contract:'NFT contract',revenue:'Mint revenue recipient',details:'Before you collect',artTitle:'A different fairy in every portrait',artText:'Original generative vector illustrations exported as 512 × 512 PNGs, not 7,777 photorealistic AI portraits. Browse every token ID.',termsTitle:'Rules fixed in the contract',termsText:'7,777 supply, 0.001 BNB each. Proceeds go directly to the specified recipient. No admin mint, price changes or recipient changes.',walletTitle:'TokenPocket wallet',walletText:'Open this page in a TokenPocket BNB Chain wallet. Built with ERC-721 and standard image metadata; wallet listing, indexing and rendering still require live verification.',storageTitle:'Storage and ownership',storageText:'Images and metadata are hosted on this website. Their manifest hash is fixed in the contract for verification. NFTs carry no dividend, equity or return entitlement.',manifest:'View the complete artwork checksum manifest ↗',slogan:'One moon above. Together onchain.',pending:'Contract not deployed · Minting not open',checking:'Reading blockchain status…',ready:'BNB Chain · Minting open',sold:'Sold out',mint:'Connect wallet & mint',working:'Confirm in your wallet…',waiting:'Transaction submitted. Waiting for confirmation…',success:'Mint successful. Your NFTs are in your wallet.',failed:'Transaction incomplete. Check your wallet and retry.',rejected:'Wallet request cancelled. No new transaction submitted.',unavailable:'Blockchain data unavailable · Minting paused',walletMissing:'Open this page in TokenPocket’s DApp browser or use an installed wallet extension.',invalid:'Enter an integer from 1 to 50, within remaining supply.',insufficient:'Insufficient BNB for NFTs and network gas.'};
const tw={...zh,brand:'蝴蝶中秋',title:'把一位嫦娥，藏進你的月光。',intro:'天涯共此月，鏈上共團圓。7,777 位國風插畫仙子，以不同的容貌、髮型、仙衣與月景相遇。',actual:'實際藏品圖',browse:'查看編號',unit:'每張',minted:'已鑄造 / 總量',quantity:'鑄造數量',batch:'每筆 1–50 張；需要更多可分筆鑄造。按編號順序鑄造，不是隨機盲盒。',total:'NFT 金額',gas:'Gas 由錢包另行顯示，付款前可查看。',viewTx:'查看交易 ↗',contract:'NFT 合約',revenue:'鑄造收入接收地址',details:'收藏之前，先了解清楚',artTitle:'每位仙子，各有模樣',artText:'發行圖為原創生成式向量插畫，匯出為 512 × 512 PNG；不是 7,777 張寫實 AI 肖像。可逐一查看全部編號。',termsTitle:'規則寫進合約',termsText:'總量 7,777，單價 0.001 BNB，鑄造收入直接進入指定地址。沒有管理員增發、改價或更換收款地址的功能。',walletTitle:'TokenPocket 錢包',walletText:'在 TP 的 BNB Chain 錢包中開啟本頁鑄造。按 ERC-721 與標準圖片中繼資料實作；錢包收錄、自動索引和實際展示仍需上線後驗證。',storageTitle:'圖片與收藏權益',storageText:'圖片和中繼資料由官網託管，內容清單雜湊固定在合約中供核驗。NFT 不代表分紅權、股權或收益承諾。',manifest:'查看完整作品校驗清單 ↗',slogan:'天涯共此月，鏈上共團圓。',pending:'合約尚未部署，暫未開放鑄造',checking:'正在讀取鏈上狀態…',ready:'BNB Chain · 鑄造開放',sold:'已售罄',mint:'連接錢包並鑄造',working:'請在錢包中確認…',waiting:'交易已提交，等待確認…',success:'鑄造成功，NFT 已進入你的錢包。',failed:'交易未完成，請檢查錢包提示後重試。',rejected:'你已取消錢包請求，未提交新的交易。',unavailable:'鏈上資訊暫不可用，鑄造已暫停',walletMissing:'請用 TokenPocket 的 DApp 瀏覽器開啟此頁，或使用已安裝的錢包擴充功能。',invalid:'請輸入 1–50 的整數，且不超過剩餘數量。',insufficient:'BNB 餘額不足以支付 NFT 金額和 Gas。'};
const ja={...en,brand:'蝴蝶中秋',title:'月の仙女を、あなたのコレクションに。',intro:'同じ月を見上げ、チェーン上で集う。顔立ち、髪型、衣装、月景色が異なる7,777枚の生成アート。',actual:'実際の作品',browse:'番号を見る',collection:'嫦娥の仙女 · 7777',unit:'1枚あたり',minted:'発行済み / 総数',quantity:'ミント枚数',batch:'1回1〜50枚。追加分は別の取引で。番号順に発行し、ランダム抽選ではありません。',total:'NFT 合計',gas:'ガス代は支払い前にウォレットで別途表示されます。',viewTx:'取引を見る ↗',contract:'NFT コントラクト',revenue:'販売代金の受取先',details:'コレクションの前に',artTitle:'一枚ごとに異なる仙女',artText:'独自の生成ベクターイラストを512 × 512 PNGで保存。写実的なAI肖像7,777枚ではありません。全番号を閲覧できます。',termsTitle:'コントラクトに固定されたルール',termsText:'総数7,777枚、1枚0.001 BNB。代金は指定先へ直接送金。管理者による追加発行、価格・受取先変更はありません。',walletTitle:'TokenPocket ウォレット',walletText:'TPのBNB Chainウォレットからこのページを開いてください。ERC-721と標準画像メタデータを使用。収録・自動検出・実際の表示は公開後の検証が必要です。',storageTitle:'画像の保管と権利',storageText:'画像とメタデータは公式サイトで保管し、一覧のハッシュをコントラクトに固定します。配当、株式、収益を約束するNFTではありません。',manifest:'全作品の検証用一覧を見る ↗',slogan:'同じ月を見上げ、チェーン上で集う。',pending:'未デプロイ · ミント未開始',checking:'チェーンの状態を確認中…',ready:'BNB Chain · ミント受付中',sold:'完売',mint:'ウォレット接続・ミント',working:'ウォレットで確認してください…',waiting:'取引を送信しました。確認待ち…',success:'ミント完了。NFTはウォレットに届きました。',failed:'取引未完了。ウォレットを確認して再試行してください。',rejected:'ウォレットの要求をキャンセルしました。',unavailable:'チェーン情報を取得できません · ミント停止中',walletMissing:'TokenPocketのDAppブラウザかウォレット拡張機能で開いてください。',invalid:'残り枚数の範囲で1〜50の整数を入力してください。',insufficient:'NFTとガス代に必要なBNBが不足しています。'};
const ko={...en,brand:'나비 중추절',title:'달의 선녀를 당신의 컬렉션에.',intro:'같은 달 아래, 온체인에서 함께. 얼굴, 머리, 의상, 달 풍경이 다른 7,777개의 생성형 일러스트입니다.',actual:'실제 작품',browse:'번호 보기',collection:'항아 선녀 · 7777',unit:'장당',minted:'발행 / 총수량',quantity:'민팅 수량',batch:'거래당 1–50개. 추가 수량은 나누어 민팅하세요. 번호순 발행이며 무작위 뽑기가 아닙니다.',total:'NFT 합계',gas:'네트워크 가스는 결제 전 지갑에 별도로 표시됩니다.',viewTx:'거래 보기 ↗',contract:'NFT 컨트랙트',revenue:'민팅 수익 수령 주소',details:'수집 전에 확인하세요',artTitle:'각기 다른 선녀',artText:'독창적인 생성형 벡터 일러스트를 512 × 512 PNG로 제공합니다. 사실적인 AI 인물 사진 7,777장이 아닙니다. 모든 번호를 볼 수 있습니다.',termsTitle:'컨트랙트에 고정된 규칙',termsText:'총 7,777개, 개당 0.001 BNB. 수익은 지정 주소로 직접 전송됩니다. 관리자 추가 발행, 가격 변경, 수령 주소 변경 기능이 없습니다.',walletTitle:'TokenPocket 지갑',walletText:'TP의 BNB Chain 지갑에서 이 페이지를 여세요. ERC-721과 표준 이미지 메타데이터를 사용합니다. 지갑 등록, 자동 검색과 실제 표시는 출시 후 검증이 필요합니다.',storageTitle:'이미지 보관과 권리',storageText:'이미지와 메타데이터는 공식 사이트에서 보관하며 목록 해시는 컨트랙트에 고정됩니다. 배당권, 지분 또는 수익을 보장하지 않습니다.',manifest:'전체 작품 검증 목록 보기 ↗',slogan:'같은 달 아래, 온체인에서 함께.',pending:'컨트랙트 미배포 · 민팅 준비 중',checking:'체인 상태 확인 중…',ready:'BNB Chain · 민팅 가능',sold:'매진',mint:'지갑 연결 후 민팅',working:'지갑에서 확인해 주세요…',waiting:'거래 전송 완료. 확인 대기 중…',success:'민팅 완료. NFT가 지갑에 도착했습니다.',failed:'거래 미완료. 지갑을 확인하고 다시 시도하세요.',rejected:'지갑 요청을 취소했습니다.',unavailable:'체인 정보를 읽을 수 없습니다 · 민팅 중지',walletMissing:'TokenPocket DApp 브라우저 또는 지갑 확장 프로그램에서 여세요.',invalid:'남은 수량 이내로 1–50 사이 정수를 입력하세요.',insufficient:'NFT와 가스 결제에 필요한 BNB가 부족합니다.'};
const texts={'zh-CN':zh,'zh-TW':tw,en,ja,ko};let lang='zh-CN',config,contract,readProvider,busy=false,remaining=7777,state='checking';
try{lang=new URLSearchParams(location.search).get('lang')||localStorage.getItem('zhongqiu-language')||lang;}catch{}
if(!texts[lang])lang='zh-CN';
const t=k=>texts[lang][k];
function render(){document.documentElement.lang=lang;$('nft-language').value=lang;document.querySelectorAll('[data-n]').forEach(e=>e.textContent=t(e.dataset.n));$('sale-status').textContent=t(state);$('mint').textContent=t(busy?'working':state==='ready'?'mint':state);$('mint').disabled=busy||state!=='ready';document.title=t('collection')+' | '+t('brand');}
$('nft-language').onchange=e=>{lang=e.target.value;try{localStorage.setItem('zhongqiu-language',lang);}catch{}const u=new URL(location.href);u.searchParams.set('lang',lang);history.replaceState(null,'',u);render();};
function quantity(){const q=Number($('quantity').value);return Number.isInteger(q)&&q>=1&&q<=50&&q<=remaining?q:null;}
function updateTotal(){const q=quantity();$('total').textContent=q?formatEther(BigInt(q)*1000000000000000n)+' BNB':'—';}
$('quantity').oninput=updateTotal;
$('minus').onclick=()=>{$('quantity').value=Math.max(1,(Number($('quantity').value)||1)-1);updateTotal();};
$('plus').onclick=()=>{$('quantity').value=Math.min(50,remaining,(Number($('quantity').value)||1)+1);updateTotal();};
document.querySelectorAll('[data-quantity]').forEach(b=>b.onclick=()=>{$('quantity').value=b.dataset.quantity;updateTotal();});
function preview(id){id=Math.min(7777,Math.max(1,Number.isInteger(id)?id:1));$('token-id').value=id;$('preview-image').src=`/nft/images/${id}.png`;$('preview-image').alt=`Chang’e Fairies #${id}`;$('preview-name').textContent=`Chang’e Fairies #${id}`;const u=new URL(location.href);u.searchParams.set('token',id);history.replaceState(null,'',u);}
$('token-id').onchange=()=>preview(Number($('token-id').value));$('previous').onclick=()=>preview(Number($('token-id').value)-1);$('next').onclick=()=>preview(Number($('token-id').value)+1);preview(Number(new URLSearchParams(location.search).get('token')||1));
async function refresh(){if(!contract)return;try{const supply=await contract.totalSupply();remaining=7777-Number(supply);$('supply').textContent=Number(supply).toLocaleString()+' / 7,777';state=remaining?'ready':'sold';}catch{state='unavailable';}render();updateTotal();}
async function initialise(){try{config=await(await fetch('/nft/config.json',{cache:'no-store'})).json();const r=await fetch(config.deploymentUrl,{cache:'no-store'});if(r.status===404){state='pending';render();return;}if(!r.ok)throw Error('Deployment status');const deployed=await r.json();if(deployed.status!=='mined'){state='pending';render();return;}if(deployed.project!=='zhongqiu.sh/change-7777'||deployed.manifestHash!==config.manifestHash||!/^0x[0-9a-fA-F]{40}$/.test(deployed.address))throw Error('Invalid deployment');readProvider=new JsonRpcProvider(config.rpc);if((await readProvider.getNetwork()).chainId!==56n)throw Error('Wrong chain');if(keccak256(await readProvider.getCode(deployed.address))!==config.runtimeHash)throw Error('Unexpected code');contract=new Contract(deployed.address,config.abi,readProvider);const [p,m,revenue,h]=await Promise.all([contract.MINT_PRICE(),contract.MAX_SUPPLY(),contract.REVENUE(),contract.manifestHash()]);if(p!==parseEther('0.001')||m!==7777n||revenue.toLowerCase()!==config.revenue.toLowerCase()||h!==config.manifestHash)throw Error('Terms mismatch');config.address=deployed.address;$('contract-link').textContent=deployed.address;$('contract-link').href=`https://bscscan.com/address/${deployed.address}`;await refresh();}catch{state='unavailable';render();}}
const announced=[];window.addEventListener('eip6963:announceProvider',e=>{if(e.detail?.provider&&!announced.some(x=>x.provider===e.detail.provider))announced.push(e.detail);});window.dispatchEvent(new Event('eip6963:requestProvider'));
$('mint').onclick=async()=>{if(busy||state!=='ready')return;const q=quantity();if(!q){$('feedback').textContent=t('invalid');return;}const injected=announced.find(x=>/tokenpocket/i.test(x.info?.name||''))?.provider||window.ethereum?.providers?.find(x=>x.isTokenPocket)||window.ethereum;if(!injected){$('feedback').textContent=t('walletMissing');return;}busy=true;render();$('transaction').hidden=true;$('feedback').textContent='';try{await injected.request({method:'eth_requestAccounts'});let chain=await injected.request({method:'eth_chainId'});if(chain!=='0x38'){await injected.request({method:'wallet_switchEthereumChain',params:[{chainId:'0x38'}]});}const walletProvider=new BrowserProvider(injected);if((await walletProvider.getNetwork()).chainId!==56n)throw Error('Wrong chain');const signer=await walletProvider.getSigner();const sale=new Contract(config.address,config.abi,signer);if(keccak256(await walletProvider.getCode(config.address))!==config.runtimeHash)throw Error('Contract mismatch');const current=await sale.totalSupply();if(current+BigInt(q)>7777n)throw Error('Supply changed');const value=BigInt(q)*1000000000000000n;await sale.mint.staticCall(q,{value});const tx=await sale.mint(q,{value});$('feedback').textContent=t('waiting');$('transaction').href=`https://bscscan.com/tx/${tx.hash}`;$('transaction').hidden=false;const receipt=await tx.wait();if(receipt.status!==1)throw Error('Transaction reverted');$('feedback').textContent=t('success');await refresh();}catch(e){if(e.code==='TRANSACTION_REPLACED'&&!e.cancelled&&e.receipt?.status===1){$('feedback').textContent=t('success');$('transaction').href=`https://bscscan.com/tx/${e.receipt.hash}`;$('transaction').hidden=false;await refresh();}else $('feedback').textContent=t(e.code===4001||e.code==='ACTION_REJECTED'?'rejected':e.code==='INSUFFICIENT_FUNDS'?'insufficient':'failed');}finally{busy=false;render();}};
render();updateTotal();initialise();setInterval(()=>{if(!document.hidden&&!busy)refresh();},30000);
