import {svg,metadata,traits} from './art.mjs';
import sharp from 'sharp';
import fs from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {root} from './compile.mjs';
const output=path.resolve(root,'../dist/nft');
for(const d of ['images','metadata'])fs.mkdirSync(path.join(output,d),{recursive:true});
const entries=[],hashes=new Set();
const hash=x=>createHash('sha256').update(x).digest('hex');
let next=1;
await Promise.all(Array.from({length:6},async()=>{while(next<=7777){const id=next++,xml=svg(id);const png=await sharp(Buffer.from(xml)).png({compressionLevel:9,palette:true,colours:128,dither:0.25}).toBuffer();const h=hash(png);if(hashes.has(h))throw Error('Duplicate artwork '+id);hashes.add(h);const m=JSON.stringify(metadata(id));fs.writeFileSync(path.join(output,`images/${id}.png`),png);fs.writeFileSync(path.join(output,`metadata/${id}.json`),m);entries.push({id,imageSha256:h,metadataSha256:hash(m),traitSignature:traits(id).signature});if(id%1000===0)console.log('Generated',id);}}));
entries.sort((a,b)=>a.id-b.id);
const manifest=JSON.stringify({version:1,count:7777,style:'Original generative vector illustration',imageSize:512,entries});
fs.writeFileSync(path.join(output,'manifest.json'),manifest);
fs.writeFileSync(path.join(output,'manifest-sha256.txt'),hash(manifest)+'\n');
fs.writeFileSync(path.join(output,'collection.json'),JSON.stringify({name:"Chang'e Fairies · 蝴蝶中秋",description:'天涯共此月，链上共团圆。7,777 original generative Chang’e fairy portraits.',image:'https://zhongqiu.sh/nft/images/1.png',external_link:'https://zhongqiu.sh/nft/'}));
await sharp(Buffer.from(svg(1))).resize(256,256).png().toFile(path.join(output,'logo.png'));
console.log('Complete:',hashes.size,'distinct image hashes. Manifest:',hash(manifest));
