import {BrowserProvider,JsonRpcProvider,Contract,parseEther,formatEther,isAddress} from 'ethers';
const $=s=>document.querySelector(s),key=document.body.dataset.collection||'change',marketPage=key==='market';
const lang=$('#language'),dict={
 'zh-CN':{brand:'蝴蝶中秋',change:'嫦娥 NFT',rabbit:'玉兔 NFT',market:'团圆集市',connect:'连接钱包',mint:'随机铸造',quantity:'铸造数量（1–50）',prev:'上一页',next:'下一页',jump:'跳转',gallery:'画面与故事',disclosure:'以 5 幅嫦娥、9 幅玉兔原画组合衍生。每张装饰组合不同；故事依据属性组合编写。原图人物与颜色保持不变。',pending:'主网合约尚未完成部署，暂未开放铸造和交易。',my:'我的 NFT',refresh:'刷新链上状态',buy:'购买',sell:'挂单出售',cancel:'撤销挂单',price:'售价（BNB）',id:'NFT 编号',expiry:'有效天数（1–30）',empty:'暂无有效挂单',status:'链上状态',motto:'天涯共此月，链上共团圆。',fee:'平台手续费 0%。挂单、撤单和购买需要网络 Gas；成交款直接付给卖家。',settle:'结算待领取 NFT',waiting:'等待随机结果；任何人均可按顺序结算。',select:'选择系列'},
 en:{brand:'Butterfly Mid-Autumn',change:'Chang’e NFT',rabbit:'Jade Rabbit NFT',market:'Reunion Market',connect:'Connect wallet',mint:'Random mint',quantity:'Quantity (1–50)',prev:'Previous',next:'Next',jump:'Go',gallery:'Art & stories',disclosure:'Compositional editions from 5 Chang’e and 9 Jade Rabbit originals. Ornament combinations differ; stories are assembled from narrative traits. Original colors and figures are preserved.',pending:'Mainnet deployment is not complete. Minting and trading are closed.',my:'My NFTs',refresh:'Refresh on-chain status',buy:'Buy',sell:'List for sale',cancel:'Cancel listing',price:'Price (BNB)',id:'Token ID',expiry:'Valid days (1–30)',empty:'No active listings',status:'On-chain status',motto:'One moon above, a reunion on-chain.',fee:'0% platform fee. Listing, cancellation and purchase cost network gas. Sellers receive the full sale price.',settle:'Settle pending NFTs',waiting:'Waiting for randomness; anyone may settle requests in sequence.',select:'Collection'},
 'zh-TW':{brand:'蝴蝶中秋',change:'嫦娥 NFT',rabbit:'玉兔 NFT',market:'團圓集市',connect:'連接錢包',mint:'隨機鑄造',quantity:'鑄造數量（1–50）',prev:'上一頁',next:'下一頁',jump:'跳轉',gallery:'畫面與故事',disclosure:'以 5 幅嫦娥、9 幅玉兔原畫組合衍生。每張裝飾組合不同；故事依據屬性組合編寫。原圖人物與顏色保持不變。',pending:'主網合約尚未完成部署，暫未開放鑄造和交易。',my:'我的 NFT',refresh:'刷新鏈上狀態',buy:'購買',sell:'掛單出售',cancel:'撤銷掛單',price:'售價（BNB）',id:'NFT 編號',expiry:'有效天數（1–30）',empty:'暫無有效掛單',status:'鏈上狀態',motto:'天涯共此月，鏈上共團圓。',fee:'平台手續費 0%。掛單、撤單和購買需要網路 Gas；成交款直接付給賣家。',settle:'結算待領取 NFT',waiting:'等待隨機結果；任何人均可按順序結算。',select:'選擇系列'},
 ja:{brand:'蝴蝶中秋',change:'嫦娥 NFT',rabbit:'玉兎 NFT',market:'再会マーケット',connect:'ウォレット接続',mint:'ランダムミント',quantity:'数量（1–50）',prev:'前へ',next:'次へ',jump:'移動',gallery:'作品と物語',disclosure:'嫦娥5点・玉兎9点の原画から構成した派生作品です。装飾の組合せが異なり、物語は属性から構成されています。原画の色と人物を保持しています。',pending:'メインネットへのデプロイは未完了です。ミントと取引は開始していません。',my:'所有 NFT',refresh:'チェーン情報を更新',buy:'購入',sell:'出品',cancel:'出品を取消',price:'価格（BNB）',id:'トークン番号',expiry:'有効日数（1–30）',empty:'有効な出品はありません',status:'チェーン情報',motto:'同じ月の下、チェーンで再会。',fee:'プラットフォーム手数料0%。出品・取消・購入にはネットワーク手数料が必要です。売上は全額出品者へ。',settle:'保留中の NFT を確定',waiting:'乱数を待機中。リクエストは順番に確定できます。',select:'コレクション'},
 ko:{brand:'호접중추',change:'항아 NFT',rabbit:'옥토끼 NFT',market:'재회 마켓',connect:'지갑 연결',mint:'무작위 민팅',quantity:'수량 (1–50)',prev:'이전',next:'다음',jump:'이동',gallery:'그림과 이야기',disclosure:'항아 원화 5점과 옥토끼 원화 9점으로 만든 조합 작품입니다. 장식 조합이 다르며 이야기는 속성에 따라 구성됩니다. 원화의 색과 인물을 유지합니다.',pending:'메인넷 배포가 완료되지 않았습니다. 민팅과 거래는 아직 닫혀 있습니다.',my:'내 NFT',refresh:'온체인 상태 갱신',buy:'구매',sell:'판매 등록',cancel:'등록 취소',price:'가격 (BNB)',id:'토큰 번호',expiry:'유효 일수 (1–30)',empty:'유효한 판매 등록 없음',status:'온체인 상태',motto:'같은 달 아래, 체인에서 만나요.',fee:'플랫폼 수수료 0%. 등록·취소·구매 시 네트워크 가스가 필요합니다. 판매 대금은 전액 판매자에게 지급됩니다.',settle:'대기 NFT 확정',waiting:'무작위 결과를 기다리는 중입니다. 요청 순서대로 확정할 수 있습니다.',select:'컬렉션'}
};
lang.value=new URLSearchParams(location.search).get('lang')||localStorage.getItem('zhongqiu-language')||'zh-CN';if(!dict[lang.value])lang.value='zh-CN';
let page=0,config,deployment,items=[],wallet,account,busy=false;
const t=k=>(dict[lang.value]||dict.en)[k]||dict.en[k]||k;
const abi=['function mint(uint256) payable','function totalSupply() view returns(uint256)','function totalReserved() view returns(uint256)','function nextToSettle() view returns(uint256)','function requestCount() view returns(uint256)','function requests(uint256) view returns(address buyer,uint32 quantity,bool ready,bool settled,uint256 vrfId,uint256 seed)','function settleNext(uint256)','function ownedInRange(address,uint256,uint256) view returns(uint256[])','function balanceOf(address) view returns(uint256)','function ownerOf(uint256) view returns(address)','function approve(address,uint256)','function MINT_PRICE() view returns(uint256)','function MAX_SUPPLY() view returns(uint256)','function REVENUE() view returns(address)','function manifestHash() view returns(bytes32)'];
const tuple='(address seller,address collection,uint256 tokenId,uint256 price,uint256 deadline,uint256 salt)';
const marketABI=[`function register(${tuple},bytes) returns(bytes32)`,`function cancel(${tuple})`,'function buy(bytes32) payable','function orderCount() view returns(uint256)','function orderIds(uint256) view returns(bytes32)',`function orders(bytes32) view returns${tuple}`,'function isActive(bytes32) view returns(bool)'];
const types={Order:[{name:'seller',type:'address'},{name:'collection',type:'address'},{name:'tokenId',type:'uint256'},{name:'price',type:'uint256'},{name:'deadline',type:'uint256'},{name:'salt',type:'uint256'}]};
const rpc=new JsonRpcProvider('https://bsc-dataseed.binance.org',56,{staticNetwork:true});
const ready=()=>deployment?.status==='verified'&&['change','rabbit','market'].every(k=>isAddress(deployment[k]?.address||''));
function message(s){$('#message').textContent=s;}
function paint(){document.documentElement.lang=lang.value;document.querySelectorAll('[data-t]').forEach(e=>e.textContent=t(e.dataset.t));$('#title').textContent=t(key);if(!ready())$('#chain-state').textContent=t('pending');render();}
lang.onchange=()=>{localStorage.setItem('zhongqiu-language',lang.value);paint();};
function card(item,k){const a=document.createElement('article');a.className='nft-card';const img=document.createElement('img');img.src=`${config.prefix}/${k}/images/${item.id}.webp`;img.alt=`${t(k)} #${item.id}`;img.loading='lazy';img.width=640;img.height=640;a.append(img);const h=document.createElement('h3');h.textContent=`${t(k)} #${item.id} · ${item.title||''}`;a.append(h);if(item.story){const p=document.createElement('p');p.textContent=lang.value.startsWith('zh')?item.story:item.story_en;a.append(p);}const link=document.createElement('a');link.href=img.src;link.target='_blank';link.rel='noopener';link.textContent='↗ '+item.id;a.append(link);return a;}
function render(){if(marketPage||!config)return;const grid=$('#cards');grid.replaceChildren();items.slice(page*24,page*24+24).forEach(x=>grid.append(card(x,key)));$('#range').textContent=`${page*24+1}–${Math.min((page+1)*24,items.length)} / ${items.length}`;$('#prev').disabled=page===0;$('#next').disabled=(page+1)*24>=items.length;}
$('#prev').onclick=()=>{page=Math.max(0,page-1);render();};$('#next').onclick=()=>{page=Math.min(Math.ceil(items.length/24)-1,page+1);render();};
$('#jump').onclick=()=>{const n=Number($('#jump-id').value);if(Number.isInteger(n)&&n>=1&&n<=7777){page=Math.floor((n-1)/24);render();}};
async function connected(){if(!window.ethereum)throw Error(lang.value.startsWith('zh')?'请在 TokenPocket 的 DApp 浏览器打开本站，或安装兼容钱包。':'Open in TokenPocket’s DApp browser or install a compatible wallet.');await window.ethereum.request({method:'eth_requestAccounts'});const chain=await window.ethereum.request({method:'eth_chainId'});if(chain!=='0x38')await window.ethereum.request({method:'wallet_switchEthereumChain',params:[{chainId:'0x38'}]});wallet=new BrowserProvider(window.ethereum);const signer=await wallet.getSigner();account=await signer.getAddress();$('#connect').textContent=account.slice(0,6)+'…'+account.slice(-4);return signer;}
async function checked(){if(!ready())throw Error(t('pending'));const s=await connected();if((await wallet.getNetwork()).chainId!==56n)throw Error('BNB Chain required');return s;}
async function action(fn){if(busy)return;busy=true;try{await fn();}catch(e){message(e.shortMessage||e.message||String(e));}finally{busy=false;}}
async function tx(p){message('…');const sent=await p;const link=document.createElement('a');link.href='https://bscscan.com/tx/'+sent.hash;link.target='_blank';link.rel='noopener';link.textContent=sent.hash;$('#message').replaceChildren(link);const receipt=await sent.wait();if(receipt.status!==1)throw Error('Transaction failed');return receipt;}
$('#connect').onclick=()=>action(connected);
window.ethereum?.on?.('accountsChanged',()=>{wallet=null;account=null;$('#connect').textContent=t('connect');$('#owned').replaceChildren();});
window.ethereum?.on?.('chainChanged',()=>{wallet=null;account=null;$('#connect').textContent=t('connect');$('#owned').replaceChildren();});
async function refresh(){if(!ready()){message(t('pending'));return;}if(marketPage)return loadMarket();const c=new Contract(deployment[key].address,abi,rpc);const [supply,reserved,price,cap,revenue,manifest]=await Promise.all([c.totalSupply(),c.totalReserved(),c.MINT_PRICE(),c.MAX_SUPPLY(),c.REVENUE(),c.manifestHash()]);if(price!==parseEther('0.001')||cap!==7777n||revenue.toLowerCase()!=='0x23898f0866e4d5fa5c9b97645239ed635ea93cdc'||manifest!=='0x'+config.manifestSha256)throw Error('Contract configuration mismatch');$('#chain-state').textContent=`${supply} / 7777 · Reserved ${reserved} · 0.001 BNB`;
 const l=document.createElement('a');l.href='https://bscscan.com/address/'+c.target;l.textContent=c.target;l.target='_blank';l.rel='noopener';$('#chain-state').append(document.createElement('br'),l);}
$('#refresh').onclick=()=>action(refresh);
$('#mint').onclick=()=>action(async()=>{const signer=await checked();await refresh();const quantity=Number($('#quantity').value);if(!Number.isInteger(quantity)||quantity<1||quantity>50)throw Error(t('quantity'));const c=new Contract(deployment[key].address,abi,signer);await tx(c.mint(quantity,{value:parseEther('0.001')*BigInt(quantity)}));message(t('waiting'));await refresh();});
$('#settle').onclick=()=>action(async()=>{const signer=await checked(),c=new Contract(deployment[key].address,abi,signer),n=await c.nextToSettle(),request=await c.requests(n);if(!request.ready)throw Error(t('waiting'));await tx(c.settleNext(n));await refresh();});
$('#my').onclick=()=>action(async()=>{const signer=await checked(),owner=await signer.getAddress(),target=$('#owned');target.replaceChildren();for(const k of ['change','rabbit']){const c=new Contract(deployment[k].address,abi,rpc);const balance=await c.balanceOf(owner);let found=0;for(let start=1;start<=7777&&BigInt(found)<balance;start+=256){const ids=await c.ownedInRange(owner,start,256);for(const id of ids){target.append(card({id:Number(id)},k));found++;}message(`${t('my')}: ${k} ${found}/${balance}`);}}});
async function loadMarket(){const m=new Contract(deployment.market.address,marketABI,rpc),count=Number(await m.orderCount()),grid=$('#cards');grid.replaceChildren();const end=Math.max(0,count-page*24),start=Math.max(0,end-24);for(let i=end-1;i>=start;i--){const h=await m.orderIds(i),o=await m.orders(h);if(!await m.isActive(h))continue;const k=o.collection.toLowerCase()===deployment.change.address.toLowerCase()?'change':'rabbit',a=card({id:Number(o.tokenId)},k),p=document.createElement('p');p.textContent=`${formatEther(o.price)} BNB`;a.append(p);const button=document.createElement('button');button.textContent=t('buy');button.onclick=()=>action(async()=>{const signer=await checked();await tx(m.connect(signer).buy(h,{value:o.price}));await loadMarket();});a.append(button);const cancel=document.createElement('button');cancel.textContent=t('cancel');cancel.onclick=()=>action(async()=>{const signer=await checked();await tx(m.connect(signer).cancel([...o]));await loadMarket();});a.append(cancel);grid.append(a);}if(!grid.children.length)grid.textContent=t('empty');$('#range').textContent=`${start+1}–${end} / ${count}`;$('#prev').disabled=page===0;$('#next').disabled=start===0;}
$('#sell').onclick=()=>action(async()=>{const signer=await checked(),k=$('#sell-collection').value,tokenId=Number($('#sell-id').value),days=Number($('#days').value);if(!Number.isInteger(tokenId)||tokenId<1||tokenId>7777||!Number.isInteger(days)||days<1||days>30)throw Error('Invalid token ID or days');const price=parseEther($('#sell-price').value);if(price<=0n)throw Error('Invalid price');const c=new Contract(deployment[k].address,abi,signer);if((await c.ownerOf(tokenId)).toLowerCase()!==account.toLowerCase())throw Error('Not NFT owner');await tx(c.approve(deployment.market.address,tokenId));const latest=await wallet.getBlock('latest');const random=crypto.getRandomValues(new Uint32Array(4));const salt=BigInt('0x'+Array.from(random,x=>x.toString(16).padStart(8,'0')).join(''));const o={seller:account,collection:c.target,tokenId,price,deadline:latest.timestamp+days*86400,salt};const signature=await signer.signTypedData({name:'Butterfly Mid-Autumn Market',version:'1',chainId:56,verifyingContract:deployment.market.address},types,o);const m=new Contract(deployment.market.address,marketABI,signer);await tx(m.register(o,signature));await loadMarket();});
if(marketPage){$('#mint-controls').hidden=true;$('#gallery-description').hidden=true;$('#jump-controls').hidden=true;$('#prev').onclick=()=>action(async()=>{page=Math.max(0,page-1);await loadMarket();});$('#next').onclick=()=>action(async()=>{page++;await loadMarket();});}else $('#sell-controls').hidden=true;
paint();
try{[config,deployment]=await Promise.all([fetch('/nft/edition-config.json').then(r=>{if(!r.ok)throw Error('Artwork config unavailable');return r.json();}),fetch('/nft/deployment.json',{cache:'no-store'}).then(r=>r.ok?r.json():({status:'pending'}))]);if(!marketPage){items=await fetch(`${config.prefix}/${key}/catalog.json`).then(r=>r.json());const id=Number(new URLSearchParams(location.search).get('id'));if(id>=1&&id<=7777)page=Math.floor((id-1)/24);}paint();if(ready())await refresh();else document.querySelectorAll('[data-chain-action]').forEach(e=>e.disabled=true);}catch(e){message(e.message);}
