import test from 'node:test';import assert from 'node:assert/strict';import ganache from 'ganache';import fs from 'node:fs';import path from 'node:path';
import {BrowserProvider,ContractFactory,Contract,parseEther,ZeroHash,id,keccak256} from 'ethers';import {root} from '../scripts/compile.mjs';import {compile} from './compile.mjs';
const WRAPPER='0x471506e6ADED0b9811D05B8cAc8Db25eE839Ac94',REVENUE='0x23898F0866E4D5fa5C9B97645239eD635EA93cDC';
const source=`pragma solidity 0.8.30;import 'MoonCollection.sol';
contract MockWrapper {uint256 public nonce;uint256 public fee;function setFee(uint256 f)external{fee=f;}function link()external pure returns(address){return 0x404460C6A5EdE2D891e8297795264fDe62ADBB75;}function estimateRequestPriceNative(uint32,uint32,uint256)external view returns(uint256){return fee;}function calculateRequestPriceNative(uint32,uint32)external view returns(uint256){return fee;}function requestRandomWordsInNative(uint32 gasLimit,uint16 confirmations,uint32 words,bytes calldata args) external payable returns(uint256){require(msg.value==fee&&gasLimit==100000&&confirmations==20&&words==1);require(keccak256(args)==keccak256(abi.encodeWithSelector(bytes4(keccak256('VRF ExtraArgsV1')),true)));return ++nonce;}function fulfill(address target,uint256 requestId,uint256 seed) external{uint256[] memory a=new uint256[](1);a[0]=seed;MoonCollection(payable(target)).rawFulfillRandomWords(requestId,a);}}
contract Boundary is MoonCollection {constructor() MoonCollection('Change','CHANGE','https://zhongqiu.sh/nft/metadata/',bytes32(uint256(1))) {}function setSupply(uint256 n)external{totalSupply=n;totalReserved=n;}}
contract HostileBuyer {function buy(MoonCollection n)external payable{n.mint{value:msg.value}(1);}function onERC721Received(address,address,uint256,bytes calldata) external pure returns(bytes4){revert('reject');}}`;
const {collection:artifact,output}=compile({'Fixtures.sol':{content:source}});const raw=ganache.provider({logging:{quiet:true},chain:{hardfork:'shanghai',chainId:56},wallet:{totalAccounts:4,defaultBalance:100}});const provider=new BrowserProvider(raw);provider.pollingInterval=10;const signer=await provider.getSigner(),buyer=await provider.getSigner(1),other=await provider.getSigner(2);const receipt=async t=>(await t).wait();
await raw.request({method:'evm_setAccountCode',params:[WRAPPER,'0x'+output.contracts['Fixtures.sol'].MockWrapper.evm.deployedBytecode.object]});const wrapper=new Contract(WRAPPER,output.contracts['Fixtures.sol'].MockWrapper.abi,signer);await receipt(wrapper.setFee(parseEther('0.00001')));
const release=JSON.parse(fs.readFileSync(path.join(root,'collection-release.json')));const deploy=async(a=artifact)=>{const c=await new ContractFactory(a.abi,a.evm.bytecode.object,signer).deploy(...(a===artifact?['Change','CHANGE','https://zhongqiu.sh/nft/metadata/','0x'+release.manifestSha256]:[]));await c.waitForDeployment();return c;};const nft=await deploy();const price=parseEther('0.001');
const request=async(c,n,who=buyer)=>{await receipt(c.connect(who).mint(n,{value:price*BigInt(n)}));return await c.requestCount();};const fulfill=async(c,seq,seed)=>{const r=await c.requests(seq);return receipt(wrapper.fulfill(await c.getAddress(),r.vrfId,seed));};
await test('runtime bytecode pinned correctly; fixed terms and ERC721 interfaces',async()=>{assert((await provider.getCode(await nft.getAddress())).length>100);assert.equal(await nft.MAX_SUPPLY(),7777n);assert.equal(await nft.MINT_PRICE(),price);assert.equal(await nft.REVENUE(),REVENUE);assert(await nft.supportsInterface('0x80ac58cd'));assert(await nft.supportsInterface('0x5b5e139f'));assert(!artifact.abi.some(x=>['ownerMint','setPrice','setBaseURI','cancel','reroll','upgradeTo'].includes(x.name)));});
await test('reserve paid separately, exact NFT revenue; purchase reserves but does not assign IDs',async()=>{await assert.rejects(nft.connect(buyer).mint.staticCall(1,{value:price}));await receipt(signer.sendTransaction({to:await nft.getAddress(),value:parseEther('0.01')}));const before=BigInt(await raw.request({method:'eth_getBalance',params:[REVENUE,'latest']}));await request(nft,7);assert.equal(await nft.totalReserved(),7n);assert.equal(await nft.totalSupply(),0n);assert.equal(BigInt(await raw.request({method:'eth_getBalance',params:[REVENUE,'latest']}))-before,7n*price);assert.equal(await nft.buyerRequestCount(await buyer.getAddress()),1n);await assert.rejects(nft.settleNext.staticCall(await nft.nextToSettle()));});
await test('authenticated VRF; out of order responses cannot change settlement order',async()=>{await request(nft,3,other);await assert.rejects(nft.rawFulfillRandomWords(1,[123]));await fulfill(nft,2,55);await assert.rejects(nft.settleNext.staticCall(await nft.nextToSettle()));await fulfill(nft,1,123456);await receipt(nft.connect(other).settleNext(await nft.nextToSettle()));assert.equal(await nft.totalSupply(),7n);assert.equal(await nft.nextToSettle(),2n);await assert.rejects(nft.settleNext.staticCall(1));const ids=await nft.requestTokens(1);assert.equal(new Set(ids.map(String)).size,7);assert(ids.some((v,i)=>v!==BigInt(i+1)));for(const token of ids){assert(token>=1n&&token<=7777n);assert.equal(await nft.ownerOf(token),await buyer.getAddress());assert.equal(await nft.tokenURI(token),`https://zhongqiu.sh/nft/metadata/${token}.json`);}await receipt(nft.settleNext(await nft.nextToSettle()));const ids2=await nft.requestTokens(2);assert.equal(new Set([...ids,...ids2].map(String)).size,10);});
await test('accepted seed cannot be overwritten and zero seed is valid',async()=>{const seq=await request(nft,1);await fulfill(nft,seq,0);await fulfill(nft,seq,999);assert.equal((await nft.requests(seq)).seed,0n);await receipt(nft.settleNext(await nft.nextToSettle()));await assert.rejects(nft.settleNext.staticCall(await nft.nextToSettle()));});
await test('invalid quantity, underpayment, overpayment and fee cap rollback',async()=>{for(const [n,v]of [[0,0n],[51,price*51n],[2,price],[1,price*2n]])await assert.rejects(nft.mint.staticCall(n,{value:v}));const before=await nft.totalReserved();await receipt(wrapper.setFee(parseEther('0.02')));await assert.rejects(nft.mint.staticCall(1,{value:price}));assert.equal(await nft.totalReserved(),before);await receipt(wrapper.setFee(parseEther('0.00001')));});
await test('failed revenue transfer rolls back request, reserve and payment',async()=>{const before=await nft.totalReserved(),nonce=await wrapper.nonce();await raw.request({method:'evm_setAccountCode',params:[REVENUE,'0x60006000fd']});await assert.rejects(nft.mint.staticCall(1,{value:price}));assert.equal(await nft.totalReserved(),before);assert.equal(await wrapper.nonce(),nonce);await raw.request({method:'evm_setAccountCode',params:[REVENUE,'0x']});});
await test('50 random IDs without replacement, callback stays below gas limit',async()=>{const seq=await request(nft,50);const cb=await fulfill(nft,seq,987);assert(cb.gasUsed<100000n);const gas=await nft.settleNext.estimateGas(await nft.nextToSettle());assert(gas<5000000n);console.log('50 NFT settlement gas:',String(gas));await receipt(nft.settleNext(await nft.nextToSettle()));const ids=await nft.requestTokens(seq);assert.equal(new Set(ids.map(String)).size,50);assert.equal(await nft.totalSupply(),61n);});
await test('hostile receiver cannot stall FIFO and another caller cannot steal tokens',async()=>{const a=output.contracts['Fixtures.sol'].HostileBuyer;const bad=await new ContractFactory(a.abi,a.evm.bytecode.object,signer).deploy();await bad.waitForDeployment();await receipt(bad.buy(await nft.getAddress(),{value:price}));const seq=await nft.requestCount();await fulfill(nft,seq,44);await receipt(nft.connect(other).settleNext(await nft.nextToSettle()));assert.equal(await nft.ownerOf((await nft.requestTokens(seq))[0]),await bad.getAddress());});
await test('reserved supply cannot oversell; end of shrinking pool is complete and unique',async()=>{const edge=await deploy(output.contracts['Fixtures.sol'].Boundary);await receipt(signer.sendTransaction({to:await edge.getAddress(),value:parseEther('0.001')}));await receipt(edge.setSupply(7750));await assert.rejects(edge.mint.staticCall(28,{value:price*28n}));await request(edge,27);await assert.rejects(edge.mint.staticCall(1,{value:price}));await fulfill(edge,1,777);await receipt(edge.settleNext(await edge.nextToSettle()));const ids=await edge.requestTokens(1);assert.deepEqual([...ids].map(Number).sort((a,b)=>a-b),Array.from({length:27},(_,i)=>i+1));assert.equal(await edge.totalSupply(),7777n);await receipt(edge.sweepUnusedReserve());assert.equal(BigInt(await raw.request({method:'eth_getBalance',params:[await edge.getAddress(),'latest']})),0n);});
await test('bounded owner lookup includes received tokens and excludes another wallet',async()=>{const token=(await nft.requestTokens(1))[0];const start=(Number(token)/256|0)*256+1;const ids=await nft.ownedInRange(await buyer.getAddress(),start,256);assert(ids.includes(token));assert(!(await nft.ownedInRange(await other.getAddress(),start,256)).includes(token));await assert.rejects(nft.ownedInRange(await buyer.getAddress(),1,257));});
await test('normal ERC721 transfer after random allocation and invalid metadata',async()=>{const token=(await nft.requestTokens(1))[0];await receipt(nft.connect(buyer).approve(await other.getAddress(),token));await receipt(nft.connect(other).transferFrom(await buyer.getAddress(),await other.getAddress(),token));await assert.rejects(nft.tokenURI(0));const f=new ContractFactory(artifact.abi,artifact.evm.bytecode.object,signer);await assert.rejects(f.deploy('Change','CHANGE','',id('a')));await assert.rejects(f.deploy('Change','CHANGE','https://zhongqiu.sh/',ZeroHash));});await raw.disconnect();
